### ISSUE TITLE
Broken Scripted Spells (Possibly Others)

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#1000]
**Current behavior**: 
Scripted spells that cast spells that are not triggered, do not go through as planned
**Expected behavior**: 
Should go through
**Steps to reproduce**:
1.  Go to TBC translocation orb in ruins of lordaeron and use it

**Client version**: 
TBC

This check is the culprit, added by @cyberium 
`if (!m_IsTriggeredSpell && m_caster->IsNonMeleeSpellCasted(false, true, true))
        return SPELL_FAILED_SPELL_IN_PROGRESS;`

I dont think any such check should be made at all, or possibly it has to be much more complex.

**Comment by Phatcat** [comment]
Well, I don't think Cyberium is all wrong with that check.

I however agree with you that it is probably not as complex as it needs to be.

I see this as him trying to prevent people from using spells when they are already in the process of casting a spell (unless it is triggered). That doesn't seem wrong to me at all, on the contrary I think such a check is indeed something that shouldn't be removed; it frankly rather shows that scripts may be scripted wrong and that the scripted creature in question is trying to cast a spell while it is already casting; then it needs to stop casting first, just like we do in the CreatureAI. 
HOWEVER. This could also be failing if the m_caster->IsNonMeleeSpellCasted already in fact is set, since we are obviously getting a spell result; this could be a case sort of similar to the one about a lot of auras breaking themselves with the damage they initially do (all the engineering bombs that both damage and stun are broken, for this reason abviously - making goblin engineering pretty useless. Not as useless as gnomish engineering, though, where half the trinkets don't do a thing, or are very broken.)

**Comment by killerwife** [comment]
Well, to this day I havent come up with a way how to cast two spells from client at once :D And I am not saying that such a check shouldnt exist. But problem is, there are three types of triggered - bool triggered, triggeredByAura, triggeredBySpell, and for a lot of scripts, i dont think the scripter used them accordingly. (we have to keep in mind some scripts were made 6+ years ago when many of our systems were different)
So I disabled the check on my end until proper check/rewrites are done, because even if we proceed with it, someone has to rewrite all spelleffects and sd2 spell scripts for this to work properly.

**Comment by Phatcat** [comment]
>and for a lot of scripts, i dont think the scripter used them accordingly

Which is an issue entirely with the scripts, not our core, and so cyberiums check right there is even more so needed than not, because it tells us exactly which scripts are not done properly.

Always remember that the workflow is that the core dictates. the rest follows. What you do on your end, all up to you.

**Comment by killerwife** [comment]
Atm, its with both.

**Comment by Phatcat** [comment]
Also given the fact you want to introduce a spellscriptfactory (which I am totally behind by the way),
all scripts are basically in a need of a looksee once that's merged, as to see what to move to the generic factory and what to keep in the specific scripts, or have I got that all wrong? I tend to misunderstand things to the fullest xD

**Comment by Phatcat** [comment]
If spellcasting works outside of the scripts, then I don't see how it's a core issue, unless spellcasting is impossible to script given our current core, which it's not, I've seen lots of mobs cast spells.

**Comment by al3xc1985** [comment]
@killerwife  do you remember fixing this?
