### ISSUE TITLE
TBC Crash #2 with clean logs 

### ISSUE THREAD

**Issue by Cosmictis** [cmangos/issues#1033]
dead project

**Comment by Cosmictis** [comment]
@warlockbugs

**Comment by SilvioDoMine** [comment]
Getting the same here. #2

**Comment by SilvioDoMine** [comment]
@Cosmictis dead project?

**Comment by evil-at-wow** [comment]
Cosmictis means nothing gets done here. Imagine the laziness here: it's been two days and no one has fixed his/her bug yet! &lt;/sarcasm>

This brings back memories about Kelzior who also kept opening issues and then close them again a day later because we didn't act soon enough to his/her liking...

**Comment by SilvioDoMine** [comment]
Nobody is getting paid for this. It's our job to contribute as much as we can, and we can't demand nothing. They are doing their best, cuz their also have a life. If you can't wait, just do it by yourself then.

**Comment by dazidkk** [comment]
Silvio, can you explain whats causing this crash?
Would like to test it out regarding the Classic core.

**Comment by Phatcat** [comment]
I am always late to the party these days it seems, I just commented on the other issue he opened and closed.

Basically what evil-at-wow said, but with an added: If you provide a method of reproduction, a clear describtion of the bug as well as expected behaviour and sources. If we have all of those things surely we can move fast, but if there's not even a method of reproduction then we have to figure it all out by ourselves. we eventually will, but then expect quite a delay.

I know it can be hard to provide proper documentation on an unknown crash, but just imagine how harder it is to actually get it fixed.

Just take a look at how we are kind of having issues with the duplicate login crash as we can't properly reproduce it (I'm not about to install a whole other OS just for one crash, not yet at least)
