### ISSUE TITLE
[CLASSIC] Instant Cast Aura's and Mana Modifiers

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1034]
**Issue:**
Currently it handles the removal of instant cast aura's on hit which is supposed to be on spellcast start.
This results in making alot of Spells Bugged/Useless. 
**Example:**
lets say we shoot a frostbolt, and use Presence of Mind afterwards then once our frostbolt hits the target, it removes our Presence of Mind aura, without us ever getting the benefit from it.

**Which Spells the bug affect ( PROB MORE):**

**Nightfall (Shadow Trance):**
http://db.vanillagaming.org/?spell=17941
**Ascendance (Item: Talisman of Ascendance):**
http://db.vanillagaming.org/?spell=28200
**Clearcasting:**
http://db.vanillagaming.org/?spell=12536
**Netherwind Focus (ItemsetBonus: Netherwind Set T2 Mage):**
http://db.vanillagaming.org/?spell=22008
**Nature's Swiftness (Druid):**
http://db.vanillagaming.org/?spell=17116
**Nature's Swiftness (Shaman):**
http://db.vanillagaming.org/?spell=16188
**Elemental Mastery:**
http://db.vanillagaming.org/?spell=16166
**Presence of Mind:**
http://db.vanillagaming.org/?spell=12043

**Expected Behavious:**
The expected behaviour is that, these "Aura's" proc on spell start rather than spell hit.

Any tip/suggestions which might lead towards the fix is appreciated!

**Comment by Phatcat** [comment]
Look up the spells in the dbc properly instead of on db sites.

I recommend a tool such as Qt SpellWork, maintained by our very own @sidsukana : https://github.com/anathemareborn/QSpellWork/releases

This will give you so much more info about the spell; lets look up clearcasting for druids, provided by omen of clarity - looking up that spell gives us this info:

Proc flag 0x00015550, chance = 100, charges - 1
04 Successful attack by Spell that use melee weapon
06 Successful Ranged attack (and wand spell cast)
08 Successful Ranged attack by Spell that use ranged weapon
10 Successful spell hit
12 Successful spell cast
14 Successful cast positive spell
16 Successful damage from harmful spell cast

This is a bit misleading as you probably didn't mean proc the same way that they did.

I'm pretty sure an aura such as clearcasting doesn't get dispelled until you actively use a ressource - in which turn it negates the cost and just dispels itself.. no?

**Comment by dazidkk** [comment]
Thanks for the tip regarding Qt Spellwork, i have looked into it before, but i could never get it started keeps telling me some error, Regarding not able to find my dbc files even tho i set the path clearly into them.

**Regarding the Aura Clearcasting:**

What you described regarding the clearcasting aura, is the wanted effect.
But as it goes for the moment, it gets dispelled on target hit in the same kind of scenario as i described with Presence of Mind.

**Example:**

Lets make a new example, Lets say Clearcast procs as your already channeling a new spell, Then the effect disapears once that spell hits the target, making the clearcast aura useless, Never giving you the wanted effect.
( I hope you understood what i meant with this example :sweat_smile: )

**Comment by Phatcat** [comment]
Yes, I see what you mean now.

> Currently it handles the removal of instant cast aura's on hit which is supposed to be on spellcast start.

Was pretty clear from the start, I just love misunderstanding things.

**Comment by Phatcat** [comment]
This is still an issue

Related issues: 
https://github.com/cmangos/issues/issues/1833
https://github.com/cmangos/issues/issues/1580

**Comment by killerwife** [comment]
Fixed as of https://github.com/cmangos/mangos-tbc/commit/731c0748e31c99174139f1871d3fb55eace85d33 on tbc branch. Will port to vanilla over the coming weeks as usual.
