### ISSUE TITLE
Lava environmental damage

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1071]
(and possibly others)

**Current behavior**: 

The way in which lava is set to deal damage can be abused to lavawalk, as in if you jump out of the lava before you take damage, it seems the timer for when the damage is hitting is reset, so if you keep timing the jumps just right you can effectively lavarun for as long as you can keep it up.

To reproduce, travel to BRD, unlock the big gate, go inside the gate, jump down the lava and see how easy it is to do what used to be an almost impossible trip back in vanilla/TBC (don't see why it'd be different in wrath)

or, well.. you could also just try the big area inside blackrock mountain, probably easier to get to...

**Expected behavior**: 

You are not supposed to be near it without taking damage. This also goes for simply standing too close to it bust mostly it goes for not being able to 'lava jump' or 'laval walk' or whoever you wanna call it which has been possible on private servers.... always?

https://www.youtube.com/watch?v=CStaLR0ipxY Watch from about 7:22 - actually, watch the whole thing because it is actually a gem of a pvp ownage video. Really unbalanced, though.

**Comment by Chaosvex** [comment]
Lava hopping was possible on retail. The best known use is using it to skip BRD for MC attunement.

Take a look:
https://www.youtube.com/results?search_query=mc+attunement+lava
https://www.gamefaqs.com/pc/534914-world-of-warcraft/faqs/42533?print=1

**Comment by Phatcat** [comment]
Your link actually verifies one of the things that I'm saying, you can get damaged while standing close to the lava without actually touching it. If you don't believe me, watch https://www.youtube.com/watch?v=2q0oEJjCsZI

Lava hopping maybe was possible, but have you tried how lava hopping works in cmangos? because lava damage is cearly handled differently on retail than we do it in cmangos. in cmangos you can do literal lava jumping and take, not minimal damage, **no damage**.

**Comment by Chaosvex** [comment]
Watch from 2:18 on 0.5x speed to get closer to real-time - he only takes three ticks of damage during quite a lengthy hop, each of those ticks occuring when he's in the lava. I've performed this particular trick on retail for MC attunement during vanilla and on CMaNGOS and I recall taking damage in a pretty similar way on CMaNGOS - I certainly didn't take zero damage.

Re: "You are not supposed to be near it without taking damage.", I assume you're using 1:58 as an example of this since he's colliding with the lava every other time he takes damage. I wouldn't be that surprised if there are some differences in handling but it could simply be latency causing him to take damage when it appears that he's out of the lava or that tiny section of geometry still counting as lava.

**Comment by Phatcat** [comment]
> https://www.youtube.com/watch?v=CStaLR0ipxY Watch from about 7:22

It is however very apparent that this guy takes a lot of the damage ticks **outside** of the lava.

Hmm.... Looks like you are much more likely to take lava damage if the breath bar is sown. May just be a coincidence, though.

**Comment by Chaosvex** [comment]
As mentioned, it could simple by latency since we're talking 2-3 frames, hard to say though. 

I considered the effects of latency with the Gyrofreeze video clip too, although the difference there is that you have feedback from the server to indicate activation.

**Comment by Phatcat** [comment]
Closing this due to the discourse above.
