### ISSUE TITLE
[Classic] Skinning time

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1072]
**Current behavior**: 

Skinning takes 3 second, consequently.

**Expected behavior**: 

The duration it takes to skin something should be based off of your 'profession level category' or whatever you fancy calling it;

http://wowwiki.wikia.com/wiki/Skinning?oldid=338768

**OBS** - This only applies to vanilla, a static time was set somewhere during TBC; http://wowwiki.wikia.com/wiki/Skinning?oldid=672657

**Comment by Jaypy** [comment]
Seems to me that there is a progression in cast times, just not correctly, if wowwiki can be trusted (i assume it can.) For me the progression is:

Apprentice: 2 sec.
Journeyman: 2.5 sec.
Expert: 3 sec.
Artisan: 3 sec.

Since I'm under the impression that stuff like casttimes for the actual spells are defined in Spell.dbc which are extracted for the client itself by each dev, I don't see a particular elegant solution to this.

Perhaps something like the workaround in SpellMgr.cpp at line 140 But in this case:

        switch (spellinfo->Id)
	{
	case 8613:       castTime = 1;		break; // Apprentice Skinning
	case 8617:	castTime = 2;		break; // Journeyman Skinning
	case 8618:	castTime = 2.5f;	break; // Expert Skinning
	case 10768:	castTime = 3;		break; // Artisan Skinning
	default:						break;
	}

Ofc you might aswell add the previous workaround into the switch. And perhaps any other spells with seemingly defunct casttimes.

I know very little about how spells in general work on cmangos, but I gave it a shot. Feedback appreciated.

**Comment by dagochen** [comment]
With the new feature of spell_template as a database table you can simply change the values there.

**Comment by BareRose** [comment]
Looking at spell_template the spells indeed have different CastingTimeIndex values: 8613 has 5, 8617 has 20, 8618 and 10768 both have 14.

I'm not sure how many seconds a given CastingTimeIndex corresponds to, but 8618 and 10768 having the same is definitely wrong.

**Comment by cyberium** [comment]
The spell work fine for me and using CastTimeIndex as it should. (maybe this was fixed since?)
