### ISSUE TITLE
Multiple instances of Entangling roots

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1074]
**Current behavior**:

Currently you are able to have 2 entangling roots active (with a bit of setup, though)

**Expected behavior**:

Whenever a new Entangling roots is sucessfully applied to a target, if another target is currently entangled it should get immediately untangled.

**Steps to reproduce**:

1. Make a druid
2. Give your druids some levels
3. Get the talents 'Nature's Grasp'
4. Active nature's grasp, and have a (possibly lower ranked, maybe not even, can't remember exactly) entangling roots ready to cast.
5. Again, it's a bit of time since I last verified this issue so I don't remember if you gotta manually entangle your first enemy and a second enemy getting entangled through natures grasp won't cancel the first, or if it's the other way around. but basically using these spells you are able to have 2 rooted targets.

I will clean this up, I promise..

**Comment by Warlockbugs** [comment]
Already a functioning part of upcoming aura rewrite.

**Comment by Phatcat** [comment]
:+1::+1::+1:

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
WoTLK port is not finished yet as it needs more groundwork done for partial effect application. If you would like to have a carbon copy of TBC for WotLK as a temporary transitional but functional aura stacking, let me know.

**Comment by Phatcat** [comment]
Nah, I'm patient enough, Bugs. Very nice work :+1:
