### ISSUE TITLE
[TBC] Pet charmed: No action possible

### ISSUE THREAD

**Issue by Poloolop10** [cmangos/issues#1075]
**Current behavior**: 

Since commit: https://github.com/cmangos/mangos-tbc/commit/839ffa6cc212757faa6448c544b514db2f6aae1a , actions no longer works on the pet charmed : Returning, attack, passif etc.. 

**Steps to reproduce**:
1.  With a hunter, do quest for learn taming the beast.
2. Or with a demonist Enslaved the demon
3. Then change action and see the result and try returning (nothing works)

**Client version**:
TBC 2.4.3

**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/36d368150deabafb505c8b4b6341bf1e53cf9843

**Database version**: 
https://github.com/TBC-DB/Database/commit/a38dbd0

**Operating system**: 
Windows 7

**Comment by Poloolop10** [comment]
Nothing to do with it but testing the pet, creatures who cast spell charge, it's work now? (on my server it's ok)
https://github.com/cmangos/issues/issues/697

**Comment by BestServedMoist** [comment]
This is a big problem on TBC servers, since enslave demon is a big part in the way warlock works, i've tested this alot, seems like faction changes properly and minion pet gets applied.
But they are still not counted as "pets", hence you will get the following in your logfiles when you try to change either REACT_ state, or cast a spell that a charmed pet has.
PetHandler: A not pet trying to do unknown Action %i and spellid %i. Pet %s owner is %s

from the code:
PetHandler.cpp--

if (!pet)
    {
        sLog.outError("PetHandler: A not pet trying to do unknown Action %i and spellid %i. Pet %s owner is %s", uint32(flag), spellid, petUnit->GetGuidStr().c_str(), _player->GetGuidStr().c_str());
        return;
    }

Mobs will return to their default creatureAI and continue to do nothing.
(Hunter tame pet quests will return the same)

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/1109

**Comment by Phatcat** [comment]
should be taken care of in: https://github.com/cmangos/mangos-tbc/commit/ffa6bee216eedf295f16f8470a3285b9d2b6c4fd
