### ISSUE TITLE
[Classic] Problems with pets

### ISSUE THREAD

**Issue by DescCore** [cmangos/issues#1109]
Problem №1 pets are now on their own now they are uncontrolled.
<a href="http://tinypic.com?ref=2wrdi79" target="_blank"><img src="http://i64.tinypic.com/2wrdi79.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Problem №2 Pet can not be released from owner
<a href="http://tinypic.com?ref=21b6s1y" target="_blank"><img src="http://i65.tinypic.com/21b6s1y.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

@Phatcat I think the problem was caused due to changes  pets

**Comment by Phatcat** [comment]
@DescCore What you're pointing at is issues with the charm system, as those right there are not normal hunter's pets, they are charmed using the taiming rod; we are very aware of the current issues with that one, and are trying to resolve it. Thank you for reporting, but I am gonna close this one as it's very much yet another duplicate. Sorry.

**Comment by DescCore** [comment]
@cyberium you see bugs?

**Comment by Phatcat** [comment]
Yes, he is aware of the bugs, and they are getting sorted. Hang tight!

**Comment by killerwife** [comment]
Temporary workarounds are up on my public branch https://github.com/killerwife/mangos-tbc/tree/charmFixes

I suggest you use those for the meantime, because judging from the complexity of the task, the fixes are not coming anytime soon. My branch contains all "reverts" needed to make charms work well enough.
