### ISSUE TITLE
[CLASSIC] Pets following speed bug!

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1146]
**Current behavior**: 
Pets following speed bug! They going too slow and then dissapear ( Hunter, Warlock)
**Expected behavior**: 
When you summoned pets they following you too slow, if you accelerate - they dissapear ( like mounting)
Summoning @Phatcat  :))))
**Steps to reproduce**:

1. Create Warlock ( or Hunter)
2. Summon Imp
3. Run and you will see big distance from Pet to player. Pet's speed must go up when he loosing distance to player and then set to Normal when he got Player.

**Client version**: 2.4.3

**Commit hash**: https://github.com/cmangos/mangos-tbc/commit/99e508c52c805d1def882626e6ff79d1e52128c0

**Database version**: 
TBC 1.5.0
**Operating system**:  Windows 7 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
> When you summoned pets they following you too slow, if you accelerate - they dissapear

Ah, so that's what you meant. Oh, it's enough to keep this issue open, then, I'm gonna close the other one.

I'm somewhat sure that Cyberium actually looked into the following mechanic once again, but the thing is, it's not so cut and dry the issue, or the solution, because if you watch some of joana's leveling videos you will notice her pet disappearing on her more than once as a result of her outrunning it.

**Comment by cooler-SAI** [comment]
Ok, thank you @Phatcat  for the answer.  It will be good if you'll check speed issue. anywaythanks again )

**Comment by Phatcat** [comment]
Currently there's a PR waiting on both classic and tbc branches, once those are merged and ported to wotlk.

I was planning on looking into detail how they should behave when idle as well as how they should move around the character and follow the character, specifically the follow speed scaling I think @cyberium is actually already looking into, it was even a part of the prs for classic and tbc but got removed again since it wasn't optimal in his opinion. I'm sure he hasn't forgotten. It's generally considered polish, though, so it's not prioritized that high, really.

**Comment by cyberium** [comment]
Yes worked on it, it will need a specific work on it so i removed my work on it.
After https://github.com/cmangos/mangos-tbc/pull/139 merge i may be involved on this issue but there is some other priority before...

**Comment by Phatcat** [comment]
Yeah no, thats wrong. In tbc and classic they are not supposed to disappear when you mount up and they are supposed to keep up with your mount speed. Same for summoned guardians.

**Comment by killerwife** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.1.0
Warlock and Hunter pets will now be automatically dismissed when you summon a mount. These pets will return on dismount. This does not affect pet happiness for Hunters.

Vanilla only.

**Comment by Phatcat** [comment]
Alright, I was basing it on an old tbc video which must've been recorded prior to 2.1 then. Good catch.

**Comment by al3xc1985** [comment]
Tgis can be closed. Fixed in last exports
