### ISSUE TITLE
[CLASSIC] Fire Burn Radius Too Big?

### ISSUE THREAD

**Issue by BareRose** [cmangos/issues#1159]
**Current behavior**: 
Thus far only tested in Valley of Trials, but the burn radius of fires seems way too high. E.g. when I stand next to the butcher I get burned eventhough I'm outside the fire, not on it.
**Expected behavior**: 
Fire radius should be smaller AFAIK, would be good if someone can confirm for sure with vanilla footage.
**Client version**: 
1.12.1
**Commit hash**: 
[https://github.com/cmangos/mangos-classic/commit/15b5199d2171dab203fefcded58a69b9f50232f3](15b5199d2171dab203fefcded58a69b9f50232f3)
**Database version**: 
classic-db
**Operating system**: 
Windows 7 64-bit

**Comment by BareRose** [comment]
Collected some screenshots from Valley of Trials and Orgrimmar to demonstrate the problem. Getting burned this far away from the fire is clearly wrong.

![screen1](https://cloud.githubusercontent.com/assets/23365116/20467164/a5b1c51a-af81-11e6-8a36-792a57bab18e.png)
![screen2](https://cloud.githubusercontent.com/assets/23365116/20467165/a5c721d0-af81-11e6-9d51-c3854b600bbd.png)
![screen3](https://cloud.githubusercontent.com/assets/23365116/20467166/a5d5c226-af81-11e6-884d-64487e24806d.png)
![screen4](https://cloud.githubusercontent.com/assets/23365116/20467167/a5d68b34-af81-11e6-8d89-d70e57309feb.png)

Don't have time to dig through old classic videos to find the exact "correct" fire burn radius. @Phatcat seems pretty good at digging through old YT videos so he might know something on that.

**Comment by Saben65** [comment]
https://www.youtube.com/watch?v=80dk-HjCPFE&feature=youtu.be&t=1m18s

It is amazing what people made videos of back in the day.

**Comment by BareRose** [comment]
The angle isn't optimal to see the exact distance he's away from the fires, but from what I can tell the radius is smaller than on cMangos, though by less than what I expected.

Now we need to either confirm that all fires had the same radius in classic or get footage from other types of fires. Especially the one in the middle of the Valley of Trials NPCs doesn't seem right.

I've actually found something that can confirm the VoT fire is off (and it looks like the NPC positions are aswell, and there's something wrong with the rugs). [From Joana's speedrun](https://www.youtube.com/watch?v=SwLjJH8LXfc&feature=youtu.be&t=310)

**Comment by Phatcat** [comment]
It could explain the reason for this issue; https://github.com/classicdb/database/issues/297

I see they basically came to the same conclusion.

**Comment by Phatcat** [comment]
> (and it looks like the NPC positions are aswell, and there's something wrong with the rugs).

I think you got the angle mixed up a bit, focus on the female orc with bread in her hand, position the rugs using her position and orientation as a point of reference then the placement of objects seem to match joana's video fine.

**Comment by vovk** [comment]
@Phatcat, @BareRose this bug came from adding to spells Object scale in cores everywhere(in TBC the same, idk how in WOTLK, but i think the same).
For example charge have min range 8, and max range 25, but in mangos it have min range ~11 & max ~28(in tooltip it still 8-25). Object scale was added for getting melee swing/shot(ranged weapon) properly, but why it was added to spells idk.
So if fire burn(what spell id?) have radius 5(Combat radius) in core it will be ~8.
This is not DB issue.

**Comment by Phatcat** [comment]
So it's actually also what is causing this; https://github.com/cmangos/issues/issues/1052... interesting...

**Comment by BareRose** [comment]
> For example charge have min range 8, and max range 25, but in mangos it have min range ~11 & max ~28(in tooltip it still 8-25).

Ohh, could that be why my bow's min range has been feeling ever so slightly off? I thought I was just imagining things.

Eitherways, I guess we know what to do now: Make it so only melee attacks take Object scale into account.

**Comment by BareRose** [comment]
Looking through the code with VS I think the problem could be in UpdateModelData where the scale is applied to UNIT_FIELD_COMBATREACH. We may have to keep track of two different reach values for melee/ranged, or apply the Object scale modifier inline where it's relevant for melee.

**Comment by Phatcat** [comment]
We only need to keep track of one rach value, ranged reach values are handled through their respective spells, and it seems that the core doesn't currently respect that properly.
hunter auto shoot and auto shoot wand are considered spells, AutoRepeatSpells to be specific. 
I have a PR up for classic touching up on autorepeatspells, but in no relation to ranges, though.

**Comment by vovk** [comment]
@Phatcat ObjectScale was add when mangos was on svn( that was tbc, even not 2.4.3 :D Maybe even classic ). So all this things should be found manualy.
About Auto Shot idk. In TBC after 2.4.0 it range was changed fron 8-35 to 5-35(blizz remove dead zone 5-8 range). But now i see dbc files for auto shot in 2.4.3 & it shows range 0-35(but this change was added in WOTLK). So in theory right now core shoud do auto shot in combat range(0-5), because it takes range from dbc, but in range 0-~3 Auto Shot stops... And there is a question become. CMangos do everything right(blizz like), but... in 2.4.3 cast range was 5-35, in dbc range 0-35, so blizz did a hack before WOTLK. Or i don't understand something :)
@BareRose this is not so easy. Object scale needed for many things. For example interact range etc. This will be a hard work to chagne all this in proper way & not broke something.

**Comment by BareRose** [comment]
@vovk It requires changes in many places but only changed one thing (whether Object scale is taken into account) unless the root of the issue is deeper. With the possible hack you said maybe the distance would need to be checked in the spell itself, if the dbc range is 0-35 maybe blizzard did it this way so spells with minimum range just give out their own little "too close" message.

**Comment by vovk** [comment]
@BareRose i'll try to explain how things work. We take Fire burn spell( as i understand this one Torch Burn => 5680, that triggers 5679 in range 5 ). So we take gameobject with this aura(5680).
CMangos take this gameobject, saw this aura. Aura periodic trigger spel. So on aura update it will take spell 5679, take his range, than add GameObject(GO) scale(~3) into it & start to find people in radius from GO coordinates(x,y,z). It don't give a shit on Object scale of your character. So if you remove Object scale of character on login or whatever it calculates, you only break things like interraction with othr objects in world of you charecter, combat rich distanse & so on.  And GO still will cast spell 5679 on range ~8.
Hope now you understand how things works.
About Auto Shot. I have an idea after some sleep. It just don't tun off when char in melee range & switch on melee attack. When hunter get off this range it switch again to auto-shooting. For now this switching is buggy(glitching) + range of switching on melee attack ~8 yards & this is too bad for hunters. Maybe because blizz didn't want to turn off Auto Shot in mele range, they just remove messages from it & change 5 yards to 0. Something like that.
Again if we just remove object scle for player/pets, we will broke combat distance/interraction etc, but fix spells like Auto Shot, Charge, etc. And this is not right.

**Comment by Phatcat** [comment]
> So on aura update it will take spell 5679, take his range, **than add GameObject(GO) scale(~3) into it** & start to find people in radius from GO coordinates(x,y,z).

Where is this done in the code exactly? please tell me it's handled collectively somewhere and not totally scattered.. this here is what seems to be the issue more or less. It shouldn't add any gameobject scale to vary the spell ranges at all, we have no evidence for that at all, on the contrary we have evidence that such a thing leads to bugs and issues.

**Comment by vovk** [comment]
@Phatcat if i knew where, i'd already fixed this...
I think at spell create. I'm looking now in spell.cpp
```cpp
void Spell::AddUnitTarget(Unit* pVictim, SpellEffectIndex effIndex){
...
            if (m_targets.m_targetMask & TARGET_FLAG_DEST_LOCATION)
                dist = affectiveObject->GetDistance(m_targets.m_destX, m_targets.m_destY, m_targets.m_destZ);
            else                                            // Must have Source Target
                dist = affectiveObject->GetDistance(m_targets.m_srcX, m_targets.m_srcY, m_targets.m_srcZ);
....
}
```
Than i look in Object.cpp:
```cpp
float WorldObject::GetDistance(float x, float y, float z) const
{
    float dx = GetPositionX() - x;
    float dy = GetPositionY() - y;
    float dz = GetPositionZ() - z;
    float sizefactor = GetObjectBoundingRadius();
    float dist = sqrt((dx * dx) + (dy * dy) + (dz * dz)) - sizefactor;
    return (dist > 0 ? dist : 0);
}
```
And here we go. We already have in distance to target bounding radius...
And bounding radius adds at object create...

As a suggestion we can create new function with name like SpellDistance or refactor current with new argument **bool spell** & if it == 1, not use bounding radius.

**Comment by vovk** [comment]
void Spell::AddGOTarget(GameObject* pVictim, SpellEffectIndex effIndex)
{
...
float dist = affectiveObject->GetDistance(pVictim->GetPositionX(), pVictim->GetPositionY(), pVictim->GetPositionZ());
        if (dist < 5.0f)
            dist = 5.0f;
...
}
The same... Plus one more. I don't understand that check if dist < 5... 
For example: There is Trap(0-2 yards) but after such check it radius became 5 yards. So rogues cand disarm it, because range of Disarm Trap 0-5 yards. So they always will be trapped... :)

P.S. After such things some times i want to kill people :D Especially that one, that add filling targets in CheckCast function...

**Comment by Phatcat** [comment]
Oh, you just sounded so confident about it I thought you had seen it for sure in the core and knew just what and where. but yeah, why wouldn't you already have fixed it then.

also the spell bool you suggest would have to be a nonmeleespell bool, since melee abilities are considered spells and need to reach as far as normal melee attacks or things would get really inconsistent.

the if dist is < 5 then dist = 5, now that just seems really really strange and hacky.

Looks like this part of the core needs a bit of work..

**Comment by Ve1vet** [comment]
@Phatcat **bool** for all spells should be w/o exception. Function GetSpellRangeAndRadius gets radius properly, i check it. Spells have no effect on melee attack. So melee attack should stay as they are now. If something wrong with them, you can start find what is wrong there. But i think all will be ok, because object scale + object scale = ~5(a little bit more to make shure 2 points can contact).
But for spells you should remove object scale(bounding radius).

**Comment by Ve1vet** [comment]
@Phatcat i think a little. Bounding radius of caster should be removed for all spells wothout exception. But bounding radius of victim whould be present in rich destination.
If there will be some problems with melee hit, this will be another issue. With this i can help you for shure. I fix this part long time ago & i have a patch.

**Comment by BareRose** [comment]
> I fix this part long time ago & i have a patch.

@Ve1vet Care to share? Would be nice to have bounding radiuses work correctly (which would improve more than just fire radiuses). Makes sense that they'd be removed for spells, if removing it from spells (but not melee attacks) somehow still breaks melee that's indeed a problem with the melee attack implementation, making it a seperate issue.

**Comment by cala** [comment]
Closing this issue as trap activation radius was fixed earlier this year.
