### ISSUE TITLE
[Classic] [Ability] Shield Slam - Nothing to dispel

### ISSUE THREAD

**Issue by trulynullified** [cmangos/issues#1168]
**Current behavior**: Doesn't slam the target with your shield, if they don't have any magic effect on them.

**Expected behavior**: Slam the target with your shield, even if they have no magic effect is on the target.

**Steps to reproduce**:

1. Log in
2. Find a mob without any magic effects/auras on them (buffs & debuffs)
3. Try to shield slam

**Client version**: 1.12.1 (5875)

**Commit hash**: b818bf3a5bbdd6a4db2b2efae996038f99d0ae43

**Database version**: Classic DB version 1.7 "The Scourge's Capital". For core Classic z2684.

**Operating system**: Windows 10 Pro 64 Bit

**Comment by Laizerox** [comment]
I will reopen issues because this is part of partial effects application which is being explored and worked on by @Warlockbugs

**Comment by cyberium** [comment]
Lets play then i consider if its fixed, its fixed. Then later if you or @Warlockbugs improve it then its ok.
If we dont close it now there is high risk to forget this and let it open.

**Comment by Phatcat** [comment]
@Laizerox That argument could be applied to generally every issue with the words;
"Server is still under construction and subject to change"

The issue here was specifically that shield slam would result in a failed cast and the error message "nothing to dispel" - that won't happen anymore. 
However everything works internally actually has nothing to do with the issue at hand, and keeping it open makes no sense what so ever, since it would then in fact be a false report since it would NOT fail anymore (at least for that reason) and it will NEVER display the 'nothing to dispel' message, at least not with the current setup in the code.

**Comment by Warlockbugs** [comment]
This issue can be considered closed for now, because the CheckCast procedure is set to be dismantled for partial effect implementation in the future anyway.
