### ISSUE TITLE
Does not compile on Ubuntu ARM

### ISSUE THREAD

**Issue by MelvinGr** [cmangos/issues#1185]
Does anybody have any success compiling for ARM?

Seems like this problem has been around for a while, see: http://cmangos.net/printthread.php?tid=186
There seems to be some (related) progress made here: https://github.com/arcemu/arcemu/pull/386

**Comment by BeerfishWoW** [comment]
@namreeb has offered help in exchange for the means to buy a raspberry pi. ;) 
http://cmangos.net/thread-7237.html

**Comment by namreeb** [comment]
I have a raspberry pi now, so that offer is withdrawn :)

The problem is x86 specific asm instructions in a third party dependency, g3dlite.  It's not a very high priority.  I have been working on an alternative to the pathfinding code which will include a self-contained replacement for g3dlite.  ARM compile should work when that is released.  Probably sometime in the next month or two.

**Comment by ekg98** [comment]
Namreeb I am very interested in this because my father loves the game and I would like to make a reliable server for him using a Raspberry PI.  I don't have much programming experience besides a high school class in C.  Subscribing to this thread.  I am very interested.  Namreeb if you need anything I can provide let me know.

**Comment by katz1** [comment]
I managed to compile and run cmangos on my raspberry pi based on scrapes of changes littered all over the internet a while ago. It seemed to work fine for me, it may be useful for you as well.

Here is the patch I use:
http://pastebin.com/ZKNWcBPY

I also had to use the following flag for cmake:
-DUSE_STD_MALLOC=1

**Comment by ekg98** [comment]
Thank you I will try tonight.  However I have never used the patch command before.  For me its quicker to edit the files with a text editor.  I will let you know how it goes.

**Comment by ekg98** [comment]
Fails to compile for me.  I get a lot of errors compiling AAbox

**Comment by katz1** [comment]
I am sorry to hear that. It does work on my Raspberry Pi 3 Model B, do you have the same model?

I also used the -DDEBUG=0 flag for cmake by the way, but I doubt that would affect your errors.

You can apply the patch with: git am --signoff < Raspberry.patch

**Comment by ekg98** [comment]
Mine is a raspberry Pi 2.  Could that be the difference?  I was wondering maybe I have a different version of build tools.

**Comment by ekg98** [comment]
Sorry if I didnt get back with you right away.  I have been busy with my job but I will give it a try as soon as I can.

**Comment by ekg98** [comment]
Well I just tried it and it passed AAbox.cpp so far.  Going to take a while.  I don't think I will see it complete before I have to head to work.  Are you planning on including this into the main project?

**Comment by katz1** [comment]
> Are you planning on including this into the main project?

That is not for me to decide. Some core developer should verify the patch at the very least, I didn't even test compiling it on windows.

> PI. I did not change malloc with the flag.

I did have some troubles without that flag, but you can try it.

**Comment by ekg98** [comment]
I just tried both classic and tbc on raspberry pi 2.  They both work fine.  I am trying to port my characters over from another server to this raspberry pi but thats a different issue.

I did not have a problem compiling as usual without changing any memory allocation settings.

**Comment by ekg98** [comment]
I got all my chars ported over and it works like a dream.  I have not tried it yet but can I do a git pull on mangos so I can get updates? What will it do to the patch that I have installed for the raspberry pi?

**Comment by Muehe** [comment]
@ekg98 I think branching is the appropriate solution (starting on a clean master):

```
git branch raspberry
git checkout raspberry
git am --signoff < Raspberry.patch
```

Now having the patch on a branch you can update your master branch as usual and afterwards rebase your raspberry branch. That means "dis-applying" the patch, getting all the changes from another branch (master in this case) and then reapplying the patch.

```
git checkout master
git fetch
git pull
git checkout raspberry
git rebase master
```

This way  any potential merge conflicts will only affect your raspberry branch, which you could then reset to its previous (working) state.

**Comment by ekg98** [comment]
I appreciate the help guys.  I will have to try that out when I am first able.  I would like to research github and the shell commands more.  I only know what the tutorial has set forth.  So far I have Tbc running on a raspberry Pi 2.  I have performed git pull on my patched directory twice and its working so far each time.  My novice way to alleviate my problems I just tar gzipped the whole project.  Executable, source, maps, and database.  That way I can revert pretty fast to previous state.  Ssh the whole thing to a remote storage.  If I break it I can fix it at least.

Thanks guys.

**Comment by Muehe** [comment]
Basically you can not break anything, because you do not have push rights to the "remote", to say it in git terms, which is the repository on Github (use `git remote -v` to see your remotes). So you can trial and error as much as you want. If you run into any problems there is usually somebody on the IRC to get help from.

The only time your approach could be problematic for you, is when the files that are changed by the patch you are using are changed on the official repo as well. The changes could lead to something called a "merge conflict", which means the diff for one (or more) file(s) can not be applied because the file doesn't look as expected, while at the moment git automatically does a "fast-forward merge" when you pull, just applying the diffs of all new commits on the official (online) repo one after another.

If you would use a branch the default branch (master) of your local repo would take the place of the Github repo in the above scenario. That means there would still be merge conflicts when you rebase your raspberry branch, but you could still use your master branch, say for compiling your desktop server.

**Comment by cyberium** [comment]
Interesting but we cannot officially support arm build. Lack of manpower.
