### ISSUE TITLE
ad.exe virus detection

### ISSUE THREAD

**Issue by Rochet2** [cmangos/issues#1186]
**Current behavior**: 
Getting a virus detection
http://i.imgur.com/bDNJmjn.png

This seems to be introduced in the latest commit (see commit below)

**Expected behavior**: 
no detections

**Steps to reproduce**:

1. clone cmangos-tbc from https://github.com/cmangos/mangos-tbc
2. run virus detection on the source (or just the ad.exe)

**Client version**: 
none

**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/c1583424b9aa4b9cc3bc93781ceaa4bb6a2f5ab6

**Database version**: 
none

**Operating system**: 
windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
omg... @AlexDereka ?

**Comment by cyberium** [comment]
Thank it should be fixed, no more binaries will be provided in source itself.
However i'll setup AppVeyor to build also tools so you'll be able to download prebuild or release here -> https://github.com/cmangos/mangos-tbc/releases

**Comment by cala** [comment]
I'm puzzled... The picture in the initial report says "ElunaCore"...

**Comment by xfurry** [comment]
Actually many anti virus programs confuse mangos.exe files for viruses. Probably we should find a way to digitally sign the .exe file automatically

But I'm also confused of what just happened.

**Comment by cyberium** [comment]
Dont bother @AlexDereka from a long period of inactivity decided to push an exe.
It was already suspicious for me. Next following day this issue is opened. So enough evidence for me that we dont need anymore those binaries.
Even more when they can be build now by appveyor instead.
So i removed @AlexDereka from the organization he can always contact me if he still interested to work with us. And i decided to move all sleeping account in a special team with no right for now.
Any old dev interested to work with us could contact me or @xfurry to get push access.

**Comment by Rochet2** [comment]
> I'm puzzled... The picture in the initial report says "ElunaCore"...

Its just a folder name.
The issue is with the ad.exe specifically from that commit reported. Everything else is meaningless.
The virustotal in the main post is directly from github raw link of ad.exe from the commit that is reported. Seems like half of their scanners pick up something.

Sounds like a logical explanation and action, cyberium.

**Comment by Dramacydal** [comment]
@cyberium that's reasonable.

**Comment by Dramacydal** [comment]
It seems like old haters dug out some credentials and decided to remind everybody they are still here 😄
