### ISSUE TITLE
Build fails for WotLK core

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1189]
**Current behavior**: 
Core does not build an error is raised for std lib:
```
/dev/cmangos-wotlk/src/game/Unit.cpp: In function ‘SpellPartialResistDistribution InitSpellPartialResistDistribution()’:
/dev/cmangos-wotlk/src/game/Unit.cpp:85:45: erreur: ‘roundf’ is not a member of ‘std’
                     values[column] = uint16(std::roundf((100.0f - (arg * 7.5f)) * 100));
                                             ^
/dev/cmangos-wotlk/src/game/Unit.cpp:85:45: note: suggested alternative:
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/math.h:28:0,
                 from /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath:44,
                 from /dev/cmangos-wotlk/src/shared/Common.h:36,
                 from /dev/cmangos-wotlk/src/game/Unit.h:29,
                 from /dev/cmangos-wotlk/src/game/Unit.cpp:19:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/architecture/i386/math.h:382:14: note:   ‘roundf’
 extern float roundf ( float );
              ^
/dev/cmangos-wotlk/src/game/Unit.cpp:90:41: erreur: ‘roundf’ is not a member of ‘std’
                 values[column] = uint16(std::roundf(std::max(0.5f - (2.5f * std::abs((float(column) * 10 / 100) - (float(percentage) / 100))), 0.0f) * 10000));
                                         ^
/dev/cmangos-wotlk/src/game/Unit.cpp:90:41: note: suggested alternative:
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/math.h:28:0,
                 from /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath:44,
                 from /dev/cmangos-wotlk/src/shared/Common.h:36,
                 from /dev/cmangos-wotlk/src/game/Unit.h:29,
                 from /dev/cmangos-wotlk/src/game/Unit.cpp:19:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/architecture/i386/math.h:382:14: note:   ‘roundf’
 extern float roundf ( float );
```

**Client version**:  3.3.5

**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/cfb9da6cd2c1592720a076755f799a8b6a17c51e

**Operating system**: 
Mac OS X 10.6

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Thanks for your suggestion, it does not go through either:
```
/dev/cmangos-wotlk/src/game/Unit.cpp: In function ‘SpellPartialResistDistribution InitSpellPartialResistDistribution()’:
/dev/cmangos-wotlk/src/game/Unit.cpp:85:45: erreur: ‘round’ is not a member of ‘std’
                     values[column] = uint16(std::round((100.0f - (arg * 7.5f)) * 100));
                                             ^
/dev/cmangos-wotlk/src/game/Unit.cpp:85:45: note: suggested alternative:
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/math.h:28:0,
                 from /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath:44,
                 from /dev/cmangos-wotlk/src/shared/Common.h:36,
                 from /dev/cmangos-wotlk/src/game/Unit.h:29,
                 from /dev/cmangos-wotlk/src/game/Unit.cpp:19:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/architecture/i386/math.h:381:15: note:   ‘round’
 extern double round ( double );
               ^
/dev/cmangos-wotlk/src/game/Unit.cpp:90:41: erreur: ‘round’ is not a member of ‘std’
                 values[column] = uint16(std::round(std::max(0.5f - (2.5f * std::abs((float(column) * 10 / 100) - (float(percentage) / 100))), 0.0f) * 10000));
                                         ^
/dev/cmangos-wotlk/src/game/Unit.cpp:90:41: note: suggested alternative:
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/math.h:28:0,
                 from /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath:44,
                 from /dev/cmangos-wotlk/src/shared/Common.h:36,
                 from /dev/cmangos-wotlk/src/game/Unit.h:29,
                 from /dev/cmangos-wotlk/src/game/Unit.cpp:19:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/architecture/i386/math.h:381:15: note:   ‘round’
 extern double round ( double );
```
And the toolchains was provided to me by @evil-at-wow I have to remember where I got it from his instructions. But the only thing in is the gcc v4.8.5

**Comment by Warlockbugs** [comment]
Looks trivial at first, but we need to choose if we want to stick to a new standard naming or old fashion roundf call. I know that GCC 5.3.0 on Linux and current MSVC++ have no issues with that naming. Requesting some C++ wisdom: @cyberium @namreeb.

**Comment by evil-at-wow** [comment]
Functions like roundf are C99 functions defined in math.h if I remember correctly (I don't have the C/C++ specs in reach at the moment). So they are not really C++, but we all know you can use C functions in C++ as well, and in fact I would expect that including &lt;cmath&gt; in C++11 would also allow one to use C99's &lt;math.h&gt; functions. The fact that changing the code to use std::round also didn't work for @cala most likely means the &lt;cmath&gt; include is missing (in Unit.cpp). Adding the missing include should fix the error.
Nevertheless, my suggestion would be to use std::round (it's C++11, so OK to use).

Some background on cala's 'special' toolchain: the short story is that Mac OS X 10.6 doesn't have any C++11 compilers out of the box, so that would have left cala in the cold when we started using C++11 last year. Apparently he has no other choice than use Mac OS X 10.6 (for some old PPC applications), so all one can do then is build a C++11 compiler like GCC or clang yourself, so that's what we did. See [the wiki page](https://github.com/cmangos/issues/wiki/Getting-a-C--11-compiler-on-Mac-OS-X) I wrote about this for some more details.

**Comment by cyberium** [comment]
http://www.cplusplus.com/reference/cmath/round/
So yes ofc GCC4.8.5 should support it if we provide it the cmath include.
In the meantime i read about some gcc bug about roud so could you please try localy to add in include directive
```diff
diff --git a/src/game/Unit.cpp b/src/game/Unit.cpp
index 4214f8e..e0cad14 100644
--- a/src/game/Unit.cpp
+++ b/src/game/Unit.cpp
@@ -48,7 +48,7 @@
 #include "movement/MoveSpline.h"
 #include "CreatureLinkingMgr.h"
 
-#include <math.h>
+#include <cmath>
 #include <array>
 
 float baseMoveSpeed[MAX_MOVE_TYPE] =
```

**Comment by cala** [comment]
Thanks all of you for your feedback, unfortunately, whatever the include I use (math.h versus cmath) none of them build with std::round or std::roundf :(

**Comment by namreeb** [comment]
Are you somehow missing the -std=c++11 flag to your compiler?

```
<x1 ~> cat hi.cpp
#include <cmath>
#include <iostream>

int main()
{
  float a = 2.5f;
  int b = std::round(a);

  std::cout << "a = " << a << " b = " << b << std::endl;

  return 0;
}
<x1 ~> g++ -std=c++11 -o h hi.cpp
<x1 ~> ./h
a = 2.5 b = 3
<x1 ~> g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
```

But without -std=c++11 this will not compile.

**Comment by evil-at-wow** [comment]
I don't know why I missed this before, but looking at the error in the original post it is clear that adding the &lt;cmake&gt; include isn't going to fix this, because it's already included indirectly:
```
from /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath:44,
from /dev/cmangos-wotlk/src/shared/Common.h:36,
from /dev/cmangos-wotlk/src/game/Unit.h:29,
from /dev/cmangos-wotlk/src/game/Unit.cpp:19:
```

You will need the -std=c++11 compiler flag as namreeb says, but it would surprise me if that's not already the case. For starters, the CMake files should take care of that since September 2015 or so (I introduced the change myself in preparation of using C++1). Secondly, you'd get a lot more errors without that flag as we're using C++11 all over the place now, so I doubt you'd even make it to Unit.cpp without it. But I'd check it anyway with a verbose build.

Also, can you try to compile namreeb's little test program and see if that works? If that doesn't work either, could you please upload the /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath file somewhere so I can have a look?

**Comment by cala** [comment]
The devil is still here with this little bit of code:

```
hi.cpp: In function ‘int main()’:
hi.cpp:7:10: erreur: ‘round’ is not a member of ‘std’
  int b = std::round(a);
          ^
hi.cpp:7:10: note: suggested alternative:
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/math.h:28:0,
                 from /toolchains/gcc-4.8.5/include/c++/4.8.5/cmath:44,
                 from hi.cpp:1:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/architecture/i386/math.h:381:15: note:   ‘round’
 extern double round ( double );
```

@evil-at-wow you will find the cmath file [here](http://pastebin.com/MHcXsr5B)

**Comment by evil-at-wow** [comment]
Well, that looks pretty much what I expected. Sadly that means that apparently Apple's C library in 10.6 isn't really fit for a modern GCC, as GCC only aims to be a "conforming freestanding implementation". I'll refer to the ISO C standard and the GCC documentation for what this means exactly, but it basically means that GCC expects a C library being supplied by the vendor of the operating system that conforms to C standards and it looks some things are missing in Apple's C library for that to be the case.

I can't check what Apple's C library is capable of because I have no access to a Snow Leopard system these days, so I'm not sure how to proceed. We could have a look at the preprocessed output I suppose so we can check what defines are used by GCC on your system and what's included and declared by all the Apple C headers. I can't promise that this will teach me much more (let alone that this will lead to a fix), but I'm willing to give it a long shot. To minimize preprocessed output, I would continue with namreeb's little test program. Then do something like ```g++ -std=c++11 -save-temps -c main.cpp -o main.o``` (or whatever file name you've used) and share the main.i file (the preprocessed output) somewhere.

Long term, I'm afraid only more things like this will surface for you though. A modern Xcode and clang could solve several of these headaches for you I guess. Assuming your hardware is recent enough to run 10.9 or later (so not an old iMac from 2006 or so), you don't happen to have enough disk space left to consider options for a more recent OS version as well? I won't tell you what you should do or not do, I'm just wondering if things like a dual boot (10.6 + newer OS) or booting a newer OS from an external (USB) disk would be an option for CMaNGOS development?

**Comment by cyberium** [comment]
@evil-at-wow, @namreeb teach me the signification of using "std::round() vs ::round() vs round()"
I honestly didnt knew that we could use "::" without namespace.

I just asked @cala to test it
> replace int b = std::round(a); to  int b = ::round(a);

And it worked. Yes he his now able to build it.
Now i may need the implication of using that. Is that safe for other system too?

**Comment by evil-at-wow** [comment]
Yeah, using '::' without namespace is just using the global scope.

The implication of the change from std::round to ::round is that you're no longer using the round defined in the std namespace (C++11) but rather the one from global scope (C99 I think). The one in the std namespace has overloads for float, double, etc, while I think the one from C is double only (I don't have my specification here to check). So implications partly depend on the types you're passing because otherwise conversions happen (and from 'long double' to 'double' could be troublesome), but I think we should be OK in the core. Strictly speaking the included header also changes from &lt;cmath&gt; to &lt;math.h&gt; but the former typically includes the last anyway so not changing the include most likely works already. I don't expect other systems to have issues with this change either - Microsoft does not have a C99 compiler per se in Visual Studio, but they typically do support those parts needed for C++ standards.

In fact, if using ::round() works for cala, it means the headers for his 10.6 system's C library have C99 functions (as I would expect), so I'm a bit suprised that GCC didn't pick these up. As you can see in the cmath header he shared, a common way to implement the functions in the std namespace is simply to use the ones from global scope if they're available, like this (simplified):

```
namespace std
{
    using ::round;
}
```

But figuring out the details of why that doesn't happen requires a bit more in depth knowledge of GCC than I have I'm afraid.

But to conclude, I'd think that using ::round should work as well.

**Comment by cala** [comment]
Thank you very much all of you for looking into that issue. :)
