### ISSUE TITLE
Magic damage mitigation tables in Classic/TBC

### ISSUE THREAD

**Issue by Stryg** [cmangos/issues#1193]
Latest implementation of the non-binary resist table  is derived from this source:
https://web.archive.org/web/20090206211016/http://www.worldofwarcraft.com/info/basics/resistances.html

However, this table was discovered to be faulty by Elitistjerks. You can't actually resist 100% of the damage from spells or elemental melee swings in Classic/TBC. With EJ shutdown I was worried I would no longer be able to prove this definitively, but I've finally found it:

http://web.archive.org/web/20110808083353/http://elitistjerks.com/f15/t10712-resisting_magical_damage_its_relation_resistance_levels/

Some key posts: [[1](http://web.archive.org/web/20110810111041/http://elitistjerks.com/f15/t10712-resisting_magical_damage_its_relation_resistance_levels/p3/#post318760)] [[2](http://web.archive.org/web/20110810111044/http://elitistjerks.com/f15/t10712-resisting_magical_damage_its_relation_resistance_levels/p4/#post329567)] [[3](http://web.archive.org/web/20110810111039/http://elitistjerks.com/f15/t10712-resisting_magical_damage_its_relation_resistance_levels/p2/#post318579)]

The primary observation here is that the damage mitigation cap is not actually 75%, as has been assumed, because full resists are always rounded down to 75%, and therefore the damage mitigation cap eventually converges to 68~70%. This is true regardless of level difference and means the benefit from magic damage mitigation is ultimately non-linear as you approach the resist cap. This explains why you don't see abnormal amounts of full resists in videos of warlocks tanking Twin Emps, and the parsed data available in the linked thread from players tanking Blazing Guards and Illhoof Imps. There's proof in the thread for both Classic and TBC.

There's another interesting observation here: it's possible to reduce the chance for a fully unresisted hit below zero for elemental melee attacks specifically - a level 60 player tanking Baron Geddon for example should NEVER see a fully unresisted hit past a certain FR threshold (68% of the resist cap is a suggested number, so 215 FR) based on observed data. It's noteworthy that this rule would have been very important for tanking pre-nerf Hydross. Data suggests that for normal spells the 1% minimum chance to see a fully unresisted hit still applies.

A lot of strong efforts are put forth in that thread attempting to reverse engineer Blizzard's internal formula, but using Blizzard's own table and simply rounding 100% resists down to 75% and possibly rounding 0% resists into 25% resists at some breakpoint gives a very good approximation of the collected data. The final column of Blizzard's table should actually read: 80% chance to resist 75% of damage, 16% to resist 50% of damage, 3% to resist 25% of damage, and 1% to resist no damage.

**Comment by Warlockbugs** [comment]
Discussion has started here: https://github.com/cmangos/mangos-classic/commit/ea114d788c43dba6ed785a3dd1cd67c79a1ba182#commitcomment-19618880

**Comment by Stryg** [comment]
Something important about this find is that it actually squares all of the inconsistencies with the previous formula. You no longer need an exception for partial dots ticks and elemental melee attacks which were already known and easily proven to be impossible to resist 100%. Now we know that normal non-binary spells are also impossible to fully resist and any 100% resist die rolls are rounded down to 75%, just like with dots and elemental melee damage.

**Comment by Warlockbugs** [comment]
I gave it a thought. Here is my hypothesis.
The supporting factor for 75% max outcome for Non-binary could be that Blizzy were too lazy to modify existing or introduce a new resist die roll function to limit it at [1-chance] an re-used existing one with [1-100], and then just bounded resulting outcome index to be 4 when its > 4.
Another, more believable supporting factor for it may be the technical RNG limitation. My assumption is that they used a hardware RNG generator, which only supported doing full range rolls (i.e. 0-1.00, whatever was the original precision) and one couldn't order it do, let's say, [1-3650] roll, like we are doing currently. And then they went with simple (x > 4  ? 4 : x) for performance instead of recalculating all 5 bins within a cycle.
This will make 75% outcome skewed on graph.
However, the 1% spike chance's presence in PvP and claimed absense in PvE is the one i have no ideas about at the moment and it may throw the guess above out of the window. Any ideas? RNG shenanigans or subjective point of view? I'll try to rewatch Leo and Illidan warlock tanking PoVs if i can find any.

**Comment by Warlockbugs** [comment]
Leotheras: https://www.youtube.com/watch?v=gZcEniFQS9Q
Spell: 37675 (Considered non-binary, Fireball-like)
This video shows a large amount of full resists against lvl 73 boss.
Warlock has: FR (+70), MD (+70). Let's assume he has all infernoweave parts, which should push us above 68% mitigation already, not counting for possible cloak enchants, a'lar band and prismatic gems. The cloak is not 
At 5:08, warlock receives 5025 Damage (1005 split with pet). Which is equal to 100% of 3 debuffs applied (1675 damage per application).
So we got 2 extremes in one video: 100% resists and 0% seem to be definitely on the table for non-binary. Am i missing something here?

**Comment by Stryg** [comment]
The application of Chaos Blast is considered binary, it's not possible to partial resist. This makes sense considering the mechanics of the fight - you must have enough resists to prevent the dot from stacking or you will die. 

> With a fire resist of 365, the Warlock will take neither damage nor debuff 75% of the time, but full damage and debuff in the other 25%.
[Source](http://blessingofkings.blogspot.com/2008/03/leotheras-randomness-and-resists.html)

I don't think the 1% spike distinction is between PvE and PvP resistance rolls, but between spells and melee attacks (like Hydross). So, if the source of damage has spellinfo attached, assume the 1% minimum, else round into the 25% die face. Something like this.

**Comment by Warlockbugs** [comment]
Currently Chaos Blast is considered non-binary, as it's structure replicates Fireball, which is non-binary.
There is no DoT component at all:
0: SPELL_EFFECT_SCHOOL_DAMAGE
1: SPELL_AURA_MOD_DAMAGE_TAKEN

The base value of Damage is 1 and it deals significant damage only if player has at least 1 debuff application. I.e.:
First hit: 1 dmg, applied debuff.
Second Hit: 1675 dmg, add debuff stack.
Third Hit: 3350 dmg, add debuff stack.
And so on.
Debuff application is likely to be processed before dmg done due to 400ms batching on retail, so the first hit can be actually 1675 (using own vulnerability application), but this is out of the question.

For non-binary spells fully resisting damage part cancels application of any effects that follow it (in this case its an aura application). Full resist roll is done as part of the hit/miss die roll.

**Comment by Stryg** [comment]
The actual spell cast by Leo is spell 37674 (0: SPELL_EFFECT_DUMMY). This is the binary component that triggers spell 37675. I assume 37675 is considered unresistable as it's a trigger and the binary resist check is performed on 37674.

**Comment by Warlockbugs** [comment]
Frostbolt and the like are not a binary spell since patch 2.3. It's quite complicated to explain what binary and non-binary is over and over again, here is my implementation:
* [Pre-2.3 (with frostbolt as binary)](https://github.com/cmangos/mangos-classic/blob/master/src/game/SpellMgr.h#L297)
* [Post-2.3 (with frostbolt as non-binary)](https://github.com/cmangos/mangos-tbc/blob/master/src/game/SpellMgr.h#L321)

Long story short, any damage spell is non-binary, unless additional EffectMechanic comes into play (which isn't the case for Fireball and Chaos Blast). If EffectMechanic is present, it depends on the version of the game and effect execution order.

We have no details on how internally dummy child spells were actually processed, because, using Execute as an example, there seems to be no concrete rules defined, each dummy-triggered spell is different. Some indeed do skip hit/miss rolls and use dummy result, while others don't. That's exactly why new internal triggered flags were introduced to all cores, to handle it on per-spell basis. Right now 37674 is binary, while 37675 is not.

**Comment by Stryg** [comment]
Well, hold on, where are you getting this claim that Frostbolt was changed to be non-binary in 2.3? That change was made in WOTLK, when the entire resistance system was overhauled.

> Partial Resists
Every spell with a damage component can now be partially resisted.
Level-based partial resists are still in the game, but do not follow the strict 25%/50%/75% pattern any more.
[source](http://web.archive.org/web/20091108152029/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_ptr/)
> It's like the 5% from chilled to the bone "buff" to frostbolt but taking into acount the 5% loss to the spell to to newly affected resistances and a net 3% less spell hit to the spell, where is the buff really?
[source](http://web.archive.org/web/20091110014102/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_ptr/p11/)
> Due to partial resists on frostbolt the 5% buff later in the tree is negated, and frostbolt lost 3% spell hit.
[source](http://web.archive.org/web/20091110014142/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_ptr/p16/)

The infamous ['ghost hit'](http://web.archive.org/web/20080802042636/http://elitistjerks.com/f31/t18441-mage_sweet_informational_thread/p42/) bug that was giving Frostbolt an additional +3% hit for the duration of TBC was theorized to be the result of some misinteraction with the spell's binary hit calculation.

Whether you are performing the resist check on the dummy effect or the triggered effect here, Chaos Blast should be considered binary because it applies non-damaging aura SPELL_AURA_MOD_DAMAGE_TAKEN.

**Comment by Warlockbugs** [comment]
The first mention of Frostbolt having partial resists earlier than 3.0 was made as a reply to a question about partial resists in early 2009 in some obscure forum thread which i am trying to find in my history. It referenced this article. [One more mention found on wowhead](http://www.wowhead.com/spell=116/frostbolt#comments:id=781627) in mid-2009 (during 3.1.x, before 3.3.0 PTR even started - [October, 2009](http://wowwiki.wikia.com/wiki/Public_client_builds)). All of this is earlier that 3.3.0, so it's ruled out. It leaves us with either 2.3.0 or 3.0.0.
A few combat logs with Frostbolts i have are dated summer 2007 and vanilla, so it's not much of a help here.
I'll see if i can get a list of fitting spells for checking.

**Comment by Stryg** [comment]
Okay, I see what happened. The PTR thread was simply renamed for each PTR session, which is why it's over 200 pages long. I can't explain why that wiki page suggests patch 2.3 as simple a typo, then, but you can see that the first replies to that thread are October 2008. Well, it's certainly not the first time in history that a wowwiki page has been wrong (especially one as obscure and undeveloped as this).

The complaints from frost mages in that thread Frostbolt is now subject to partial resists and thus level based resists is all from October 2008 during the first WOTLK PTR sessions.

You can also just look at the Mage thread on EJ : [source](http://web.archive.org/web/20080811094101/http://elitistjerks.com/f31/t18441-mage_sweet_informational_thread/)  The OP was created after 2.3 hit, and still says in August 2008:
> Frostbolt, however, is a binary spell, meaning it has special rules regarding magic resist. A binary spell can only hit or miss; it will not ever partially resist. Because of this, frostbolt is completely unaffected by level based magic resist.

**Comment by Warlockbugs** [comment]
Patches for all main branches are complete and currently being tested. The progress made:
* Binary/Non-binary detection reshuffled once again.
* Damage cut-off for NPC spells, elemental attacks, environmental damage (Lava, Fire) is now simulated.
* Non-binary spells casted by NPCs can no longer be fully resisted by magic resistance, but can be cut-off.
* Vanilla: DoTs originated from binary spells use only 1/10 of resistance mitigation per tick.
* Vanilla: DoTs originated from non-binary spells use regular resistance mitigation per tick (should cover DoT exceptions you mentioned).

**Comment by lequintal69** [comment]
@Warlockbugs @Stryg 

1- Regarding damaging DOTs in Vanilla (corruption, curse of agony, shadow word: pain), if i understood you correctly, there should be both a binary roll upon application and a non-binary roll for each dmg tick?

2 - Regarding the 1/10 mitigation claimed by that GM, how can we be sure it was the case BOTH for the binary AND the non-binary roll? 
Also, he says "in general", so how can we be sure each and every dot follows that rule ? 

In my opinion and from what i have seen, it could very apply to the initial binary roll only. The guy the GM was answering to just vaguely said "affliction spells (dots, fear) are getting HEAVILY resisted" which could be refer solely to the binary roll, which is easier to notice and could explain the outcry, while an increase of partial resistances is harder to notice, especially since ppl dont run heavy shadow resistance gear in pvp.
Also, the GM just said that "dots in general were 1/10th as likely to be resisted as normal spells. That has been fixed, they're now as likely to be resisted as other spells", which doesnt clearly refer to the non-binary roll. 
Maybe i'm just nitpicking, but i thought it wasnt clear enough.

Regarding empirical data, i could find no video of DOTs getting "chain" resisted upon application against spriest or SL lock for exemple.

As for partial resists, some data i could find

=>Saerdna 3 - shadow resistance: 10
https://youtu.be/SRXUTgrZOvM?t=16m55s
2 half partial resistances on corruption in that fight

=>R13 Druid PvP – Unstoppable – estimated shadow resistance: 20 to 40
https://youtu.be/tXgsBdLQfvU?t=16m3s
3 partial resists of shadow word pain (25% 25% then 50%) from a single dot



what do you think?


Paul

**Comment by Warlockbugs** [comment]
1) DoTs are, in fact, just a component of a spell, an aura one. If there is no direct damage components within the spell, it ends up being binary. So "pure DoTs" are always binary on application. If there is a damage component in it next to a DoT (Fireball), the spell follow non-binary rules on application. 
2) There is no such thing as "DoT spells". Internally, its either binary or non-binary spell with a DoT component in it. Affliction spells, on the other hand, are almost all exclusively binary, which is what they meant by "DoT spells". I suggest following the discussion buried in the first post, which leads to commit comments. Empirical data for some raid encounters mentions low effectiveness of resistance against specific DoTs. Upon closer inspection of provided examples, it turns into a rather simple division of DoT effects originating from binary and non-binary spells. I came to conclusion, that GM reply about low effectiveness of resistance was addressing partial resists, upon closer inspection of vanilla combat log samples i have. A particular one was recorded in november of 2006 against a high resistance target, just before the change. In this sample, binary spells were fully resisted very often to even consider 1/10 rate for so-called "DoT spells" (or binary spells). So, deduction leaves us with tick damage for DoTs they mentioned.

I hope, this clears it up. The issue is not abandoned, the change i described a month ago is still on it's trial run.

**Comment by Warlockbugs** [comment]
However, one question remains unanswered, and this is the target of 1/10 coefficient.
Two possible options:
a) Apply 1/10 to effective resistance chance (this reduces 75% resistance to 7.5%).
b) Apply 1/10 to each individual outcome chance, with the exception of full hit.
In the current edition of the patch I went with option a). You can help by providing more empirical data on partial resists from videos. From your notes, b) may also be the case, because partial resists on low resistance targets should not be that common in case of a).

**Comment by lequintal69** [comment]
@Warlockbugs 
 
Yes, i definitly need to look for more data. The first one i posted shows 2x half damage corruption's tick on a undead with just 10sr from racial passive, but it could very well be just lucky RNG.
I will try to find more.

Regarding the binary roll using the regular formula, that means using 300 sr set should lead to 75% resist chance against the application of pure dmg DOTS, which is arguably good i guess :)

**Comment by lequintal69** [comment]
Found that comment about DOTs nerf:
"Apparently the change that makes DoTs 10 times more likely to be resisted only applies to partial resist checks made on each tick, IE when they're cast on someone with shadow resistance. It's always happened, it just happens as often as, say, Shadow Bolt now, whereas before it would only happen once in a while"

https://forum.quartertothree.com/t/wow-big-ole-nerf-bat-to-locks/32506/23

**Comment by lequintal69** [comment]
@Warlockbugs 
Hey, 
would you mind sharing the combat logs samples you have showing high resistance of binary spells (dots) against high resistance targets?

**Comment by Warlockbugs** [comment]
I don't have DoTs for vanilla. Binary excerpts i have are for application only, and this is Frost Mage binary spells (Frost Nova, Frostbolt) against a target with a high frost resistance. Which is enough to judge DoT application, but that's also why i am asking about any other source specifically for DoT ticks.

**Comment by Warlockbugs** [comment]
All changes were tested and finally implemented.
