### ISSUE TITLE
Blink doesn't work as it's supposed to

### ISSUE THREAD

**Issue by Lillecarl** [cmangos/issues#1245]
**Current behavior**: 
Blink blinks straight forward in horisontal position, doesn't matter where objects or ground are.
**Expected behavior**: 
Should care about ground and objects.
**Steps to reproduce**:
1.  *Blink

**Client version**: 
2.4.3
**Commit hash**: 
e98aae8ad633f05a1e8abbb5040ded46376c96b7
**Database version**: 
Some half oldish database.
**Operating system**: 
Windows

Reverting this commit fixes blink: https://github.com/cmangos/mangos-tbc/commit/ab737f13e946517350867cf6b3bacb2dd784287a

**Comment by Lillecarl** [comment]
@killerwife

**Comment by Lillecarl** [comment]
Effect 0: Id 29 (SPELL_EFFECT_LEAP)
BasePoints = 0
Targets (1, 47) (TARGET_SELF, TARGET_DYNAMIC_OBJECT_FRONT)
Radius (Id 9) 20,00

Apparently target is 47, not 55 as code suggests?.

**Comment by Lillecarl** [comment]
```
diff --git a/src/game/Spell.cpp b/src/game/Spell.cpp
index 962db64..2c4a948 100644
--- a/src/game/Spell.cpp
+++ b/src/game/Spell.cpp
@@ -2356,7 +2356,7 @@ void Spell::SetTargetMap(SpellEffectIndex effIndex, uint32 targetMode, UnitList&
                 m_targets.setDestination(dynObj->GetPositionX(), dynObj->GetPositionY(), dynObj->GetPositionZ());
             break;
 
-        case TARGET_DYNAMIC_OBJECT_FRONT:
+        
         case TARGET_DYNAMIC_OBJECT_BEHIND:
         case TARGET_DYNAMIC_OBJECT_LEFT_SIDE:
         case TARGET_DYNAMIC_OBJECT_RIGHT_SIDE:
@@ -2564,6 +2564,7 @@ void Spell::SetTargetMap(SpellEffectIndex effIndex, uint32 targetMode, UnitList&
             }
             break;
         }
+        case TARGET_DYNAMIC_OBJECT_FRONT:
         case TARGET_DEST_CASTER_FRONT_LEAP:
         case TARGET_RANDOM_CIRCUMFERENCE_AROUND_TARGET:
         {
```

This diff will "fix" the issue. (Make blink work, break something else?).

**Comment by killerwife** [comment]
Thats because you are not looking at player version of blink. Player version is TARGET_55 Spell ID=1953.
My code only fixed proper sending of destination in SMSG_SPELL_GO packet, no logistical changes were done. If you wish to fix non-player blink spells, then its quite possible that what you are suggesting is correct. I moved targeting calculation from SPELL_EFFECT_LEAP to SetTargetMap, meaning all spells need to go through this in SetTargetMap which have this effect to correctly compute it. But careful TARGET_DYNAMIC_OBJECT_FRONT is used for non-movement skills as well and maybe should have different behaviour.

**Comment by Lillecarl** [comment]
@killerwife i looked with sidsukanas old 2.4.3 spellworks, and i couldn't find any spell with TARGET_55.

I might be all wrong though, i'll be back with more info =)

**Comment by killerwife** [comment]
http://imgur.com/a/EVEZm yes you are I am afraid

**Comment by Lillecarl** [comment]
Thanks! I was wrong!
