### ISSUE TITLE
[CLASSIC] Songflower Serenade, Demon Armor, Mark of the Wild Can't Coexist

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1280]
**Current behavior**: 
The same situation also exists in: Warlocks Curse of Shadow and Curse of the Elements .etc
**Expected behavior**: 
Maybe the Aura Stacking system have something not calculated?
**Steps to reproduce**:

1.  15366 Songflower Serenade
2. 1086 Demon Armor
3. 9884 Mark of the Wild

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/tree/963616fa3a87486973f52b72808d6db15c33247b
**Database version**: 
z2694_01
**Operating system**: 
WIN 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by wowmui** [comment]
@Warlockbugs  Thank you first.

**Comment by Warlockbugs** [comment]
There is a version incompatibility present. Demon Armor counts as magic buff in Classic (and therefore can be dispelled), while this isn't the case as of TBC and onward. Dispel type hint currently is used to push off scroll buffs with class buffs and vice versa. Songflower Serenade is also affected, because it counts as a magic buff with similar stats to Mark of the Wild, which causes the same result.
Most of the data i have is TBC and WotLK. You can help by providing more classic sources: this includes videos, screenshots, guides where stacking is mentioned, so, hopefully, more hints can be picked up, resulting in much better filters afterwards. 
I don't want to return to old hardcoding and "same icon" hacky practices, as it became evident after 10 years, that it leads nowhere. This makes auras a "forever WIP" kind of stuff, because of too many variables in place, including possible hacks on retail side.

**Comment by wowmui** [comment]
I agree. I hope find some pattern in classic filters. How do I actually help?

**Comment by Warlockbugs** [comment]
Anything that shows or mentions something stacking or not stacking for armor buffs and stat buffs specifically to classic, if you happen to stumble upon it. I am accumulating and analyzing this data myself for TBC and WotLK, while vanilla mostly gets TBC backports. But some expansion-specific things don't match well between vanilla and TBC. Some armor self-buffs being a dispellable magic buff is one of them. Currently i don't have a solution for this particular issue, because it conflicts with scrolls logic.

**Comment by cala** [comment]
I can confirm this issue and that those spells could coexist together back in Classic days.

**Comment by cala** [comment]
With https://github.com/cmangos/mangos-classic/commit/fb5288774484c17520bdc124ed6b623b5878a4ba Demon Armor and Mark of the Wild can now coexist. However, there is still a conflict between Songflower Serenaed and MotW.

**Comment by cala** [comment]
And in https://www.youtube.com/watch?v=6CNN_Cn2L2A, we can see that Songflower Serenade and MotW did coexist in Classic times, as mentioned here.
