### ISSUE TITLE
Creature Linking Crash on SetInCombat

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#1316]
https://gist.github.com/killerwife/b6ef0c810dfca1ffa5fdb3863e063043

Following crash occured.
(gdb) p slave_itr
$1 = Cannot access memory at address 0x10
(gdb) p slaveGuidList
$2 = std::list = {[0] = {m_guid = 17379391325870891269}, [1] = Cannot access memory at address 0x10

Should anyone have any ideas how to solve this, let me know. If anyone wants, I can provide the necessary info, since this is from voa core. I can guarantee the code in the execution path is 1:1.

Crash occured on following line slaveGuidList.erase(slave_itr++);

**Comment by boxa** [comment]
hm. for me works years below code w/o any issues

replace:

slaveGuidList.erase(slave_itr++);

on

``` c++
        Creature* pSlave = pSource->GetMap()->GetCreature(*slave_itr);
        if (!pSlave)
        {
            // Remove old guid first
            ____slave_itr = slaveGuidList.erase(slave_itr);____
            continue;
        }
```

need make commit for it i think

**Comment by killerwife** [comment]
Why is it dangerous?

**Comment by evil-at-wow** [comment]
It's dangerous because containers typically invalidate iterators to erased elements, so before you know it you'll be using an iterator that is no longer valid (which will cause havoc, of course).

The code in this particular case - ```list.erase( itr++ )``` - is fine because you're using a postfix increment.
This is because the postfix increment operator updates itr to point to the element following the one you're about to erase, and then *returns the old value* so erase will use and invalidate the old value (the one you actually intended to erase) and all is still fine because itr was already updated and stays valid. But many people don't realize it only works fine because of that, and that makes it dangerous. If someone ever changes this to a prefix increment, say because it turns out you had a bug and actually wanted to delete the next element, then you're in for extra fun caused by invalidated iterators.

To avoid such subtle things, the erase function of std::list (and std::vector etc) returns a valid iterator pointing to the element after the erased one, so code like ``` itr = list.erase( itr ) ``` is more idiot proof, to say so.

&lt;/C++ lesson&gt; :smile:

**Comment by killerwife** [comment]
@evil-at-wow but I knew that. How does it fix the above crash? :)

**Comment by evil-at-wow** [comment]
Oh, and as to why it crashed: it looks like your debugger is telling you that slave_itr is already slaveGuidList.end() when you print it. So it's "past the last element". That is still a valid state, but doing ```slaveGuidList.erase(slave_itr++)``` next will crash because doing a postfix increment on it is not allowed. 

You'll have to figure out why slave_itr is already at end(), or avoid doing the erase with that value.

**Comment by evil-at-wow** [comment]
And it doesn't fix the crash. It if does fix the crash, it's by accident because it avoids a crash in the postfix increment iterator and doesn't crash in erase in your STL implementation.

But you are not allowed to pass the end() iterator to erase either, so don't do that!

**Comment by killerwife** [comment]
The question becomes whether we really did something stupid here, or if its a memleak/wrong memaccess/write. Thats the reason i posted this crash in the first place :)

**Comment by BenDol** [comment]
has this issue surfaced again for anyone else?

**Comment by killerwife** [comment]
Resolved long time ago. Was due to wrong iterator use after c++11 conversion
