### ISSUE TITLE
[Classic] Quest: Plagued lands

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1361]
I cannot capture a _Rabid Thistle Bear_ in quest _Plagued Lands_ (2118).
After placing the trap (Tharnariun's Hope, 7586) some red circles on the ground appear, but luring a _Rabid Thistle Bear_ in it has no effect. I also tried defeating the bear in it, and placing the trap directly under a bear.

Note that while placing the trap the cast bar displays _Failed_ at the very end, even though the trap appears visually afterwards. I believe this quest used to work some time ago.

![plagued_lands](https://cloud.githubusercontent.com/assets/18726138/25632631/a73095c4-2f74-11e7-8ffa-5ed8ccf07a33.jpg)

**Comment by killerwife** [comment]
Afaik classic is using my code for the quest which was merged by @cala. Do you have latest SD2 and DB?

**Comment by katz1** [comment]
I believe I have. I pulled on both mangos-classic and classic-db, and run the db install script just before posting this issue.

**Comment by cala** [comment]
> Afaik classic is using my code for the quest which was merged by @cala.

I just tested the PR and gave my approval. It was @cyberium who did the merge and backport, blame him! And ask @Tobschinski to help you.

The SQL updates proposed in the PR were missing from Classic DB, this is fixed by https://github.com/cmangos/classic-db/commit/8203682493f4f0eb1b0f528daa109a3eeeb4d232

Thanks both of you.

**Comment by killerwife** [comment]
Ye, I was so preoccupied when it was merged that I completely forgot to notify u about it. GJ anyway.
