### ISSUE TITLE
Extractors are not working

### ISSUE THREAD

**Issue by Flameshot** [cmangos/issues#1391]
**Current behavior**: 
When I try to compile the the ad.exe project I have errors related to .cpp files missing and I don't find them in core.

lipmpq/extract.cpp
libmqp/huffman.cpp 
etc.

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/be949ce84302c4f0cf6220160ad1e854822a073c
**Database version**: 
https://github.com/cmangos/tbc-db
**Operating system**: 
Windows Server 2016

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Flameshot** [comment]
Ok I downloaded the extractors from releases binaries but when I try to extract vmaps I have this error
using Buildings as source directory and writing output to vmaps
Could not read dir_bin file!
exit with errors

**Comment by Phatcat** [comment]
the extractors from the release binaries only work with that specific verison, and since only exctractors are offered up in the release binaries for wotlk, then it won't work with either classic or tbc. Too bad pre-build extractors never made it into the pre-build binaries as per the commit message of when they were taken out of the repos; https://github.com/cmangos/mangos-classic/commit/69d4ff54f3d35216ceb00c0ed7f425b21dab394f

There are pre-extracted files ready however, links are in these comments;

classic : https://github.com/cmangos/mangos-classic/commit/69526162accbe586e4457183a683d54444fd727d#commitcomment-20229996

tbc : https://github.com/cmangos/mangos-tbc/commit/277e1362763dad25a5fb7bde26b4c062baed2d66#commitcomment-20197107

**Comment by cyberium** [comment]
@Phatcat Extractors prebuild binaries are provided for all cores on windows.
Just download the zip file in release section extract it and you'll found a folder called Extractors.

For the issue itselfs, Dont uses provided sln, i'll remove them all soon. You have to use CMAKE to generate an compatible sln that contain extractors.

**Comment by Flameshot** [comment]
@cyberium  @Phatcat  Ok fixed thanks
