### ISSUE TITLE
[playerbot for classic]

### ISSUE THREAD

**Issue by vurtnezheng** [cmangos/issues#1411]
1. can u pullrequest ai from yyhhrr/portalclassic yyhhrr is great playerbotai
yyhhrr optimized a lot of spell cast sequences
and class in combat order
and many fix for playbot
2. why not inv playerbot>5  for raid
3. tank heal assist need more fix
4. TANK can't effectively create aggro
5. Hope to add AOEAI 
6. Why don't you combine the BOT advantages of blueboy and IKE3?Is it because MANGOSZERO has done the integration of ike3? Why not integrate them to make classic great?

**Comment by vurtnezheng** [comment]
yyhhrr playerbot fix github/yyhhrr/portalclassic/tree/develop

**Comment by yushicsm** [comment]
yyhhrr/portalclassic have much bugs
It will be crash some times when change to allow bots to be added from a different account
And it's difficult to fix

**Comment by cala** [comment]
Greetings,

Thanks for your message, I will answer it there but I will also close the issue because you are doing a feature request that should be discussed in our forum. Our issue tracker is for tracking/assigning issues and the commits that fixed them.

1. yyhhrr made many interesting changes to its playerbot branch. Some of them are already in the current code. However, many of his changes are not compliant with the code policy of CMaNGOS and are not pullable as they are. I already rewrote a few of his interesting changes, mentioning them were based on his work. Some others ideas of yyhhrr are still interesting, like the AoE stuff, but it is incomplete and need to be rethought with a more generic approach
2. Sorry, I did not understand
3. You need to be more specific
4. You will have to provide examples, because as long as other bots use combat delay, I never had real issues about warriors holding aggro
5. See 1.
6. unfortunately, bots code is not some kind of LEGO. The various bots AI rely on a bot function API to work and this API relies itself on the core to use functions and classes provided by the core. This means that we cannot merely merge/pull/pick Ike bots code from mangoszero and put it into playerbot. We can port interesting features from Ike, but that means a new development
