### ISSUE TITLE
freebsd 11 build broken

### ISSUE THREAD

**Issue by metacreo** [cmangos/issues#1451]
freebsd 11 build broken
https://pastebin.com/7vAt3b7v

wotlk master

**Comment by natiewow** [comment]
Try building with -DPCH=0
It works for me. PCH build has been broken on FreeBSD for as long as I remember.

AFAIK all it does is speed up the build process a bit, so we're not missing much.

**Comment by Lillecarl** [comment]
If it helps, installing ccache will help speed builds up quite nicely too.

**Comment by metacreo** [comment]
Thanks all for help.
Tried build with -DPCH=0 and got extractors build error
https://pastebin.com/r6QJb3yd
/home/mangos/src/contrib/vmap_extractor/vmapextract/vmapexport.cpp:295:23: error: use of undeclared identifier
      'fopen64'; did you mean 'fopen'?

without BUILD_EXTRACTORS and PCH compilation passed 
but I need extractors too.

**Comment by Lillecarl** [comment]
@metacreo 

https://github.com/cmangos/mangos-tbc/commit/c224595b1210231f1042a7d9e27b953f32ca5cca#diff-793c6de45002ab21332b9cca08769ff5

+  add_definitions("-Dfopen64=fopen")
 +  add_definitions("-Dfseeko64=fseeko")
 +  add_definitions("-Dfseek64=fseek")
 +  add_definitions("-Dftell64=ftell")
 +  add_definitions("-Dftello64=ftello")

Those should be applied to FreeBSD aswell, so if you solve that it should work.

**Comment by metacreo** [comment]
@Lillecarl 
added this in UNIX section and build success.
Thanks All.
Solved.

**Comment by Lillecarl** [comment]
@metacreo You could pullrequest this, it's valid for freebsd and apple :)

**Comment by evil-at-wow** [comment]
Well, whatever you call valid...  

That commit you reference should be fixed because it is just setting up macros that the preprocessor handles, and it makes the compiler see your code as if you had written fopen instead of fopen64 in your source code. Close, but don't do that via your own macros please!

It probably won't make a different for a 64-bit build, because 64-bit builds should be able to manipulate large files by default. But it won't work for 32-bit builds as you expect. The offset types for say fseeko will be 32-bit types in a 32-bit build, so you're still not going to be able to work properly with files larger than 2 GB by just "renaming" the call, which was most likely the entire point of using fseeko64 in the first place.

What I believe should be done instead is using the non-64 functions in the code, always. So just write 'fopen' in this case in vmapexport.cpp. And then make sure that large file support is enabled for 32-bit builds so they can work with files larger than 2 GB as well. For glibc on Linux this means using `-D_FILE_OFFSET_BITS=64` (which basically *replaces* the file system interface with the 64-bit interface). Stay away from `-D_LARGEFILE64_SOURCE` and the like that *add* an additional set of xxx64() functions to the file system, if possible. If you need fseeko and ftello added to the file system interface for some reason, define `_LARGEFILE_SOURCE` as well.

As far as I know, FreeBSD and Darwin (Mac) work the same way, or at least very similar (you can check their documentation on large file support to be sure).
