### ISSUE TITLE
[ALL] Question of implement Multilanguage

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1468]
Hi, i know it is not an issue, but is it possiple to impement
multilanguagefromthis repositoy?
https://github.com/MangosExtras
there many languges for all versions
i think it is great for many people 

i tested german language i only changed 2 database names than can use it 1 :1 
and worked fine

**Comment by killerwife** [comment]
It doesn't need to be implemented. This is all just about supporting it. We on vengeance maintain it ourselves, because there has not been any interest in this on an official cmangos front afaik. It's a lot of work, and doesn't contribute to emulation per-se. We do it as a common courtesy to players. @cyberium what is your stance on this?

**Comment by Warlockbugs** [comment]
Obligatory boring legal nagging from me. :smile: The more in-game texts are somehow hosted under "CMaNGOS" organization, the bigger target crosshair it paints on the project. From a better legal safety standpoint, my proposal would be removing all in-game texts and titles from dbs and creating a separate organization with just "l10n" repos, containing all db texts for the databases, starting with english to any number of languages - it's all about initiative to maintain it.

**Comment by cyberium** [comment]
While iam 100% ok with @Warlockbugs i will support ```MOTIVATED enough``` people that want to do it and support the project over years ;)

Ah and closing this because hopefully its not an issue.
