### ISSUE TITLE
[CLASSIC] Dual Wielding Mobs

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1478]
There is a bunch of mobs which should know dual wield. There is a bunch of mobs with dual wield set in ACID. However currently, dual wield is limited to players only. It needs to be extended to mobs as well.

ref; https://github.com/cmangos/classic-db/pull/131

**Comment by AnonXS** [comment]
It seems dual wielding is now automatically added by [`creature_equip_template`.`entry`](https://github.com/cmangos/issues/wiki/Creature_equip_template#entry).

---

See Naga casters in tbc-db as example, they have wrongly set equipentry2 != 0, therefore they all dualwield with a staff equipped in main hand due to equipentry1 != 0.

**Comment by Phatcat** [comment]
Not sufficient, read the discussion i referenced, more specifically, read here; https://github.com/cmangos/classic-db/pull/131#issuecomment-335086342

**Comment by AnonXS** [comment]
trinitycores supports dual wield auras for npcs too, so we might do it two ways, either via equipment_template for humanoid like npcs and with aura for others which should still dualwield like brutallus.

**Comment by Phatcat** [comment]
So instead of actually getting it to properly work we should have not 1, but 2 custom work-around systems...? amazing. I suggest a third way. Finding out how dual wield is really supposed to be handled by the core instead of trying to hack around it.

**Comment by AnonXS** [comment]
Progress was made, CREATURE_EXTRA_FLAG_DUAL_WIELD_FORCED  will be added soonish.
