### ISSUE TITLE
[CLASSIC] The Problem of Biological Attack Quest Issues

### ISSUE THREAD

**Issue by bluehelp1989** [cmangos/issues#1521]
**Current behavior**: 
When I walk into the attack creature, the creature will run behind me, causing me to adjust my angle of view to attack the creature.
If the hunter's baby attacks the creature, the baby and the creature like the game, adjust their position to each other back and forth.
Request repair!

**Expected behavior**: 

**Steps to reproduce**:
See video and pictures

**Client version**: 
1.21

**Commit hash**: 
Newest

**Database version**: 
Newest

**Operating system**: 
windows 10 X64

video:
https://youtu.be/NFgQLc2ubgM
https://youtu.be/Rmmk2kY29tA

**Comment by Trystanosaurus** [comment]
I've also noticed my hunter pet runs back and forth while it has aggro.

I think the problem is in \AI\BaseAI\PetAI.cpp 

In that it sets the pet's attack angle to behind the creature (line 46 in the WotLK version of the file), however they should only try and attack from behind if they don't have aggro. If they do have aggro they should stay where they are.

**Comment by Trystanosaurus** [comment]
Just a quick update to this but it does seem to be that line that's making the hunter pets keep running back and forth when tanking.

Changing line 46 in PetAI.cpp from

`m_attackAngle = M_PI_F;`
to
`m_attackAngle = 0.0f;`

Makes the pets stop running around, however of course they then only attack from the front. Ideally they should attack from the front when they have aggro and from the back when they don't but my knowledge of c++ and this project isn't quite up to that.

**Comment by Phatcat** [comment]
This should be solvable by making a condition in the respective AIs checking if the target of it's victim is itself, if it is, then attack from the front, if not, attack from behind.

**Comment by cala** [comment]
> the baby and the creature like the game

I'm glad they enjoy it.

> adjust their position to each other back and forth

That sounds soooo Valentine's Day.

On a more serious note. I never looked at the pet system so it is kind of a black box to me, though the approach suggested by @Phatcat sounds reasonable (especially as I did something similar for the rogue AI of Playerbot). Any idea where we should look at in Pet AI code?

**Comment by Trystanosaurus** [comment]
The Pet AI code is all in \AI\BaseAI\PetAI.cpp

At the moment the attack angle is set on line 46.

I couldn't say for sure but my guess is that's an initialisation function though and the attack angle would need to be moved for it to update in real time as the pet gained and lost aggro.

**Comment by killerwife** [comment]
@Trystanosaurus what should happen is: On combat enter set attack angle behind. On first approach to an enemy in combat change attack angle to whatever is available. On switching to another enemy, change attack angle again to behind, and again turn it off on arriving near him. This requires ChaseMovementGenerator communication with PetAI.

The problems are as follows:
PetAI is now too much used for too many things. This behaviour only exists for player pets, which should be the only thing PetAI handles.
Arriving at target is not a hook yet. When previous issue is fixed, its a matter of adding that communication between the AI and the movement generator which is quite easy.

The solution is to wait for @devmaximus to finish CharmAI which removes Charmed players from PetAI. Then force Guardians to use GuardianAI. And after that implement this in PetAI. Don't get me wrong, its not rocket science, we just have to wait so that its not a mess. I will add the m_attackAngle = 0.0f; for now soon-ish so that pets at least work as intended and put a note to do what I described above.

**Comment by Phatcat** [comment]
> This behaviour only exists for player pets, which should be the only thing PetAI handles.

That's not quite true, though, look at how the mob behaves in the video he linked in OP as well as what he reported;
> When I walk into the attack creature, the creature will run behind me, causing me to adjust my angle of view to attack the creature.
> https://www.youtube.com/watch?v=Rmmk2kY29tA&feature=youtu.be

Difference being though that it doesn't try to readjust itself to attack from behind as the pet, but the initial angle is still odd.

which is certainly not like it should behave.

**Comment by killerwife** [comment]
This should be resolved as petai is its own thing and we solved many bugs with it over time.
