### ISSUE TITLE
Connect to game server loop

### ISSUE THREAD

**Issue by Albanosdes** [cmangos/issues#1527]
Hello there.
As a IT guy i'm not usually asking for help but I'm kind of stuck.

I installed Mangos Vanilla server and everything is starting fine, but I am stuck at the server lists and "Connect to game server" loop.

My computer is in the 192.168.0.0/24 network and the machine running the server is 192.168.100.20.
This is not a firewall/routing issue, everything is allowed.

My wish is to be able to connect to the server through my public adress (I have a domain-name for it).

The connection loop occurs when using 192.168.100.20 in realmlist or the the domain-name.

There is some screens captures of my conf (on Debian 8.9) :
realmd.conf :
![realmd conf](https://user-images.githubusercontent.com/12948248/34536989-42158522-f0c7-11e7-9b08-4eba02b6a963.PNG)

mangosd.conf :
![mangosd conf](https://user-images.githubusercontent.com/12948248/34536994-428dfd90-f0c7-11e7-93fa-3218a29d4175.PNG)

/etc/host conf :
![hosts](https://user-images.githubusercontent.com/12948248/34536993-426b8544-f0c7-11e7-9d31-d28c9646aa9a.PNG)

I have also did this :
DELETE FROM realmlist WHERE id=1;
INSERT INTO realmlist (id, name, address, port, icon, realmflags, timezone, allowedSecurityLevel)
VALUES ('1', 'MaNGOS', '192.168.100.20', '8085', '1', '0', '1', '0');

I went through a lot of forums and things alike. But I can't get anything valuable except the thing that the problem should had been resolved when using "192.168.100.20" insteed of "127.0.0.1" in the conf files. But not working...

Thanks for reading.

**Comment by evil-at-wow** [comment]
I'll try to give some background info here so you can understand the purpose of things. That might help you fix the issue, because I don't immediately see where the problem is here.

The -DatabaseInfo lines in the realmd/mangosd.conf files are only important to be able to reach the database server (MySQL typically) from the machine where the corresponding game binary is running. Pretty much anything that allows you to reach the database server is fine: an IP address as you wrote, but if the database is running on the same machine as it looks to be the case, you could as well use "localhost" literally instead of the "192.168.100.20" that is there now. Changing it won't make a difference for you, but I often use 'localhost' so I can easily move/copy config files to another server without having to edit much.

The other important things to know are that the game client first connects for authentication with the realmd binary, but it sounds like that is already working. Either way, for future reference: make sure that your WoW client connects to the correct realm daemon by ensuring the WTF/Config.wtf file in your WoW directory (at least that's the file for The Burning Crusade, but I think it's similar for Classic) contains a realmList setting that can be reached. For example it should contain something like this:
```SET realmList "wow.imperium-gaming.fr"```. If you use a hostname here instead of an IP address, make sure it resolves to the IP of the server that runs the realmd daemon on the machine running the WoW client.

Once the realmd deamon thinks you successfully logged in, it will send your WoW client a list of realms that you can connect to. That's where the realmlist table in the database comes in. It's important to understand that it sends your game client exactly what's in the database here. In your example, that's going to be 'connect to 192.168.100.20, port 8085'. This would never work for anyone outside of your LAN (they would need a public IP), but I'm sure you know that already. If you want to connect to the world server through a public hostname, put that in the database. In your case, that's changing the INSERT query to use 'wow.imperium-gaming.fr' instead of the IP address. Of course that hostname will be resolved to an IP address, by the WoW client, so just make sure it resolves to the IP of the server that's running the mangosd daemon on the machine running the WoW client. Note that this IP will typically be different for machines on your LAN and on the internet: machines on your LAN might resolve the hostname to 192.168.100.20 with an entry in /etc/hosts or some DNS on your LAN, machines on the internet (say friends or family) should resolve it to the IP you get from your ISP through DNS.

I have a somewhat similar setup, where I connect with a hostname to play. I'm using the hostname in the realmlist table as explained above. The main differences between our setups apart from that are that I only have one entry in /etc/hosts (not the one with 127.0.0.1), and I have set "BindIP" in the config files to "0.0.0.0" (basically bind to all interfaces). I can't imagine that makes a difference, but I don't see anything else being wrong at the moment...

One last debugging tip: you can double check that you can connect properly to both the realmd and mangosd daemons from the machine running the WoW client in advance, for example with a simple telnet command such as ```telnet wow.imperium-gaming.fr 3724``` for the realmd daemon and ```telnet wow.imperium-gaming.fr 8085``` for the mangosd daemon. Of course this won't really do anything, but all we want is check for a successful TCP/IP connection. It can help detect typos, hostnames that resolve to the wrong IP for some reason, etc. If any of those connections fail, something is still wrong and there is no point trying with the WoW client yet.

**Comment by Ve1vet** [comment]
@evil-at-wow there is a bug i core...
How to reproduce. For example: 
1. You have 2 compurets under your router/switch.
2. You have dedicated IP, for example 139.130.4.5
3. On machine with local IP 192.168.0.1 you start server. If you set realmlist as 192.168.0.1 in DB, you can connect from local computer( 192.168.0.2 ).
But, if you set in DB your dedicated IP( 139.130.4.5 ), you open your server to the world, but people from local network can't connect to the server( configuration of the router is correct, same as realmlist ). They still can find server trough 192.168.0.1( as local computer ), but won't be able to connect to realmlist, because it have IP 139.130.4.5.

**Comment by Albanosdes** [comment]
@evil-at-wow Thanks for your answer. As for the sql connections, I should had listened to myself, bcz I knew the localhost was fine, but after seeing so much forums where they would have edited theses lines, I wasnt sure anymore.

What was missing from me was the "wow.imperium-gaming.fr" as the adress in the realmd database. I will try this tonight and try it out, and thanks for the telnet tip, may be useful later.

@Ve1vet I have serious doubt about this being a bug, as I said above, I may just be a config issue. The way you describe the problem on your third point is logical, you will not be able to connect to your own public IP, that's why using DNS as @evil-at-wow said makes sense.

Anyway, trying it out tonight and will come back with news.

**Comment by Albanosdes** [comment]
The issue is resolved, thanks to @evil-at-wow  everything is working great !

**Comment by cala** [comment]
I'm glad to read this. Feel free to post any other issue that you might find. Enjoy cmangos ! =)

**Comment by evil-at-wow** [comment]
I'm glad to read that things are working for you now!

@Ve1vet I agree with Albanosdes that this is not a bug in the core. It's annoying, sure, but it's not something specific for CMaNGOS cores. There are plenty of other services that show the same behavior (like web servers, for example). If you want to connect to your own public IP from the LAN, you need to redirect the traffic that's routed to your public IP (your public IP is not in your LAN, so that traffic gets routed to "the internet", and basically ends at your firewall/router). The typical way to redirect that traffic is done with either NAT reflection on your firewall/router or split DNS. Split DNS is what I explained earlier - a hostname resolves to a different IP for LAN machines and WAN machines. NAT reflection is... more troublesome I think. It works fine, except when it doesn't work at all :wink: So I prefer the split DNS way myself, it has never failed me.
