### ISSUE TITLE
[Classic] ERROR CreatureEventAI: nullptr target for ACTION_T_CAST creature entry 8541 casting spell id 5884

### ISSUE THREAD

**Issue by Garog** [cmangos/issues#1537]
**Current behavior**: 
found this in the server log after a while of playing

`ERROR CreatureEventAI: nullptr target for ACTION_T_CAST creature entry 8541 casting spell id 5884
`
Client version:
1.12.1 (5875)

Commit hash:
CMaNGOS Classic/0.18 (2018-01-14 12:31:11 - 9ce621b3392da2d9a78e25d1fb2c0e7fcab5aef0) for Linux_x64 (little-endian) [world-daemon]

Database version:
characters :
required_z2708_01_characters_account_instances_entered

mangos :
required_z2717_01_mangos_spam_records_length
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

realmd:
required_z2716_01_realmd_totp

Operating system:
Debian 9.3

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
I'm unable to reproduce this issue while fighting the NPC and the related script looks correct. It may be possible that this happened while the target was unexpectedly removed from world for some reason.
Could you try reproduce this error ?

**Comment by Grz3s** [comment]
@cala this is well known issue...it happens when spell with casting time (here : CastingTime (Id 5) = 2,00) is interupted by fact ..that its target disappeared during casting process... 
It occurs when "target" is unloaded from grid ... (usualy because is to far from active object)... Rare but happens:)

I dont really know ...why we do have this at all .. (im sure spell should be just cancelled without any error log).. Maybe @killerwife or whoever knows this subject will help here...

It can be fixed... by using 9 = EVENT_T_RANGE: ... so for this case, you will use range 0-30.
example here:
https://github.com/cmangos/wotlk-db/commit/d2e65de36129db4ec4140550df3ec35e2277f9d2

**Comment by killerwife** [comment]
using EVENT_T_RANGE is a hack which hides the real problem. The real fix is to make something more complex. getVictim== nullptr is actually legitimate behaviour in some cases. So having no targets, it should just quietly fail in my opinion. Thats how all of SD2 code works for example.

**Comment by Grz3s** [comment]
sure ... but whats the point to throw that error... in console .. we do not need to know that spell was cancelled... (simply kick it to debug mode)

**Comment by killerwife** [comment]
The error is valid in other target selection instances (other actions). But yes, propably this one should be elevated to debug OR disabled completely.

**Comment by cala** [comment]
As I understand it, this is not a real issue and can be closed or do you prefer to rename it while the error is elevated to debug?

**Comment by killerwife** [comment]
Ill commit it on voa and when i do next export batch I will export it to all branches of cmangos.
