### ISSUE TITLE
[Classic] [Lunar Festival] missing Elder Ironband

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#1558]
Elder Ironband is missing
NPC ID = 15567

He should be near Blackchar Cave in the Searing Gorge

source :  
https://wotlk-twinhead.twinstar.cz/?npc=15567#starts

![5190](https://user-images.githubusercontent.com/2279126/35771341-7a1bd828-092b-11e8-9425-ecacf5794613.jpg)

**Comment by RichardGe** [comment]
@cala ,

Here are other issues,

1)  npc=15595 at Teldrassil  has a bad name, he should be named "Elder Bladeleaf" instead of "Elder Moonstrike"
( In current database, we have 2 "Elder Moonstrike" :    npc 15595 and 15594  )
2) Elder Obsidian is missing , he should be in Silverpine Forest
3) Elder Farwhisper is missing, he should be in Stratholme

my reference is the wotlk-twinhead.twinstar.cz database.

**Comment by cala** [comment]
@RichardGe 
Thank you very much for you report and providing references. I'll look at this. :+1: 

On a side note, we highly prefer known sources like wowpedia, wowhead or allakhazam archives rather than DB from private servers. Those can be a good indicator of what is wrong or missing, but might prove unreliable.
For example, I had at least once a report on a missing NPC based on a private server DB that proved to be an old fork of Classic DB. The "missing NPC" was removed by myself because it was added after patch 1.12, thus the issue was on the private server DB that was not up-to-date, not the other way round.

**Comment by RichardGe** [comment]
I see,  here we can also base our reference on the gossip menu from other Elders, all the : 
'Where is Elder Bladeleaf?'  ,  'Where is Elder Obsidian?'  .....etc...
they do exist in the current database, and the are describing the same location that in wotlk-twinhead.twinstar.cz
