### ISSUE TITLE
Warlock Keeps Felguard When Switching Talent Specialization to Non-Demonology

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#159]
When a Demo-Lock switches to an alternate Specialization while having a Felguard up, they get to keep the Felguard even though they should no longer have access to one.

This probably affects BM Hunter exotic pets as well, but I haven't tested it with those.

On Talent-Spec change, all active pets should be dismissed (for Warlocks: dismiss pet, return the soul shard, for Hunters: apply dismiss pet mechanic from Spell #2641)

**Comment by Phatcat** [comment]
This has been partly resolved. Warlocks as well as Hunters when resetting talents will have their pets dismissed, and for the warlock's case, since he now doesn't have the spell anymore, he won't be able to re-summon felguard without retaking the talent, which seems good, as for the hunter though, things get a bit more complicated and I'm raising a seperate issue for that so this can be closed.
