### ISSUE TITLE
[Classic] Blackfathom Deeps: Aqua Guardians

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1607]
**Twilight Reaver**s in Blackfathom Deeps are summoning a million **Aqua Guardian**s. My client FPS dropped below one after getting to the area.

![aqua_guardians](https://user-images.githubusercontent.com/18726138/39967112-59652502-56b6-11e8-9699-26f8ed47c09e.jpg)

**Comment by Grz3s** [comment]
Theyre summoned by "Twilight Aquamancer" that stain next to your npc....
![summon](https://user-images.githubusercontent.com/2374069/39967576-6f496e9a-56ad-11e8-9192-5b24e994295c.jpg)

This is a common issue for all summons...
And TBC and WoTLK... fixed that already. (both using a diff method)
TBCDB - using summon on spawn.. (summon if killed wont be respawned after creatures evade)
WoTLKDB -

**Comment by cala** [comment]
Thanks @Grz3s , I'll backport your fixes soon.

**Comment by AnonXS** [comment]
The way @Grz3s fixes the Issue might resolve the issue better in the short run, but it is not blizzlike because thats not how tempspawns are respawned by npc ai usually (there might be exclusions for bossscripts with adds summoned by spells etc). https://www.youtube.com/watch?v=r_o2eCTAeSA

The correct way for tempspawns to be respawned would be by respawning when their corpsedecay timer is terminated, aka respawn just like a normal spawn would, but without taking creature.spawntimesecsmin/max into account.

**Comment by Grz3s** [comment]
if core will suppoert this ..then it will be easy to catch them all again and fix...

BTW:
this isnt normal that master  evades if guardian is killed... (looks strange) .. oh well... :)

**Comment by AnonXS** [comment]
The Hunter forced the behavior with Feign Death to showcase the guardian behavior.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/ac9fa346f68fc7de9e203237efdf4709bd71b75e
