### ISSUE TITLE
[TBC] Duplicate Items in Auctions

### ISSUE THREAD

**Issue by ungluck** [cmangos/issues#1638]
**Current behavior**: 
Player can copy stack of cloth, leather, ore, vortex and the same items.
**Expected behavior**: 
Player should not be able to copy something
**Steps to reproduce**:

1. Create almost empty main bag with stackable item on all slots.
![image](https://user-images.githubusercontent.com/40755598/42151428-a9708626-7de5-11e8-9e80-798042ad3a97.png)
2. Divide items to slots for don't have empty ones
![image](https://user-images.githubusercontent.com/40755598/42151632-44243d48-7de6-11e8-91ec-72a66e804fb6.png)
3. Destroy one of them to have empty slot
![image](https://user-images.githubusercontent.com/40755598/42151667-64743436-7de6-11e8-88c3-59fe0e78222e.png)
4. Divide item that you want to clon into two stacks - 1 and 19.
![image](https://user-images.githubusercontent.com/40755598/42151760-a53b74fc-7de6-11e8-80b1-3ac684a914d0.png)
5. After move emptry bag to empty slot, then again to first slot. And then - try to move it to your main bag. Empty bag will disappear.
![image](https://user-images.githubusercontent.com/40755598/42151902-28809068-7de7-11e8-861a-7ea94bc04d3a.png)
6. After - put stack 19 to auction. And do re-log.
![image](https://user-images.githubusercontent.com/40755598/42151947-5002db6e-7de7-11e8-97d5-621e02d6a867.png)
7. After logging you will appear with full stack (20) in your main bag and empty bag will in your character again.
![image](https://user-images.githubusercontent.com/40755598/42152018-93b5cace-7de7-11e8-95dc-2f32674ddbb8.png)
8. Cancel your auction and have profit - 19+20 stack.
![image](https://user-images.githubusercontent.com/40755598/42152065-b974f2bc-7de7-11e8-932f-e02cfa24cba6.png)

**Client version**: 
2.4.3
**Commit hash**: 
commit 78a22c869eb6931c5c604440a85917cb4d68416f
**Database version**: 
latest
**Operating system**: 
Tested on win10-64, win7-32, win7-64.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by ungluck** [comment]
Anyway, my verification team said me, that this bug can be used simpler, without bag manipulation:
1. Divide stack into two stacks - 19+1.
2. Do logout.
3. Go to game and see that you have 19+20 items.

Can it be connected with any "save" time? May be information about stack of vortex is begin saved not so often as information about bag "save" time?

**Comment by Ve1vet** [comment]
@Warlockbugs, not the same.
#1732 related to DataBase exceeding the maximum value. Magos core can't work with it. I have such problem when one of those who have DB access decided to create a new character & than change character id for number, that was much higher than max id value. Guess what happen next :) All new created characters start delete most old characters beginning from 1, but only in character table, so new characters get all skills/items/gold etc from old deleted characters :) Mangos tables are not connected at all & core not handle such cases. Noone even thought about such things.

In this case... I think he has patches from Trinity core, because what he describe - old Trinity bug, that never worked on Mangos. I'm almost shure he not use clean cmangos core.
Or... his players use cheats, for example WPE.

**Comment by berserkingyadis** [comment]
Can somebody rephrase this replication method in simple terms? Im trying to replicate it but the "empty bag" does not disappear.

**Comment by datchannin** [comment]
I've created one more report for this issue. It was fixed here:
https://github.com/cmangos/issues/issues/1732

For report in this case - the main step is number '6', steps before '6' can be skipped. You can see in this step price '55555' gold. So this issue is the same as my.

**Comment by killerwife** [comment]
Other issue was closed as fixed.
