### ISSUE TITLE
[Classic] Invisible rain

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1656]
I noticed it a long time ago that during rainy weather there are often long (>5min) periods when you can clearly hear the raining sound but there are no rain particles at all. This happens really often in Elwynn Forest, but I've seen it in other zones as well.

I took a glance at the Weather class. I believe the weather type is properly sent (**m_type**) because the fog and color changes related to raining are present during the 'invisible rain'. So my guess is that something is up with the **m_grade**, maybe wrong values are sent or there are some wrong assumptions how does the client display certain grades.

**Comment by bdebaere** [comment]
There look to be some wrong assumptions on how the client displays certain grades indeed. In Elwynn Forest anything equal to or below m_grade 0.25f appears to just be very cloudy and that's it. No rain particles are being generated. I have noticed this in other zones as well but it's very clear in Elwynn Forest.

The other weather sound effects are not an issue since they only produce the sound of a light wind and therefore do not create the expectation of any particles to accompany it.
