### ISSUE TITLE
[TBC] Errors in Server Log From Stair of Destiny NPCs

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1671]
**Current behavior**: 
Currently there is quite a bit of server spam from Stormwind Mage (template 18949), Melgromm Highmountain (18969), Undercity Mage (18971) and Ironforge Paladin (18986) trying to cast Fireball (33417), Arcane Missiles (33419), ArcaneExplosion (33632), Blizzard (33624) and Chain Lightning (18969).

All of these NPCs are fighting the legion at the stair of destiny in hellfire peninsula. They spawn from portals and join in the fight. In game the event looks fine, though the mages sometimes start casting when they are at very long ranges from the demons (around 100 yards).

```
nullptr target for ACTION_T_CAST creature entry 18949 casting spell id 33417
nullptr target for ACTION_T_CAST creature entry 18949 casting spell id 33624

nullptr target for ACTION_T_CAST creature entry 18969 casting spell id 33643

nullptr target for ACTION_T_CAST creature entry 18971 casting spell id 33417
nullptr target for ACTION_T_CAST creature entry 18971 casting spell id 33419
nullptr target for ACTION_T_CAST creature entry 18971 casting spell id 33624

nullptr target for ACTION_T_CAST creature entry 18986 casting spell id 33632
```
**Expected behavior**: 
I guess these errors shouldn't be there, though they're not doing anything game breaking they're just filling the console a bit.

**Steps to reproduce**:

1. Start the server
2. Watch the server console
3. 

Client version: 2.4.3

Commit hash: 3c627a4

Database version: 48c70bc

Operating system: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
old "milion Times" reported issue ...
Happens when creature X start casting spell on creature Y and for any kind of reason Y disappears during that process... (most of the time its unloaded by grid load/unload)...  Creature X stops casting and error log is displayed.
I asked many Times ..why we have to see this "spam". Why creature cant just stop casting and continue his life ;)

Can be avoided by using event = 9 EVENT_T_RANGE .. instead of  - 0 EVENT_T_TIMER_IN_COMBAT

**Comment by killerwife** [comment]
These are now mostly resolved.
