### ISSUE TITLE
Playerbots Not Listing Items Outside Main Bag When Interacting With Merchant

### ISSUE THREAD

**Issue by zjx2172** [cmangos/issues#1776]
**Current behavior**: 
When interacting with a merchant, playerbots whisper items they could sell. The list of items only includes items in their main bag.
**Expected behavior**: 
Playerbots should list items in all bag slots.
**Steps to reproduce**:

1.  Instruct playerbot to loot enough items to fill their main bag +1
2. Interact with merchant/vendor
3. Note that the playerbot's whispered sell list
4. Open trade with the playerbot. The bot will list items by bag. Note that items on the other bags are not listed in the sell list.

**Client version**: 
1.12.1 (5875)
**Commit hash**: 
3cbdeacb4c3eb7b4ea0b299c32328def30d27f91
**Database version**: 
ac3d9259837cfee00e6744089d67d6565cb1ccf7
**Operating system**: 
Debian 9

**Notes**
Quick fix: Remove redeclaration of "std::ostringstream goods" on line 6095 of PlayerbotAI.cpp (relative to commit 575e7e8e9e778b0a857a7541d08b6245b7f09d56)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
For the sake of replicating this, it looks like you need to have the option `PlayerbotAI.SellGarbage` set to 1 so that the bot attempts to sell his junk. If this is not enabled the bot does not attempt to sell any  garvage items thus no whisper with a listing of his items. That said, I can confirm this as reproducible in cmangos/cmangos-classic@58f9345

When talking to a vendor he lists only the items in his Main Bag:

![2018-11-24 21_25_53-world of warcraft](https://user-images.githubusercontent.com/405585/48975143-30a4c000-f030-11e8-9738-8f269adb3fe2.png)

When initiating a trade with the bot, he lists his bags and all items:

![2018-11-24 21_27_35-world of warcraft](https://user-images.githubusercontent.com/405585/48975147-474b1700-f030-11e8-8c1a-af0de84567d3.png)

**Comment by cala** [comment]
Fixed in 
https://github.com/cmangos/mangos-classic/commit/d6f4a44c333deca6810db7e4bb27f1c29d8d9b53
