### ISSUE TITLE
Typo - Winter's Presents Quest

### ISSUE THREAD

**Issue by Lankytim** [cmangos/issues#1813]
**Current behavior**: 
Wonderform Operator (NPC entry 15732, spawned by event 2 (Feast of Winter Veil - Main Event)) has a quest offer gossip for "Winter's Presents" that reads:

> "I hear Greatfather Winter - with the generous support of Smokeywood Pastures"...

**Expected behavior**: 
"Smokeywood" is spelled "Smokywood" elsewhere throughout the game (I understand Smokywood is the correct way).

**Steps to reproduce**:

1. go to NPC 15732 during the Feast of Winter Veil event
2. read the text for the quest he offers - "Winter's Presents"

**Client version**: 
2.4.3

**Commit hash**: 

**Database version**: 
tbc-db 470e84adfc8646b6c59a0476f4636237874ed112

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by bdebaere** [comment]
It does indeed look like the official name is Smokywood according to http://wowwiki.wikia.com/wiki/Smokywood_Pastures. I have an open pull request to fix the ones where a source proves they should be spelled otherwise. It appears there are more misspellings of this name in the database, however, they do match with the source. The OfferRewardText of quests 8769, 8827 and 8828 all mention Smokeywood. But these texts match with https://www.wowhead.com/quest=8769/a-ticking-present, https://www.wowhead.com/quest=8827/winters-presents, https://www.wowhead.com/quest=8828/winters-presents. The question then becomes, do we fix these too or leave it blizzlike...

**Comment by cala** [comment]
> The question then becomes, do we fix these too or leave it blizzlike...

A tough question that we have on a regular basis with no clear rule yet. Basically: if it is an obvious bug or typo like here, we fix it unless the bug/typo was so wildly known that it is expected to be that way. 

We tend to keep everything else blizzlike even if we have doubts.

**Comment by cala** [comment]
Closed in Classic DB by 
https://github.com/cmangos/classic-db/commit/5b15177ed71c754564e5ef4f6c0bad86bc626d20

**Comment by AnonXS** [comment]
My gut feeling tells me that the first repo to resolve an issue should always close the related issue, if found. else it is very likely to stay open as there is no backlink in the commit that fixed it.

**Comment by cala** [comment]
> My gut feeling tells me that the first repo to resolve an issue should always close the related issue, if found.

We can agree on that! :smiley:
