### ISSUE TITLE
Load map error

### ISSUE THREAD

**Issue by Rapth** [cmangos/issues#1819]
**Current behavior**: 
load map error 
**Expected behavior**: 
with no errors
**Steps to reproduce**:

1. extract maps with latest map extractors
2. create a 70lv character and teleport it to any instance of Outland
3. Server shows ERROR:Error load map file :XXX

**Client version**: 
BUILD 8606
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
WIN10 64bit
[Server.log](https://github.com/cmangos/issues/files/2718105/Server.log)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
nothing serious .. DB isssue....
- 2018-12-31 17:10:28 ERROR:Error load map file: ./maps/5473132.map
- 2018-12-31 17:10:32 ERROR:Error load map file: ./maps/5473232.map

**2 creatures are spawned somewhere outside visible map ... "Coilfang: The Slave Pens"**

- 2018-12-31 17:11:13 ERROR:Error load map file: ./maps/5403232.map
- 2018-12-31 17:11:13 ERROR:Error load map file: ./maps/5403231.map
- 2018-12-31 17:11:13 ERROR:Error load map file: ./maps/5403132.map
- 2018-12-31 17:11:13 ERROR:Error load map file: ./maps/5403131.map

**4 creatures are spawned somewhere outside visible map ... "Hellfire Citadel: The Shattered Halls"**

Its not easy to track them ..but im sure it will be fixed soon*

**Comment by evil-at-wow** [comment]
That's an interesting remark, @Grz3s, about wrong spawns in the databases. It's perhaps even the reason why the error is logged by the core. But I think that's not what's actually going on here!

I recently looked into this after I found similar errors in my TBC logs for the Dire Maul map:
```
2018-12-21 20:31:23 ERROR:Error load map file: <path to installation>/data/maps/4293232.map
2018-12-21 20:32:00 ERROR:Error load map file: <path to installation>/data/maps/4293132.map
2018-12-21 20:33:25 ERROR:Error load map file: <path to installation>/data/maps/4293133.map
2018-12-21 20:33:31 ERROR:Error load map file: <path to installation>/data/maps/4293233.map
```

I noticed a pattern though, which also holds in my TBC server map files for the errors you mention: not only do the map files mentioned in errors not exist, there are no map files at all for that map! None. No map files for maps 547, 540, or 429 exist in my data/maps folder. And I think that's normal, because these instances have several levels/floors, so the geometry is more than just a simple height map. These instances seem to have a WMO.

So I think the errors here are at least misleading, and IMHO just wrong. The core should probably not even try to load any map files for these instances, but this might be difficult to know in advance. I can see the value of these errors to detect wrong spawns, but in these cases the spawns are most likely correct and there is not really problem, which makes the errors false positives at best. That's bad, but I don't know enough details of all this at the moment to suggest a better solution.

Maybe @killerwife has ideas?

**Comment by Grz3s** [comment]
Well maybe ... but then you should see spam of these errors ... for every creature
also:
I fixed simmilar errors by correcting spawns already...
https://github.com/cmangos/wotlk-db/commit/36220e9842dd126c8d131acba34842bbeac316c2 
- or it was DB dev mistake with xyz... (example ... .xxx instead of -xxx)
- or creature taken from sniff but in our core half of it stucks inside ground lvl - that in some cases ..pushes him down ... and then u can see nice anim ...him falling down under map.... (catch him is quite hard... koz u have sec or 2 to do it:) )....
...
What makes it even harder... is ..that some creatures are spawned by scripts events etc...
