### ISSUE TITLE
multiple Edge of Madness events active

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#1824]
There are multiple Edge of Madness events active ... shouldn't be most likely.

![untitled](https://user-images.githubusercontent.com/4753528/50704759-bb79d100-1058-11e9-8455-7cb8223b7266.png)

**Timestamp**:
1546627637

**Commit hash**: 
b77a96351df74cc9f5bfa97a824aa4cf226d37da

**Database version**: 
f406f10aaa675b4d78793db5204bf4f0c3651bca

**Comment by cala** [comment]
Damn, I can't assign yourself to it... :/

**Comment by Tobschinski** [comment]
my vacation is going to last for at least another 5 months, it kinda depends on Blizzard

**Comment by cala** [comment]
I don't think these events should even be treated as game_events in the first place. One from the four of them is supposed to be triggered when a specific action is made in Zul'Gurub (and I don't see related code in here).

There are 4 identical spawns of the starting GO in Zul'Gurub map and each summons a specific NPC on use. But because the spawn of each GO is dependant on the related game_event to be active, it is possible to have zero, one or up to four GOs spawned instead of only one.

I suggest either to:
- remove the game_events all together and to pool the four GOs
- handle this by SD2 and get rid of the duplicate spawns

What do you think @Tobschinski ?

**Comment by Tobschinski** [comment]
The boss you'll get is not random. https://edgeofmadnesscalendar.com/eu#calendar

**Comment by cala** [comment]
So the game_event approach is correct then. This means the schedules in the game_event tables need to be updated.

I'm sure you can do it ! 😇

**Comment by Tobschinski** [comment]
Not sure, numbers only confuse me ... letters too.

**Comment by cala** [comment]
Just throw random numbers in. With some luck, they might be the correct ones.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/1f109732e77044a1c99f26460c48a71b87d34162
Now, I want my cookies.
