### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by DennisWG** [cmangos/issues#1826]
**Description:**

Anyone with read-access to the account database (by legit means or otherwise) can log into any account they want to.

This is due to the fact that all the major emulators currently store the hash of USERNAME:PASSWORD - which is refered to as `x` in the SRP6 protocol - within their database, namely within the `sha_pass_hash` field inside the `account` table. Using this value, you can bypass the SRP6 authentication process, because it is used to calculate the shared secret (session key). Here's the critical step (as described per [rfc5054](https://tools.ietf.org/html/rfc5054)):

```
S = pow(B - k * (pow(g, x) % N), a + u * x) % N

where
B is known to both server and client
k is known to both server and client
g is known to both server and client
N is known to both server and client
a is known to the client
u is known to both server and client
x is calculated from the username & password and should only be known to the user
```
As you can see, the only value that isn't known to anyone, except the user, is `x` and this is what keeps this whole process safe.

Here's a demo video I've quickly thrown together demonstrating that I'm able to query the realm list of a cmangos based realm (this happens after the SRP6 authentication sequence) using only the account name and the value `x`.

https://www.youtube.com/watch?v=JAVDuzq3Jg0

**How to fix this:**
Luckily this is very simple:
Remove the `sha_pass_hash` field within the `account` table inside the database.
Alternatively, put more data into the hash. So not just Hash(USERNAME:PASSWORD), but Hash(USERNAME:PASSWORD:SOMEOTHERVALUE)

**Comment by evil-at-wow** [comment]
Interesting, I never realized the existence of that sha_pass_hash column (or I forgot of course). I agree with your suggestion, the alternative fix shouldn't be needed and probably only complicates things needlessly. There's no good reason why we should keep the sha_pass_hash field around, because the account table contains everything else that's needed for the server to calculate the session key, namely user name and verifier v (= g^x % N), and salt s to send to the client so the client can calculate x too.

A quick grep in my TBC source tree shows this column is used only when an account is created, renamed or its password is changed. The sha_pass_hash is then updated and s+v seem to be reset, so these values are recomputed the next time by the authentication code. This seems a bit silly as you point out, we should just update s and v instead when we change account data.

**Comment by Laizerox** [comment]
This is interesting indeed, however there are couple things I would like to mention first.

For example even if you remove sha_pass_hash and you have access to an account database its still possible to login into accounts even without knowing password. [I will leave this research here as it may contain proof of concept how it could be done.](http://opine.me/blizzards-battle-net-hack/)

Then another, I've been for more than 6 months now working on a nice wrapper (which is not ready yet) that supports similar SRP6 authentication with similar logic that client does in JavaScript and PHP backend.

And I can tell you that H(U:P:S) won't really work because client doesn't calculate identity for x like that.

What client and my JS library do is more or less something like this:
```js
SRPClient.prototype.x = function (options) {
  const {username, password} = options

  let salt = options.salt
  if (typeof options.salt === 'string') {
    salt = new Buffer(options.salt, 'hex').reverse()
  }

  const identity = createHash('sha1').update(username.toUpperCase() + ':' + password.toUpperCase()).digest()
  const sha = createHash('sha1').update(salt).update(identity).digest().reverse()

  return new BigInteger(sha.toString('hex'), 16)
}
```
So if anyone wants to discuss removal of sha_pass_hash we can do it however if we decide to remove it we should also provide some sort of support, library or guide how to create accounts which generate s and v and stores them in database and how could front-end or back-end authenticate without ever exposing identity of an x but using only server sent or stored s.

**Comment by Fabi** [comment]
Just save the password verifier and the salt for the user. that is how it should be. nothing else.

**Comment by esno** [comment]
`sha_pass_hash` is dropped now:
see:
https://github.com/cmangos/mangos-classic/pull/397
https://github.com/cmangos/mangos-tbc/pull/327
https://github.com/cmangos/mangos-wotlk/pull/285
