### ISSUE TITLE
Hyjal Summit - Lady Jaina Proudmore Does Not Respawn After Death

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1830]
**Current behavior**: 
In Hyjal Summit, when the players die leaving just Jaina and the wave of adds. Jaina is eventually killed, which should stop the wave event and cause her to respawn. 

Respawning Jaina manually resets the event but it's not occuring automatically.

**Expected behavior**: 
When the adds kill Jaina the event should end, following Jaina respawning. This lets the players retry.

**Steps to reproduce**:

1. .teleport into Hyjal Summit
2. Start wave event by talking to 5342001-4968- Lady Jaina Proudmoore
3. Die, letting the adds kill Lady Jaina Proudmoore

**Client version**:  2.4.3

**Commit hash**: c559b36d4e99345002f59987161bb87591bc30d4

**Database version**: 8de43372a43d824a3f9e5688d1f6609ab71cb775

**Operating system**:  Windows Server 2012 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment]
In this instance is the solution to just reduce the respawn time? It shouldn't effect raid progress is the sense that it shouldn't let people redo bosses. I've tested and doing .die on her and respawning doesn't let the group re-do previous progress (waves)

**Comment by Saltgurka** [comment]
There is a huge rework for Hyjal Summit which solves this and all other Hyjal issues, that has not yet been committed. Therefore, there is no point to do any changes in these old hyjal files because they will be 99% replaced by the new ones.

As a temporary solution if you're running a server, you might be able to get away with lower respawn times, but keep in mind that they will also respawn during the event in that case.

**Comment by Saltgurka** [comment]
Solved with https://github.com/cmangos/mangos-tbc/commit/c665b1e79d4f3e6542cb52bf60e0f606501db38a
