### ISSUE TITLE
Spirit Ressers in Battlegrounds don't revive players

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1837]
**Current behavior**: Spirit resser in the battlegrounds are casting the res spell [22012] but nothing happens to the dead players, they stay dead on cast completion. The animation fires off.

**Expected behavior**: Dead player with the timer countdown should res once the spirit resser finishes casting

**Steps to reproduce**:

1. Enter WSG
2. Die
3. Try to res 

Client version: 2.4.3

Commit hash: c559b36d4e99345002f59987161bb87591bc30d4

Database version: 8de43372a43d824a3f9e5688d1f6609ab71cb775

Operating system: Windows Server 2012 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment]
I can't seem to cast 22012 in a dead player - maybe it has the wrong attribute?

**Comment by yatzi888** [comment]
Going to do some testing tonight to see if I can figure it out :)

**Comment by Tobschinski** [comment]
Okay, the night is over ... we expect answers.

**Comment by yatzi888** [comment]
I've been trying to remove the value 1024 in the spell_template targets column by changing it to 0 in both the dc spell.dbc serverside and clientside. Although it probably not the solution, I just want to atleast try get the spell to act like an aoe. The changes don't seem to stick though. There's not a lot online about spell editting so I'm probably doing it incorrectly.

**Comment by Ve1vet** [comment]
This bug never dissapear... Earlier it called "glitchihg" or something like that.
For some reason it not targeting players sometimes. Not always. Helps when you go out from spirit range & then came back into ressurecting circle radius, than you will be ressurected. But this not always works also...
I think this bug can be related to ... sorry forgot where & names of this functions... anyway, it related to search FRIENDLY targets on grid, that fill the map of targets, on witch spell should be casted. This function works sucks. Oten it fills not all targets that should be in target map. There are tonns of them.
And this spell can be one of them, ass all spells, for example, that deals damage to friendly units( this reason i know, after first hit to friendly unit, it becomes unfriendly & next time such spell won't pass this check ).
I've already discuss this long time ago with Killerwife & his team. I have thouble with "fill target map", when i tried to rework SPELL_CHAIN_DAMAGE. I start use "fill all targets", because it worked correctly and than create checks to remove unneeded targets from target map. But they say, that this way is sucks :(  And reworked chain damage still uses filling target map that not worked correctly... Something like this. I knew that my way not correct, but use not working function - much worse... Until it will be fixed.
Hope you will understand what i tried to say here...

**Comment by yatzi888** [comment]
On my server it seems to fail everytime, I'll try the run in and out thing.

**Comment by killerwife** [comment]
Hold my beer.

**Comment by yatzi888** [comment]
@killerwife You just saved my weekend <3 I was 50% through sorting out a work around in the meantime involving an npc casting res on a player through the gossip window. Holy fuck, I love you.
