### ISSUE TITLE
Game Master - Ticket System

### ISSUE THREAD

**Issue by LewisPotato** [cmangos/issues#1853]
**Current behavior**: 
When responding to a ticket it will print the response in the text field where the text written by the user is stored. And the player has to click on "Edit Ticket" to view the response.
**Expected behavior**: 
The response should look like (https://static.fjcdn.com/pictures/Wow_2542ea_1041128.jpg) this in its own section and the user notified of a response to their ticket.
**Steps to reproduce**:

1.  Create a ticket on a player account.
2.  Respond to it on a GM account.
3.  Click the top right icon and click Edit Ticket and you will see the problem.

**Client version**: 
2.4.3.8606
**Commit hash**: 
CMaNGOS TBC/0.18 (2019-01-27T11:50:14+03:00 - d54c4e869f6e638deb9382853ea1945c4fd240fe) for Win64 (little-endian) [world-daemon]
**Database version**: 
TBC-DB 1.7.0 'A New Hope' for CMaNGOS-TBC
**Operating system**: 
Windows Server 2016: Standard

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
As you can see, there is achievement button on the screenshot. This screenshot and response field are only relevant to Wrath+ versions, earlier ones had in-game mail and whisper as means of communication between a GM and a player. 
However, there are some improvements to ticket system to be made across all versions which are not listed in this report. The interest to this area is noted, but this particular report is invalid in its current form due to version mismatch between expected functionality and the game's capability.
