### ISSUE TITLE
Nexus Item Does Not Work

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#1918]
Does looting this
http://www.wowhead.com/item=43095/berinands-research#comments
summoning boss?  or unfreese?

**Comment by Grz3s** [comment]
item works fine 
Part of:
https://www.wowhead.com/quest=13094/have-they-no-shame

Does not summon anything...(never should) 
Also creatures unfreeze automaticaly if u are there....

Last thing ... if u asking about 2 creatures that are listed on bosses list...and are there:
- Commander Stoutbeard - appears when horde team plays this instance
- Commander Kolurg - appears when alliance team plays this instance
Well.. thy're not bosses... appears only in (Heroic) mode... instead of normal commanders.

**Comment by jimmybrancaccio** [comment]
Hello,

Please use the bug template when filing issues. This allows us to collect all the necessary information to further investigate the issue.

Thanks,

**Comment by Grz3s** [comment]
i thought that I explained whole thing :o: 
Just close it....
