### ISSUE TITLE
One-Handed Specialization Visual adds +10% to Two-Handed Weapon

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1956]
## 🐛 Bugreport
One-Handed Specialization Visual adds +10% to Two-Handed Weapon.
But it seems only visual bug. DPS is the same, but player can see +10% damade. Look into the scrins:
One-hand weapon without talent and with it looks good.
![image](https://user-images.githubusercontent.com/39913306/58836947-d6ca2600-8662-11e9-8aa9-a73c70663617.png)

Two-hand weapon:
![image](https://user-images.githubusercontent.com/39913306/58837023-06792e00-8663-11e9-93c3-237e0945cfdf.png)

Seems talent reduce normal damage by 10%, but adds +10% from talent. So if you player you see it as if you have +10% damage, but damage not increase.

The same issue is for paladin talents.

### Expected behavior
It not influance on game I think, but this addition of 10% damage should not exist. It may influance on some other mechanic, that can not observe by players.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 2bd07043438cbae4b64352e9d14d35cf49c109b4
Database Repo & Commit Hash: c8569c4265b62678a574a8c3951a871ef5662843

Operating System: [Win 64]

### Steps to reproduce
1. Create warrior
2. Check damage with talent
3. Check damage without talent
4. ...
5. Profit

### Crashlog
- None

**Comment by al3xc1985** [comment]
confirm

**Comment by killerwife** [comment]
Notes on this issue:
The issue is 100% visual only and as such it is low priority for me.
The issue originates in:
void Aura::HandleModDamagePercentDone(bool apply, bool Real)
where we alter:
target->ApplyModSignedFloatValue(PLAYER_FIELD_MOD_DAMAGE_DONE_PCT, m_modifier.m_amount / 100.0f, apply);
no matter if the aura has weapon specific conditions. The alteration has to check for equipped items. This is easy, what is complicated however is that we need to recalculate it on equpping weapons.

**Comment by Yatzii93** [comment]
Speaking of visual bugs (or I assume visual), there seems to be an issue where armor debuffs don't visually get removed from the character pane details (aura isnt present on character). Players will sit with lik say -500 armor until they relog. Will try to gather some more info and a way to reproduce. Just thought it was worth noting.
