### ISSUE TITLE
Playerbot Crashes Client

### ISSUE THREAD

**Issue by jameschansell** [cmangos/issues#1969]
## 🐛 Bugreport
In certain cases, using the ".bot add [playername]" command causes the client to crash with the following error message. This error appears to be correlated with the login server reporting 'A character with that name already exists" when attempting login. Trying to log in multiple times has eventually led to success.   

![image](https://user-images.githubusercontent.com/8217901/59441139-f7098b80-8dac-11e9-98c7-c946383b9716.png)

I also notice that the mangosd server reports that it is unable to open the AHbot or Playerbot config files. 

![image](https://user-images.githubusercontent.com/8217901/59441204-10123c80-8dad-11e9-9c44-17e0953d130d.png)

I got everything running (mostly) following the installation guide, but notice that install guides for other servers have steps related to moving / re-naming the playerbot config file while CMangos-wotlk just mentioned turning on the option in the cmake build. It may be that I'm just missing a simple step - apologies, this is my first bug report / time working with any of this code.

### Expected behavior
Not crash when using ".bot add"

### Version & Environment

Client Version: 3.3.5a (WOTLK)

CMaNGOS Repo & Commit Hash:  [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/8e173b7ccf71bf5795dee036039618538161c03d)

Database Repo & Commit Hash: [WOTLK](https://github.com/cmangos/wotlk-db/tree/0a634f5519b3091b99f4471c0042aa0bf3df6d5a
)

Operating System: [Win 10]

### Steps to reproduce
1. Log into secondary character
2. Log out of secondary character
3. Log into primary character
4. Enter ".bot add [secondary character]"
5. Profit/Crash

### Crashlog

- Still trying to figure this part out

**Comment by jameschansell** [comment]
Also experienced the crash after entering non-playerbot /say and /shout text

**Comment by berserkingyadis** [comment]
Can't reproduce on TBC.

![botadded](https://user-images.githubusercontent.com/9959527/59458953-e6442e80-8e1b-11e9-8ac1-d9b97e745c6a.png)

Did:

1. Log into secondary character
2. Log out of secondary character
3. Log into primary character
4. Enter ".bot add [secondary character]"
5. Some /say and some /yell

May be WOTLK client issue?

core: 74e6f3a1766d56c2e56f3881bb26f1c98b4267b0
db: 53943cada35b81adf82d97d9fb40da84836edbac

**Comment by cyberium** [comment]
I have been able to reproduce it. However it need some deep digging i hate client crash...

**Comment by cala** [comment]
I'm unable to reproduce this at the moment. I agree with @cyberium: we need more data on how to replicate this.

**Comment by apock69** [comment]
This looks very similar to an issue I was having trying to get Ike3's playerbot and Cmangos vanilla working in Linux.  I think the problem is occurring because the core thinks that either character 1 or 2 is trying to login in twice, and therefore attempting to kick them off;

I believe it starts in CharacterHandler.cpp at KickPlayer here [at this line](https://github.com/cmangos/mangos-wotlk/blob/dcb0fb593d3f2113c7d4ad9d65691e2d8a46e984/src/game/Entities/CharacterHandler.cpp#L670)

This goes to WorldSession.cpp where the KickPlayer fuction is located eventually leading to Map.cpp.  Map.cpp calls         `    if (remove)        DeleteFromWorld(player);` At [Line 774](https://github.com/cmangos/mangos-wotlk/blob/dcb0fb593d3f2113c7d4ad9d65691e2d8a46e984/src/game/Maps/Map.cpp#L774-L775)

[DeleteFromWorld](https://github.com/cmangos/mangos-wotlk/blob/dcb0fb593d3f2113c7d4ad9d65691e2d8a46e984/src/game/Maps/Map.cpp#L226-L229) deletes the player.

Going back to CharacterHandler after KickPlayer try's to call another [delete](https://github.com/cmangos/mangos-wotlk/blob/dcb0fb593d3f2113c7d4ad9d65691e2d8a46e984/src/game/Entities/CharacterHandler.cpp#L671) on the player `        delete pCurrChar; `  but it can't because that memory location is no longer valid.

[The solution](https://github.com/apock69/mangosbot/commit/7a2888bca123b70b14d0000f1e7c60948c315c10) that I came up with seems to work but I don't know if it was the best way to handle it.

**Comment by killerwife** [comment]
Closing this as its stale.
