### ISSUE TITLE
🐛 Unpopped Darkmist Eye

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#2039]
## 🐛 Bugreport

Unpopped Darkmist Eye
100% chance (1-3)

**Comment by killerwife** [comment]
I assume this is confirmed on classic.

**Comment by Tobschinski** [comment]
yeah killed roughly 40 with my party, for sure not the 35% classicdb uses

**Comment by AnonXS** [comment]
can confirm dropped plenty on every mob

**Comment by Phatcat** [comment]
If it is a quest item, then every time someone kills the mob without being on the quest and it is recorded, it's going to affect the overall drop chance of the item, so a 35% drop chance on classicdb could very well be a 100% drop chance, since the 65% can have all been people not being on the quest, or people who loot the mob AFTER the quest item has been picked up by someone else.

Drop chances, particularly in relation to quest items, is a complex matter.

Unless they changed the drop chance in 1.13, I'd say the best way to find the drop chance is to go on official classic, have the quest, and simply start killing; if you get the item on every kill, there's a good chance the 100% is right, if you get it on roughly 1/3 then the 35% is probably right.
Simply looking at classic.wowhead tells a somewhat different story, the story of a 100% drop chance by the looks of it;
https://classic.wowhead.com/item=5884/unpopped-darkmist-eye#dropped-by

**Comment by AnonXS** [comment]
We should recheck with old wowhead comments still to make sure
