### ISSUE TITLE
🐛 [Bug Report] Dynamic Creature/GOs spawning

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2051]
## 🚀 Feature
Creatures and Objects (like herbs) should spawn depending on how much players are in the zone.
Also rspawntimer should start ticking straight after killing the unit + creature should be respawned as completely new unit with new guid.

https://github.com/TrinityCore/TrinityCore/commit/59db2eeea0a35028779fd76372ae06cc98c8086f

I know on retail classic (current classic) its working a bit different then it was to real vanilla cause it has some bugs back in the days. This "system" got changed pretty much i guess with newer versions.

**Comment by al3xc1985** [comment]
@killerwife u have implemented this

**Comment by killerwife** [comment]
Nope, I have not even gone near this and it needs core-wide dynguid push which will take us a while. Keeping this opened.

**Comment by AnonXS** [comment]
the nostalrius legacy code in vmangos is not the solution to this issue, we've to rework zones/areas with dynguid as kw says, then we can talk about further improving this system.

**Comment by al3xc1985** [comment]
shouldn't we keep this open for prpblem reminder as kw said?

**Comment by AnonXS** [comment]
Our spawn_group system is exactly what this is. Now it has to be added for actual usecases, which should be performed in separate issues, case by case.

**Comment by killerwife** [comment]
Dynamic spawning is a blizzlike feature, yes, but until whole system is reworked with dynamic guid, that being pooling being thrown out entirely among other things, we cant even start thinking about that. Currently we have first dungeons that use it full (naxx and hellfire ramparts) and BGs but thats about it. We are in this transitional state for 2 years now so that we dont break every existing script :)

**Comment by al3xc1985** [comment]
:) thank you kw and AnonXS for all this info!
