### ISSUE TITLE
[Bug Report] - Uldaman - Altar of The Keepers

### ISSUE THREAD

**Issue by schell244** [cmangos/issues#2058]
**Current behavior**: 
Stone Golems don't become alive and attack player (but they face in players direction when walking across the room). They also can't be focused/klicked.

**Expected behavior**: 
Stone Golems become alive and attack player. After all golems are killed, the door to the next room should be opend.

**Steps to reproduce**:
1.  .go xyz 62.39 253.63 -26.58 70
3.  "activate" Altar of The Keepers

**Client version**: 
1.12.1(5875) 

**Commit hash**: 
CMaNGOS Repo & Commit Hash: Classic, Latest
CMaNGOS Classic/0.18 (2019-11-02T05:14:23+03:00 - 6986ea7c05fe173f83a6464e378e7ea6a8fff828) for Win64 (little-endian)

**Database version**: 
CMaNGOS Repo & Commit Hash: Classic DB, Latest
Using World DB: Classic DB version 1.10.1 "The Shifting Sands". For core Classic z2742.

**Operating system**: 
Win10

I found a ticket describing a different Uldaman issue on WOTLK, I don't know whether this is up to date anymore and whether both WOTLK and Classic share the same code at this place:
https://github.com/cmangos/issues/issues/1782

**Comment by Orcman2019** [comment]
I had the same issue but only with one of the Stone Keepers, the one on the right closest to the door. 

I used .gm on and .npc move and it was attackable...  then 3 or 4 more spawned and the door opened.

**Comment by Orcman2019** [comment]
Adding some pictures, on the latest attempt the 2 closest to the door seemed to aggro with consecrate and face me but didn't summon with the altar.. Once again used .gm on (so they can be selected) and .npc move, and .gm off and they were killable but the door didn't open. Reused the altar and it spawned 4 new keepers, killed 2 and the door opened.

![uldaman1](https://user-images.githubusercontent.com/58348159/72671907-09b50480-3a0f-11ea-847e-5beb6b1bd19d.jpg)
![uldaman2](https://user-images.githubusercontent.com/58348159/72671908-09b50480-3a0f-11ea-86eb-4cf813de24fb.jpg)

**Comment by lduguid** [comment]
Not related to the bug per-se but out of interest, how do you "activate" Altar of The Keepers ?  Is there a GM command to do it ? As some alters in the game like this one require 3 players to click on it. Cheers.

**Comment by Orcman2019** [comment]
That altar just right clicks to activate the stone keepers.

**Comment by canidae** [comment]
I can confirm that this is still an issue (server built with commit d697ac0189736aa1611b74c723df67a819ae0a57).

**Comment by cala** [comment]
I cannot reproduce the issue as of today. Three players clicked on the altar, the stone keepers came one after the other to attack. When the four of them were defeated, the doors opened. Everything is working as intended.

Could you tell-me if the issue still occurs to you? And if so, which steps can help me reproduce it, please ?

> Not related to the bug per-se but out of interest, how do you "activate" Altar of The Keepers ? Is there a GM command to do it ? As some alters in the game like this one require 3 players to click on it. Cheers.

@lduguid Altar-type gameobjects like this one require a certain number of players to use it (click on it) at the same time in order to trigger the spells. In the case of this object (ID 130511), `data0=3` which means that 3 players are required. The Altar of Blackrock in UBRS is quite similar, also requiring 3 players.

Dungeons Summoning Stones and warlocks' summoning portals are also altar-type GameObjects.

**Comment by lduguid** [comment]
@cala thank you for the clarification.  My question was more how to test these kind of gameobject's that require multiple people to click on if there is only one of you in game.  I assume GM's can single person click it?  Also, can you instruct player bots to also interact 'click' with go objects as well?

Cheers,

**Comment by cala** [comment]
No, bots cannot use this type of gameobjects. GMs cannot activate it either if they are alone.

There are two ways of a testing things related to these objects if you are playing alone:
- launch three different instances of wow.exe in windowed mode and login through three distinct accounts. This way, there are three "real" players from the server point of view
- change data0 to 1 for this gameobject's template so you can activate it even if alone

Unless I need to test things specifically related to the number of players using the gameobject, I usually choose the second option.

**Comment by Orcman2019** [comment]
The statues acted like they were getting aggro and reacting..

I could retry it in a few days but I solo'd it. I never had/will never have 2 more people on there to click it.

**Comment by schell244** [comment]
FYI once I created the ticket I was testing it with only one character as well and gm enabled/disabled. Thanks @cala for the clarification.

**Comment by canidae** [comment]
Unfortunately I'm unable to test this again, but when I last tested this we were 4 players, with no prior use of GM commands (only used _.npc move_ when golems were stuck as explained in issue). So the altar was activated as intended. I don't remember if the first golem attacked as intended or was stuck, but I'm certain golem 2, 3 and 4 all were stuck as explained in the issue (always facing one player, but neither moving nor attacking).
Not very helpful, but perhaps there has been some changes since commit d697ac0189736aa1611b74c723df67a819ae0a57 that could have resolved this issue?

**Comment by canidae** [comment]
I got the opportunity to test this again. Party of 5 unique players & clients this time.
This time two of the keepers attacked before anyone even touched the altar. We were fighting trash mobs when they suddenly joined in. The third keeper was activated after the first two keepers died.
Fourth keeper didn't activate, but when we used the altar, two more keepers spawned, making it a total of 5 keepers we killed. The door was opened after forth or fifth killed keeper.
Didn't have to use ".npc move" this time, but the encounter is still not working properly. At least this time we could progress without GM commands.

**Comment by Szymplo** [comment]
Hello.
There's is still problem with opening door to Achaedas
Client TBC 2.4.3
Commit Cmangos 61d211bc95aca27a6df421168a5dbc6696eb6210 
Commit TBC-db    c02b193e78dec115b8825d266ad4c9db3639ad4
System Debian 10 with MariaDB database

We tried two ways
1) Killing all thrash in room with keepers and then clicking portal makes them targetable one by one. Still after killing all keepers the door didn't open
2) Activating altar with thrash inside room and killing again all keepers and thrash at same time. Again it ended with room clear but door closed

I Know that's not a 70 level instance but IMHO this is very nice place to visit and boss to kill.
Few versions ago we did it but weird things took place. Three keepers got alive instead of last of them, but then door opened!
Today it seems that there is no legit way to get to last Uldaman boss and that makes it bug worth caring.

Best regards

**Comment by nate123456** [comment]
Here's my experience getting the fight to start with 3 unique clients on the current build.

Upon first entering the room, none of the Golems are attackable or targetable, and do not move. After 3 players interact with the stone in the middle, one golem activates and attacks the player, then once it dies, the next one spawned, and so on until all four were dead. When the last one died, the door opened as expected. 

I'd say the issue is cannot be currently replicated on classic and the encounter works as expected.

The issue can be updated to remove the tag `Needs Replication` and the tag `Can't Replicate` can be added until OP confirms the issue is resolved and/or the issue can simply be closed. 

If the previous commenter did have a problem with it in the current build of TBC, the `Version: TBC` tag could be added and the `Version: Classic` could be removed.

**Comment by AnonXS** [comment]
```
ServerToClient: SMSG_GAMEOBJECT_QUERY_RESPONSE (0x005F) Length: 135 ConnectionIndex: 0 Time: 10/23/2007 13:42:40.000 Number: 1945
Entry: 130511
Type: SummoningRitual (18)
Display ID: 2490
[0] Name: Altar of The Keepers
[1] Name: 
[2] Name: 
[3] Name: 
Icon Name: 
Cast Caption: 
Unk String: 
[0] Data: 3
[1] Data: 11568
[2] Data: 11206
[3] Data: 1
[4] Data: 0
[5] Data: 0
[6] Data: 1
[7] Data: 0
[8] Data: 0
[9] Data: 0
[10] Data: 0
[11] Data: 0
[12] Data: 0
[13] Data: 0
[14] Data: 0
[15] Data: 0
[16] Data: 0
[17] Data: 0
[18] Data: 0
[19] Data: 0
[20] Data: 0
[21] Data: 0
[22] Data: 0
[23] Data: 0
```

You need 3 Players to activate this Altar.

```
GAMEOBJECT_TYPE_RITUAL = 18
    data0: casters
```

![grafik](https://user-images.githubusercontent.com/19734826/146687697-07ab0817-0676-47c9-8f4e-5774c0f9b646.png)

all get activated one by one (could use some polising as they turn befor they remove unselectable unitflags)

![grafik](https://user-images.githubusercontent.com/19734826/146687775-9aa89eeb-00d3-44d9-9d12-1d00860cab3f.png)

**Comment by MilkmanMHOC** [comment]
This encounter is not working correctly in classic.  (note i have not tried it until recently with a group of players).  The stone keepers are active and attack-able before interacting with the alter in the middle.  If you kill them all and then interact with the alter, they spawn again and all instantly attack.  Defeating them either way does not open the door to the next area.  If you walk up to the doors you will draw agro and the mobs on the other side come in through the closed door and attack.  Defeating them does not open the door either.  

If this was working, i wonder if something got back ported that broke it again?

**Comment by AnonXS** [comment]
then open a new issue, because what you discribe is not what was discribed here. because they should not be attackable pre clicking the altar.

**Comment by MilkmanMHOC** [comment]
ok

**Comment by TrusterX** [comment]
i know this is old but you can trigger the Altar with partybots by issuing.

```
!gobject near
```

output is like

`40696,  130511 - [Altar of The Keepers X:104.845001 Y:272.453003 Z:-26.532200 MapId:70]
Found near gameobjects (distance 10.000000): 1 `

```
!gobject select [Altar of The Keepers X:104,845001 Y:272,453003 Z:-26,532200 MapId:70]
```
(insert Link by shift click)
`40696, Entry 130511 - [Altar of The Keepers X:104.845001 Y:272.453003 Z:-26.532200 MapId:70]`

Now select a partybot member and issue command:
```
!partybot use gobject
```
`Dirxia has used the object.`

repeat the last two steps until you have enough members.

i didnt found any documentation about this.

**Comment by celguar** [comment]
@TrusterX this is cmangos github, not vmangos. Cmangos does not have partybots, vmangos does

**Comment by TrusterX** [comment]
@celguar You're right. I must be confused with multiple tabs regarding *mangos. Sorry, I marked it as off-topic.

**Comment by Azglor8** [comment]
What is the GM command to activate the altar?
EDIT: if you want to remove the 3 person requirement, the command is:
UPDATE classicmangos.gameobject_template SET data0 = 1 WHERE entry = 130511
