### ISSUE TITLE
💬 [Support Request] Old backup imported - "database indicates that this database is out of date!"

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2091]
## 💬 Support Request

My backup now is old when it is imported back (realmd)
The server won't start with my old backup imported, it starts without.
```
classiccharacters-01.17.2020.sql
classicrealmd-01.17.2020.sql
```

When I try to import my 'classicrealmd-01.17.2020.sql' backup back into classicrealmd database I get different version error:

```
Realmd log -->

2020-01-17 19:00:44 ERROR:query ERROR: Unknown column 'required_z2748_01_realmd_banning' in 'field list'
2020-01-17 19:00:44 ERROR:The table `realmd_db_version` in your [REALMD] database indicates that this database is out of date!
2020-01-17 19:00:44 ERROR:
2020-01-17 19:00:44 ERROR:  [A] You have: --> `z2743_00_realmd_account_drop_sha.sql`
2020-01-17 19:00:44 ERROR:
2020-01-17 19:00:44 ERROR:  [B] You need: --> `z2748_01_realmd_banning.sql`
2020-01-17 19:00:44 ERROR:
2020-01-17 19:00:44 ERROR:You must apply all updates after [A] to [B] to use mangos with this database.
2020-01-17 19:00:44 ERROR:These updates are included in the sql/updates folder.
2020-01-17 19:00:44 ERROR:Please read the included [README] in sql/updates for instructions on updating.
```

How can I "update" my backup so it's new.
I can manually edit tables I guess..

The import error on mangos database still occurs.

```
Table 'classicmangos.db_script_string' doesn't exist
```
### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash:  
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/68556568285cc90ac6897e236365d286bb6bff87)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/65c04d32cfb86a937138313f0d622f1ef20d9b70)

Operating System: 
  - Linux Flavor
### Steps to reproduce
1. Import old backup.
2. Start server.
3. "database indicates that this database is out of date!"
4. ...
5. Hmmmmmmmmm

**Comment by Daedalus-code** [comment]
Manually edited my old backup.sql (realmd.sql) with new tables that it was complaining it was missing, works now.

**Comment by evil-at-wow** [comment]
You have closed the issue, but I'll still answer your original question. It might help you or someone else to understand how the database versioning currently works. You probably know some of what I'll say, but for completeness I'll try to give a fairly complete picture.

First, the core's database versioning system applies to all databases (using the default naming that's ```realmd```, ```characters``` and ```mangos```). I'll use the characters database below to explain it, for a reason that'll become clear soon, but remember the others are basically the same system.

Second, there's two types of data in these databases. 

The first type is what I'd call static, read-only data. It's data that, once installed for a given server installation, never changes. That's all the data in the mangos database, which is provided to you by this project (or alternative projects). It's of course also the reason why you typically don't make backups of this table. We highly recommand people to use the install scripts that come with the content data projects (classic-db, tbc-db, wotlk-db) to install or update this database (because of the complexity to get all the tables installed properly and in the correct order), but if you'd want you could update this database manually in a similar way for a newer core revision. Note that if you also want to add updates from the content database project, it becomes a bit more involved. I'm not going to explain that part here; unless you're a developer just use the install script from your content database to save yourself all the hasle.

The second type is what I'd call dynamic data. Data that's updated and changes all the time while the server is running. This is mainly the characters database, but the realmd database is also in this category. While the realmd database generally changes less frequently than the characters database, it does contain the data for things like the list of realms, the accounts on your server, banned accounts/IPs, uptime information, etc. The content projects never touch these two databases, so they are the full responsability of the server admin(s) to set up, upgrade and/or back up. Therefore, I'll take the characters database to show how versioning is done, because that's the database you'll likely update the most frequently (manually) as a server admin.

The current version of any database is kept in a table named ```db_version``` (mangos database), ```realmd_db_version``` (realmd database) or ```character_db_version``` (characters database). This table contains a field that's named after the current revision. For example, on a server I have here, the character_db_version of my character database contains a field named ```required_s2395_01_characters_WorldState```. This is how the core knows what version, or more precisely what revision of the database structure, my characters database has. If the core considers this outdated, this will be referenced as the ```[A] You have``` in the message. In the realmd log extract you posted above, this is **z2743_00_realmd_account_drop_sha** (also note it mentions the realmd_db_version table in the log).

On the other hand, the core has a built-in expected version of the databases (see src/shared/revision_sql.h). If the database structure of any databases changes, developers have to adjust this as part of the commit, so the core can warn about a now outdated database structure. This expected version is referred to as the ```[B] You need``` in the message.

That leaves one question: how do you transform the database structure from [A] to [B]? Well, as part of the database structure change commit, core developers also have to provide a SQL update file. These are in the sql/updates folder of the core repository, in a subdirectory per database. To upgrade a database structure from [A] to [B], you have to apply **all** SQL updates from the database subfolder **in order**, starting with the first one **after [A]** and **up to and including [B]**.

Let's do this with an example, using the TBC version. Say that for some reason I restored an old backup of my characters database, and silly me forgot to update it of course, and now my core complains that 

```
ERROR:  [A] You have: --> `s2375_01_characters_pet_loyalty.sql`
ERROR:
ERROR:  [B] You need: --> `s2388_01_characters_fix_skills_overflow.sql`
```

To demonstrate a slightly more complex situation, let's say I also built/installed this core a while ago, then later I updated my git repository but without having built/installed a newer core yet. Ok, I say, let's see what updates I need to apply then. I check my git repository on disk, and since this is about the characters database, I have to look in sql/updates/characters and see this list of files (sorted order):
```
s2327_01_characters_pvpstats.sql
s2333_01_characters_reset_talents.sql
s2335_01_characters_wotlk_timer_port.sql
s2337_01_characters_weekly_quests.sql
s2343_01_characters_mangle_cleanup.sql
s2345_01_characters_instance.sql
s2346_01_characters_playerbot_saved_data.sql
s2352_01_characters_fix_revision.sql
s2357_01_characters_spell_cooldown.sql
s2358_01_characters_event_group_chosen.sql
s2359_01_characters_account_instances_entered.sql
s2370_01_characters_taxi_system_update.sql
s2375_01_characters_pet_loyalty.sql
s2376_01_characters_taxi_system_format_update.sql
s2379_01_characters_playerbot_saved_data.sql
s2386_01_characters_skills_cleanup_1829.sql
s2387_01_characters_weapon_skills_fix_tbc.sql
s2388_01_characters_fix_skills_overflow.sql
s2389_00_characters_cooldown.sql
s2395_01_characters_WorldState.sql
```
Remember I need all updates after [A], and up to including [B], so in my example this becomes this list of files:
```
s2376_01_characters_taxi_system_format_update.sql
s2379_01_characters_playerbot_saved_data.sql
s2386_01_characters_skills_cleanup_1829.sql
s2387_01_characters_weapon_skills_fix_tbc.sql
s2388_01_characters_fix_skills_overflow.sql
```
Now it's a matter of applying these 5 SQL updates, one by one and in the order listed, to my character database, and I'm done upgrading it! Note that I do not need the first few updates from the list. These were already applied earlier because my character database structure is already at [A] s2375_01_characters_pet_loyalty.sql. Also note I do not need the last two updates listed, because these are after [B] s2388_01_characters_fix_skills_overflow.sql, which means my core doesn't have that code yet. Remember I said I updated my git repository without rebuilding the core? That's why I have these files on disk but my core doesn't have that code yet. Once I build a newer core with the git updates I fetched, I'll likely have to apply these two as well (but in case of doubt, just start the server and it will tell you what you have and what you need if these don't match).

As I mentioned before, updating your realmd database is similar. You apply updates from sql/updates/realmd instead, again in order, and only those after [A] and up to and including [B]. That's basically all there is to updating a database manually, and once you understand what to do, it's a nearly trivial task.

**Comment by Daedalus-code** [comment]
Starting to get a picture , thank you so much for taking your time with this.

So I could just update from ' sql/updates/realmd ' with correct updates in correct order without me editing manually :P 



" Only those after [A] and up to and including [B]. "

I will try to remember that!

Again, Thank you!

**Comment by AnthonyPaulO** [comment]
> You have closed the issue, but I'll still answer your original question. It might help you or someone else to understand how the database versioning currently works. You probably know some of what I'll say, but for completeness I'll try to give a fairly complete picture.
> 
> First, the core's database versioning system applies to all databases (using the default naming that's `realmd`, `characters` and `mangos`). I'll use the characters database below to explain it, for a reason that'll become clear soon, but remember the others are basically the same system.
> 
> Second, there's two types of data in these databases.
> 
> The first type is what I'd call static, read-only data. It's data that, once installed for a given server installation, never changes. That's all the data in the mangos database, which is provided to you by this project (or alternative projects). It's of course also the reason why you typically don't make backups of this table. We highly recommand people to use the install scripts that come with the content data projects (classic-db, tbc-db, wotlk-db) to install or update this database (because of the complexity to get all the tables installed properly and in the correct order), but if you'd want you could update this database manually in a similar way for a newer core revision. Note that if you also want to add updates from the content database project, it becomes a bit more involved. I'm not going to explain that part here; unless you're a developer just use the install script from your content database to save yourself all the hasle.
> 
> The second type is what I'd call dynamic data. Data that's updated and changes all the time while the server is running. This is mainly the characters database, but the realmd database is also in this category. While the realmd database generally changes less frequently than the characters database, it does contain the data for things like the list of realms, the accounts on your server, banned accounts/IPs, uptime information, etc. The content projects never touch these two databases, so they are the full responsability of the server admin(s) to set up, upgrade and/or back up. Therefore, I'll take the characters database to show how versioning is done, because that's the database you'll likely update the most frequently (manually) as a server admin.
> 
> The current version of any database is kept in a table named `db_version` (mangos database), `realmd_db_version` (realmd database) or `character_db_version` (characters database). This table contains a field that's named after the current revision. For example, on a server I have here, the character_db_version of my character database contains a field named `required_s2395_01_characters_WorldState`. This is how the core knows what version, or more precisely what revision of the database structure, my characters database has. If the core considers this outdated, this will be referenced as the `[A] You have` in the message. In the realmd log extract you posted above, this is **z2743_00_realmd_account_drop_sha** (also note it mentions the realmd_db_version table in the log).
> 
> On the other hand, the core has a built-in expected version of the databases (see src/shared/revision_sql.h). If the database structure of any databases changes, developers have to adjust this as part of the commit, so the core can warn about a now outdated database structure. This expected version is referred to as the `[B] You need` in the message.
> 
> That leaves one question: how do you transform the database structure from [A] to [B]? Well, as part of the database structure change commit, core developers also have to provide a SQL update file. These are in the sql/updates folder of the core repository, in a subdirectory per database. To upgrade a database structure from [A] to [B], you have to apply **all** SQL updates from the database subfolder **in order**, starting with the first one **after [A]** and **up to and including [B]**.
> 
> Let's do this with an example, using the TBC version. Say that for some reason I restored an old backup of my characters database, and silly me forgot to update it of course, and now my core complains that
> 
> ```
> ERROR:  [A] You have: --> `s2375_01_characters_pet_loyalty.sql`
> ERROR:
> ERROR:  [B] You need: --> `s2388_01_characters_fix_skills_overflow.sql`
> ```
> 
> To demonstrate a slightly more complex situation, let's say I also built/installed this core a while ago, then later I updated my git repository but without having built/installed a newer core yet. Ok, I say, let's see what updates I need to apply then. I check my git repository on disk, and since this is about the characters database, I have to look in sql/updates/characters and see this list of files (sorted order):
> 
> ```
> s2327_01_characters_pvpstats.sql
> s2333_01_characters_reset_talents.sql
> s2335_01_characters_wotlk_timer_port.sql
> s2337_01_characters_weekly_quests.sql
> s2343_01_characters_mangle_cleanup.sql
> s2345_01_characters_instance.sql
> s2346_01_characters_playerbot_saved_data.sql
> s2352_01_characters_fix_revision.sql
> s2357_01_characters_spell_cooldown.sql
> s2358_01_characters_event_group_chosen.sql
> s2359_01_characters_account_instances_entered.sql
> s2370_01_characters_taxi_system_update.sql
> s2375_01_characters_pet_loyalty.sql
> s2376_01_characters_taxi_system_format_update.sql
> s2379_01_characters_playerbot_saved_data.sql
> s2386_01_characters_skills_cleanup_1829.sql
> s2387_01_characters_weapon_skills_fix_tbc.sql
> s2388_01_characters_fix_skills_overflow.sql
> s2389_00_characters_cooldown.sql
> s2395_01_characters_WorldState.sql
> ```
> 
> Remember I need all updates after [A], and up to including [B], so in my example this becomes this list of files:
> 
> ```
> s2376_01_characters_taxi_system_format_update.sql
> s2379_01_characters_playerbot_saved_data.sql
> s2386_01_characters_skills_cleanup_1829.sql
> s2387_01_characters_weapon_skills_fix_tbc.sql
> s2388_01_characters_fix_skills_overflow.sql
> ```
> 
> Now it's a matter of applying these 5 SQL updates, one by one and in the order listed, to my character database, and I'm done upgrading it! Note that I do not need the first few updates from the list. These were already applied earlier because my character database structure is already at [A] s2375_01_characters_pet_loyalty.sql. Also note I do not need the last two updates listed, because these are after [B] s2388_01_characters_fix_skills_overflow.sql, which means my core doesn't have that code yet. Remember I said I updated my git repository without rebuilding the core? That's why I have these files on disk but my core doesn't have that code yet. Once I build a newer core with the git updates I fetched, I'll likely have to apply these two as well (but in case of doubt, just start the server and it will tell you what you have and what you need if these don't match).
> 
> As I mentioned before, updating your realmd database is similar. You apply updates from sql/updates/realmd instead, again in order, and only those after [A] and up to and including [B]. That's basically all there is to updating a database manually, and once you understand what to do, it's a nearly trivial task.

Hey @evil-at-wow ! Sorry for resurrecting this, but your post was so informative that I want to thank you for having taken your time to detail this all so nicely for us noobs. I've tasked myself with updating an add-on called pfQuest to support WOTLK and I have zero WoW add-on experience so your write-up was very illuminating, thank you so much! I'm currently setting up the initial environment and trying to put together the latest cmangos TBC database but I've been seeing errors when trying to execute the tbc-db scripts after the the cmangos mangos-tbc scripts due to 'unknown column xxx in db_version' errors and your post helped me understand what this is all about. I'm guessing I can't just naively run the updates from mangos-tbc first and then the tbc-db scripts after because the updates are intermingled with each other (ie. mangos-tbc range from s2326-s2463 while tbc-db range from s2436-s2462), so I'll have to write a script that makes sure I run both sets of updates in the correct order; I'll still get errors since the tbc-db has duplicate db_version changes but at least the rest of the code in the scripts will come in at the right time.

**Comment by evil-at-wow** [comment]
Thank you for the kind words, @AnthonyPaulO. It's always a pleasure to hear some of our work was helpful and is appreciated!

Related to your issues, the part that's probably missing in my former post is that projects like tbc-db are content database and only touch the ```mangos``` database (using the default naming), not the other databases. Because this database only contains what I called static, read-only data, it can easily be wiped and rebuilt from scratch, so that's basically what the tbc-db install script is doing (InstallFullDB.sh). 

So if you're setting up an initial environment - rather than updating an existing server - you can create the initial (empty) databases using the files from the core:
* Apply ```<git repository>/sql/create/db_create_mysql.sql``` to creates the empty databases and set up some permissions for the database user. You can check the file and adjust it if you prefer to use differerent names of course, but sticking to the defaults is probably a good idea for a first server setup.
* Apply ```<git repository>/sql/base/mangos.sql```, ```<git repository>/sql/base/characters.sql```, ```<git repository>/sql/base/logs.sql``` and ```<git repository>/sql/base/realmd.sql``` to create the necessary tables in those databases.

With that, you're basically set to run the server core, but the world will probably be very empty because it has no content yet. This is where a project like tbc-db comes in, and the easiest way to install it is to run ```./InstallFullDB.sh``` from the tbc-db folder, which will first create a ```InstallFullDB.config``` file. Have a look at this file, and fill in the details about your database, then run ```./InstallFullDB.sh``` again. This time it should fill the mangos database (and from now on you can simply re-run ```./InstallFullDB.sh``` to rebuild the mangos database).

The point where the updates come in that I described earlier, is when the core has updates that tbc-db hasn't applied yet. In that case tbc-db will basically generate a mangos database that, from the core's perspective, is out of date. And that's where you apply the missing updates for the mangos database 'manually' (could be scripted, as you say). If you run any mangos-tbc updates first, that work will basically be undone by the tbc-db installation because it rebuilds the mangos database tables from scratch.

So the main point to remember is that the content databases rebuild the entire mangos database (only), so you run their installation first, and then, as needed, apply missing mangos-tbc updates. The character and realm databases are not touched by the content projects, so once you have an initial server you need to apply the relevant core updates when they're out of date.

Best of luck!

**Comment by AnthonyPaulO** [comment]
> Thank you for the kind words, @AnthonyPaulO. It's always a pleasure to hear some of our work was helpful and is appreciated!
> 
> Related to your issues, the part that's probably missing in my former post is that projects like tbc-db are content database and only touch the `mangos` database (using the default naming), not the other databases. Because this database only contains what I called static, read-only data, it can easily be wiped and rebuilt from scratch, so that's basically what the tbc-db install script is doing (InstallFullDB.sh).
> 
> So if you're setting up an initial environment - rather than updating an existing server - you can create the initial (empty) databases using the files from the core:
> 
> * Apply `<git repository>/sql/create/db_create_mysql.sql` to creates the empty databases and set up some permissions for the database user. You can check the file and adjust it if you prefer to use differerent names of course, but sticking to the defaults is probably a good idea for a first server setup.
> * Apply `<git repository>/sql/base/mangos.sql`, `<git repository>/sql/base/characters.sql`, `<git repository>/sql/base/logs.sql` and `<git repository>/sql/base/realmd.sql` to create the necessary tables in those databases.
> 
> With that, you're basically set to run the server core, but the world will probably be very empty because it has no content yet. This is where a project like tbc-db comes in, and the easiest way to install it is to run `./InstallFullDB.sh` from the tbc-db folder, which will first create a `InstallFullDB.config` file. Have a look at this file, and fill in the details about your database, then run `./InstallFullDB.sh` again. This time it should fill the mangos database (and from now on you can simply re-run `./InstallFullDB.sh` to rebuild the mangos database).
> 
> The point where the updates come in that I described earlier, is when the core has updates that tbc-db hasn't applied yet. In that case tbc-db will basically generate a mangos database that, from the core's perspective, is out of date. And that's where you apply the missing updates for the mangos database 'manually' (could be scripted, as you say). If you run any mangos-tbc updates first, that work will basically be undone by the tbc-db installation because it rebuilds the mangos database tables from scratch.
> 
> So the main point to remember is that the content databases rebuild the entire mangos database (only), so you run their installation first, and then, as needed, apply missing mangos-tbc updates. The character and realm databases are not touched by the content projects, so once you have an initial server you need to apply the relevant core updates when they're out of date.
> 
> Best of luck!

@evil-at-wow, thank you so much; the community needs people like you! :)
