### ISSUE TITLE
🐛 [Bug Report] Accessing field out of bounds in BattleGroundMgr.cpp

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2095]
## 🐛 Bugreport
https://github.com/cmangos/mangos-tbc/blob/master/src/game/BattleGround/BattleGroundMgr.cpp#L1647 attempts to access field[8], but this is out of bounds and is causing a segfault upon starting the server.
Likely an oversight from this commit: https://github.com/cmangos/mangos-tbc/commit/bdfe094cedf1c83cef23db46bb2a36c8e56a9a1b
~Changing it to `field[6]` is likely the way to fix it.~ Edit: Incorrect, see comment below.

(Remaining fields of bug report is irrelevant, erasing).

**Comment by evil-at-wow** [comment]
Great catch!

I'm not convinced using ```field[6]``` is the way to go here though, because that looks to be an ID used to get the horde start location from sWorldSafeLocsStore (see a few lines earlier).

And to add to your discovery, there's more code in that function that smells a bit. While ```AStartLoc[3] = fields[6].GetFloat();```  on line 1624 is not an out of bounds access, it seems off given that field 6 is horde related...

**Comment by canidae** [comment]
It's quite likely changing it from field[8] to field[6] is incorrect. I thought it was two prior fields that were removed (5 & 7), but I see now that what used to be field[6] and field[8] were the ones that was removed. My mistake, thanks for correcting it!

**Comment by ratkosrb** [comment]
This appears to be a bug that happened when the commit was ported from classic to tbc, because those lines do not actually exist in the classic core.

These two lines must be changed to assign 0 to the orientation.
https://github.com/cmangos/mangos-tbc/blob/master/src/game/BattleGround/BattleGroundMgr.cpp#L1624
https://github.com/cmangos/mangos-tbc/blob/master/src/game/BattleGround/BattleGroundMgr.cpp#L1647
