### ISSUE TITLE
🐛 [Classic] Incorrect Feign Death behaviour with active pet

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2104]
## 🐛 Bugreport
A hunter using Feign Death with active pet cause enemies to attack pet, but upon pet death the enemies will return their attention to the hunter.

### Expected behavior
I'm not entirely, but fairly sure that Feign Death in original WoW the behaviour was that enemies would kill the pet, but not attack the still feigning hunter once the pet was dead.

### Version & Environment
  - Client: "1.12.1" (CLASSIC)
  - Server: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/3b3df96c90e06691ae6324cfb0b3341180d2e414)
  - Database: [CLASSIC](https://github.com/cmangos/classic-db/tree/e15ef1e135943f59961746cb1fbfae974e8cb16e)
  - OS: Linux Arch

### Steps to reproduce
1. Attack enemy with pet on defensive mode.
2. Use Feign Death.
3. Feign Death until enemy kills pet.
4. Enemy attacks hunter.
5. Repeat steps, but this time without pet. Enemy will disengage immediately upon Feign Death.
6. Profit.

**Comment by Warlockbugs** [comment]
Pets were propagating combat to master combat even through FD.

Fixed in:
https://github.com/cmangos/mangos-classic/commit/72a978accf754d71bd2969900073b7a111df2053
https://github.com/cmangos/mangos-tbc/commit/afcd80704c33b6601eaf20ff5760b33a10269323
https://github.com/cmangos/mangos-wotlk/commit/68ab30b8fb1e0eebed357e05be6a426b906e5ce1
