### ISSUE TITLE
💬 [Support Request]Shattered Halls Scripting

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2120]
This is more a Discussion Thread about how to script this.
Client Version:  2.4.3 (TBC)

I just started looking and fixing Shattered Halls. Cause this is a real complex instance with many events, i start this threat to discuse the best way about Scripting this.

I will start with the first group and the Bugs i found.

- [x] One spawn seem a bit off. (His spawn point is already his final waypoint position from Intro)
- [x] Intro moving of the Savages/Heathen seem a bit off. (Add Final emote)
- [x] On Heroic there should only spawn Shattered Hand Heathen, on normal both can spawn. Heathen/Savage
- [x] Group isnt linked to Boss
- [ ] The ooc event where the legionnair is going to a heathen/savage is missing on the first group.
- [ ] Its a Group with legionnair as Leader. When a slave dies, a new one spawns in the back and runs to the Position where the one who got killed stayed.

The first things of this i already fixed (see Pull Request), the last thing is a bit complicated.  
Here is my Idea to fix it:

- Set the final waypoint from Savage/Heathen as Homeposition when the final waypoint is reached.
- On Death send AI to Legionnair (find leader GUID) (maybe via Custom Flag in CreatureLinkingEvent or as new ACTION_EVENT_AI)
- Legionnair script via Core, on AI Recive Event check for legionnair GUID, spawn new creature with Fixed position
- Let new Creature walk to the homepostion of the old creature.

I Will add some more pictures/videos later.

**Comment by MantisLord** [comment]
Good work/observations so far. I'll go over each of the items on your list one by one and give my thoughts. 

 - One spawn seem a bit off. (His spawn point is already his final waypoint position from Intro)

You're right about this one - CGUID+135 appears to spawn at his final waypoint location which is indeed wrong.

-  Intro moving of the Savages/Heathen seem a bit off. (Add Final emote)

It seems you moved emote 333 out of creature_addon and made it a dbscript instead that they use once they reach their final waypoint. Not sure exactly what the difference is really, but I suppose I'm okay with this change as well.

-  On Heroic there should only spawn Shattered Hand Heathen, on normal both can spawn. Heathen/Savage

This sounds tricky to me, but you're definitely on the right track by adding new heroic only spawns using spawnMask.

- Group isnt linked to Boss

This one I have to question... do you have proof that this group should not respawn in the event Grand Warlock Nethekurse is killed? We did some testing on retail for this and discovered that the vast majority of the time in TBC dungeons, there is no "cannot spawn when boss is dead" style linking. The mobs will still respawn after some period even if the bosses are dead. Perhaps I'm wrong in the specific case of this pack, but we should confirm this on retail before adding it, even if it *seems* right to have.

-  The ooc event where the legionnair is going to a heathen/savage is missing on the first group.

This one should be scripted currently, although perhaps a little crudely. The dbscript is here for Legionnaire CGUID+74
https://github.com/cmangos/tbc-db/blob/master/Updates/Instances/540_shattered_halls.sql#L1013
There's a 10% chance the "approach ally" relay script 10114 will be triggered, which is the RP where the Legionnaire goes up to one of the mobs and does some emotes:
https://github.com/cmangos/tbc-db/blob/master/Updates/Instances/540_shattered_halls.sql#L947
There are a couple problems with this script though... First, he moves too close to the npc he is approaching so it ends up looking a little strange:
![image](https://user-images.githubusercontent.com/16798471/73911152-44c48e00-487f-11ea-938c-5ae97cbddea5.png)
Second, if you notice relay script 10114 is hard-coded to look for entry 17420 (Shattered Hand Heathen), so this means he will never do this script for any Shattered Hand Savage which may be spawned instead. The only way I can think to work around this is to make a separate script for each guid and don't look for nearby creature with entry 17420.

-  Its a Group with legionnair as Leader. When a slave dies, a new one spawns in the back and runs to the Position where the one who got killed stayed.

This one I thought about for awhile too, but what I ended up settling on is actually quite simple and already in place. If you notice, I've purposefully set the respawn timer of all the mobs in this first pack (except the Legionnaire) to be super fast (5 seconds) https://github.com/cmangos/tbc-db/blob/master/Updates/Instances/540_shattered_halls.sql#L686
So this ends up essentially emulating the exact behavior you describe and as can be seen on retail. You can kill the Savages/Heathens as much as you want, but as long as the Legionnaire is alive, they will continue to respawn and run back into formation.
Let me know if you think there's anything wrong with the way this is implemented currently. We could lower the respawn time down even further if you feel like 5 seconds isn't responsive enough. I think 5 seconds was chosen because of how fast we saw them coming back during retail testing.

**Comment by killerwife** [comment]
Small warning "It seems you moved emote 333 out of creature_addon and made it a dbscript instead that they use once they reach their final waypoint. Not sure exactly what the difference is really, but I suppose I'm okay with this change as well."
If you do this, you need to then manually remove the emote on aggro and reinstate it on OOC, because addon does just that.

**Comment by AnonXS** [comment]
The problem with addon is that npcs will play the emote on every waypoint reached looks strange, even if they move further afterwards. Maybe something to think about to disable emote addon while movement is going on.

**Comment by killerwife** [comment]
If that is the case, I cannot remedy that automatically. I am only able to disable addon emote/stand state on combat enter. If you need such fine grained control, AI + dbscript is always needed.

**Comment by al3xc1985** [comment]
This is the case of my last quest bug report @killerwife  as @AnonXS  described

**Comment by Grz3s** [comment]
(...)`Maybe something to think about to disable emote addon while movement is going on.`
Be careful with this.. theyre plenty npc ..using state emote (example: 69) .. even during movement...
db_scripts work well for whats needed here

**Comment by killerwife** [comment]
I thought as much. That is why combat enter + addon is the only thing I addressed with my patch. Everything else needs to be scripted manually.

**Comment by miraco** [comment]
> 
> 
> It seems you moved emote 333 out of creature_addon and made it a dbscript instead that they use once they reach their final waypoint. Not sure exactly what the difference is really, but I suppose I'm okay with this change as well.

Yes like AnonXS said, with creature Addon they always try to use the emote while moving. In my version it works like it should.
> If you do this, you need to then manually remove the emote on aggro and reinstate it on OOC, because addon does just that.

Its using the same way creature_addon uses, just after the waypoint. So no dont have to remove/add it. (SCRIPT_COMMAND_FIELD_SET

>     * On Heroic there should only spawn Shattered Hand Heathen, on normal both can spawn. Heathen/Savage
> 
> 
> This sounds tricky to me, but you're definitely on the right track by adding new heroic only spawns using spawnMask.

I normaly dont like adding more GUID spawns, but we currently dont have an option to set spawn_entry for normal/heroic. 
> 
>     * Group isnt linked to Boss
> 
> 
> This one I have to question... do you have proof that this group should not respawn in the event Grand Warlock Nethekurse is killed? We did some testing on retail for this and discovered that the vast majority of the time in TBC dungeons, there is no "cannot spawn when boss is dead" style linking. The mobs will still respawn after some period even if the bosses are dead. Perhaps I'm wrong in the specific case of this pack, but we should confirm this on retail before adding it, even if it _seems_ right to have.
> 
Thats a good question, i gonna try it on retail when i find a bit time. 

>     * The ooc event where the legionnair is going to a heathen/savage is missing on the first group.
> 
> 
> This one should be scripted currently, although perhaps a little crudely. The dbscript is here for Legionnaire CGUID+74
> https://github.com/cmangos/tbc-db/blob/master/Updates/Instances/540_shattered_halls.sql#L1013
> There's a 10% chance the "approach ally" relay script 10114 will be triggered, which is the RP where the Legionnaire goes up to one of the mobs and does some emotes:
> https://github.com/cmangos/tbc-db/blob/master/Updates/Instances/540_shattered_halls.sql#L947
> There are a couple problems with this script though... First, he moves too close to the npc he is approaching so it ends up looking a little strange:
> ![image](https://user-images.githubusercontent.com/16798471/73911152-44c48e00-487f-11ea-938c-5ae97cbddea5.png)
> Second, if you notice relay script 10114 is hard-coded to look for entry 17420 (Shattered Hand Heathen), so this means he will never do this script for any Shattered Hand Savage which may be spawned instead. The only way I can think to work around this is to make a separate script for each guid and don't look for nearby creature with entry 17420.
> 
Yes its scripted but like you said not looking rly nice and giving errors in Core. Want to look into it next.

>     * Its a Group with legionnair as Leader. When a slave dies, a new one spawns in the back and runs to the Position where the one who got killed stayed.
> 
> 
> This one I thought about for awhile too, but what I ended up settling on is actually quite simple and already in place. If you notice, I've purposefully set the respawn timer of all the mobs in this first pack (except the Legionnaire) to be super fast (5 seconds) https://github.com/cmangos/tbc-db/blob/master/Updates/Instances/540_shattered_halls.sql#L686
> So this ends up essentially emulating the exact behavior you describe and as can be seen on retail. You can kill the Savages/Heathens as much as you want, but as long as the Legionnaire is alive, they will continue to respawn and run back into formation.
> Let me know if you think there's anything wrong with the way this is implemented currently. We could lower the respawn time down even further if you feel like 5 seconds isn't responsive enough. I think 5 seconds was chosen because of how fast we saw them coming back during retail testing.

Yes this could work for the first Group. But looking with 1 eye at the other Groups with legionnaires i dont think this is the right way to handle it. 
For example the next 2/3 groups dont respawn the mobs when a slave die, instead there is a new npc getting spawned on a fixed spawnpoint + using fixed waypoints.
The interesting part just starts before the first boss when its get even more complicated. When a group slave die, one of the sleeping mobs around joins the fight. 
Same after the FlameGauntlet.

**Comment by killerwife** [comment]
Its using the same way creature_addon uses, just after the waypoint. So no dont have to remove/add it. (SCRIPT_COMMAND_FIELD_SET - this assumption is wrong.
You are right, it uses the same code, but I have recently prototyped a functionality where creature_addon emote_state and standstate is automatically removed on combat start, and automatically reinstated on combat end. This cannot be done with ANY other script, be it EAI setting, dbscript setting or SD2 setting because then there are a lot of mobs and bosses who use it inside the scripts. As a result, I cannot autoremove your setting in dbscripts and it will look horribly during combat. Which then leads to you requiring it to unset it on aggro in EAI and setting on evade in EAI.

**Comment by MantisLord** [comment]
> Yes this could work for the first Group. But looking with 1 eye at the other Groups with legionnaires i dont think this is the right way to handle it.
> For example the next 2/3 groups dont respawn the mobs when a slave die, instead there is a new npc getting spawned on a fixed spawnpoint + using fixed waypoints.
> The interesting part just starts before the first boss when its get even more complicated. When a group slave die, one of the sleeping mobs around joins the fight.
> Same after the FlameGauntlet.

Yes that's right, I'm aware the later groups with Legionnaires have different behaviors as you described - I'm speaking only for the very first pack in the dungeon right now which we've been discussing. The others will need different solutions. The reinforcements spawning and running in behavior is indeed missing and is different from this fast respawn behavior we see in the first pack.

I'm of the opinion that it's fairly blizzlike the way the respawning happens currently for the first pack and thus doesn't require any additions/changes. As for the remaining Legionnaire packs, they will need some love :)

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/228df00b8f9f8e526e33597c38b7a46be592d1b6
this autofixes 90% of weird combat animations. Anything extra can't be done manually.

**Comment by miraco** [comment]
> This one I have to question... do you have proof that this group should not respawn in the event Grand Warlock Nethekurse is killed? We did some testing on retail for this and discovered that the vast majority of the time in TBC dungeons, there is no "cannot spawn when boss is dead" style linking. The mobs will still respawn after some period even if the bosses are dead. Perhaps I'm wrong in the specific case of this pack, but we should confirm this on retail before adding it, even if it seems right to have.
> 
I can test it on retail today, but i am not sure that this is a good proof. Maybe it got added with laters patches.

> There are a couple problems with this script though... First, he moves too close to the npc he is approaching so it ends up looking a little strange:

This one was easier to fix then i thought.  
`datalong3 = Exact contact point distance, to be used when you want to stop moving as soon as you're within this distance of the target`

he stops moving now when he is 1 yard away. 
Adjusted some timers here (just with watching videos/testing ingame.
I added a check to look if the creature is in range of 6 yards before executing the rest this should prevent the error.
Also added this for Savage NPC.

> 
> [cmangos/mangos-tbc@228df00](https://github.com/cmangos/mangos-tbc/commit/228df00b8f9f8e526e33597c38b7a46be592d1b6)
> this autofixes 90% of weird combat animations. Anything extra must be done manually.

I couldnt find any weird combat animations. 

https://github.com/cmangos/tbc-db/pull/719/commits/3af287f6431ce2139e996b864b2b343d52fa309a

**Comment by MantisLord** [comment]
Good observation with the datalong3 param of that command, I had forgotten about that!
I'm also okay with how you added a script to handle both Heathen and Savage - looks good.

You're right that retail may have changed in terms of the respawn/linking to boss behavior, but in general for the TBC dungeons/raids it's still fairly accurate. I guess we won't know 100% for sure until blizz decides to re-release TBC.

I'll review your changes as a whole today and merge assuming it's ready. Probably good to keep the scope of this to just the first pack. You can make separate PRs or whatever works for you if you end up working on the other packs in the dungeon later :)

**Comment by miraco** [comment]
Already found some errors. Guess i pushed it to fast. :) Will Add it later.
I think we should merge this when all is finished. There will be some more updates in future.

**Comment by MantisLord** [comment]
Okay sure thing, I'll hold off on it until you're ready in that case then.

**Comment by MantisLord** [comment]
Just a note, mostly for myself... You may be right after all about the "cannot respawn if boss dead" linking. I went onto retail the other day, and killed everything up to and including Grand Warlock Nethekurse. I waited 2 hours and the packs still hadn't respawned.
So unless this changed since TBC, I'd say you're on the right track with adding that.

**Comment by miraco** [comment]
> 
> 
> Just a note, mostly for myself... You may be right after all about the "cannot respawn if boss dead" linking. I went onto retail the other day, and killed everything up to and including Grand Warlock Nethekurse. I waited 2 hours and the packs still hadn't respawned (this was on Heroic difficulty for reference).
> So unless this changed since TBC, I'd say you're on the right track with adding that.

Yeah i will add it, we can still remove it when someone can prove its not blizzlike in bc. But for me it dont make sense that trash respawns when boss is dead even in dungeons.

After watching the First group on retail again for 20mins and comparing it to my current version  + testing AIs of the creatures, i found some more interesting details. 

Legionnair not wearing torchs (had to change creature_addon b2_0_sheath to 1)
Legionnair AI:
This one is a bit complicated and i cant rly test this solo on retail. Currently Legionnair only uses Pummel when his Main target (mostly the tank) uses a Spell to interupt it.
If i remember right, Creatures that can interupt with spells, check for all players that cast a spell (in spellrange) and interupt them.
For example with Pummel (melee range) he should check for all players in melee range and interupt them.
https://youtu.be/gXn7HRgYe1c?t=115
That was from corecraft but i can remember that this worked on retail just like this.

**Comment by al3xc1985** [comment]
u should open a new issue for the ai problems

**Comment by miraco** [comment]
Before i start working with the 2nd Group, here is my Idea how to script the Legionnairs behind the first group.

https://github.com/miraco/mangos-tbc/commit/5867d95b1f522282133c4dce06f596d9c117e206

This still has some place for improvments and got 2 bugs.

- Send AI Event B on Death from nearby creatures triggers all legionnairs in range, not only the "group leader" have to add a new function to creature_event_ai which sends AI_EVENT_B only to the group leader. 
- Spawned Fel Orc move to his waypoints and only gets infight when he reached the waypoint not before.

**Comment by AnonXS** [comment]
baby steps please, for new additions please make a new pullrequest and maybe extract what hasnt been fixed into a new issue as this is already polluted alot and your pr wrote it resolves everything in here and ti doubt that.
