### ISSUE TITLE
💬 [Support Request]

### ISSUE THREAD

**Issue by dvdvideo1234** [cmangos/issues#2162]
## 💬 Support Request
I have all the three MaNGOS servers installed on Ubuntu 18.04. I start the classic server. Everything is OK. Then I start TBC server, the MaNGOS-D runs OK and starts loading, but the REALM-D gives:
```sh
# $drtitle is what title is runnin at the moment. Equals to "TBC"
# $scriptpath is the install location of the WoW MaNGOS server

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
./config.sh: line 79: 24551 Aborted                 (core dumped) $scriptpath/$drtitle/run/bin/realmd -c $scriptpath/$drtitle/run/realmd.conf

```
### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)
  - "2.4.3" (TBC) ( Tries to connect, but cannot enter character creation )

[CLASSIC](https://github.com/cmangos/mangos-classic/tree/e0057d4e4ec20dc74ae6c69e4e46b3047a1c0ae5)
[TBC](https://github.com/cmangos/mangos-tbc/tree/70a6147c9719f954694361e5b27315aa6dc6df97)

[CLASSIC](https://github.com/cmangos/classic-db/tree/1af850629e2ad04fb84daf723d172495893a9563)
[TBC](https://github.com/cmangos/tbc-db/tree/99a366bf04f002349f7385f799844fb99dbfc7e9)

Operating System:  Linux mangos-vb 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce
1. Install CLASSIC on a machine
2. Install TBC on the same machine
3. Start mangos/realm of CLASSIC
4. Start mangos/realm of TBC
5. Realm executable for TBC raises the error and stuck in a loop

**Comment by dvdvideo1234** [comment]
It seems this some kind of a port is already being used for another application error of Linux. So how can I fix that ?

**Comment by Muehe** [comment]
You need to change the ports in your config files. Defaults are 8085 for mangosd and 3724 for realmd. However only one instance can use the same port at the same time. So change the ports for your TBC server and add the new realm server port to the address in the TBC clients `realmlist.wtf`.

**Comment by evil-at-wow** [comment]
> Start mangos/realm of CLASSIC
> Start mangos/realm of TBC

This is the root of your problem. Realmd needs to run on port 3724 because that's what the client expects, and you can't run both processes with the same port. But fortunately that's not needed, because you can run _one_ realmd for different worlds, even from different expansions. Just put the different worlds in the database for one realmd.

Also, as @Muehe says, you need to run different world servers on different ports (set in the config, but also in the realmd database), but it sounds like you already do that.

**Comment by dvdvideo1234** [comment]
@evil-at-wow  @Muehe 

Yes I know, it is limitation if the Linux OS in general. It is very common problem to support only one port running multiple applications binded to it. I can change the ports, but my problem is rather if the client will `magically know` that that the server is not in `3724` but `3725`. I do recall `WoW.exe` searching for realms on port `3724` in general. 

How do I tell the client that the TBC realm is on `3725`, is this value being hardcoded in `WoW.exe`
I can run one Classic world at `8085` and one TBC world at `8086` and one WOTLK world at `8087`. It seems possible as I cannot change the way the client expects `3724`, but how do I know it will still expect `8086` and `8087` for the TBC/WOTLK as these are not the standard ports. Are they hardcoded in `WoW.exe` ?

**Comment by Warlockbugs** [comment]
You can add port to the realmlist address like this: `SET realmList "127.0.0.1:3725"`

**Comment by dvdvideo1234** [comment]
@Warlockbugs 

Oh, nice. I never expected that supports ports... Let me try with only one realm ( the one for wotlk ) . See you in a bit.

**Comment by dvdvideo1234** [comment]
Hello, @Warlockbugs 

The client stays on `Connecting` both TBC and WOTLK. Classic is not yet modified in terms of ports.

What I did

Open service ports `TCP/UTP 3725, 3726, 8086, 8087` in the router.

What I tried:

TBC: 
```
realmd.conf/RealmServerPort = 3725
mangosd.conf/WorldServerPort = 8086
mysql/tbcrealmd.realmlist.port = 8086
WoW2.4.3(8606)/realmlist.wtf -> set realmlist "<PUBLIC_IP>:3725"
WoW2.4.3(8606)/realmlist.wtf -> set realmlist "<PUBLIC_IP>:8086"
```

WOTLK:
```
realmd.conf/RealmServerPort = 3726
mangosd.conf/WorldServerPort = 8087
mysql/wotlkrealmd.realmlist.port = 8087
WoW3.3.5(12340)/Data/enUS/realmlist.wtf -> set realmlist "<PUBLIC_IP>:3726"
WoW3.3.5(12340)/Data/enUS/realmlist.wtf -> set realmlist "<PUBLIC_IP>:8087"
```

How data stays in mySQL:
```sql
mysql> select port from tbcrealmd.realmlist
       union all
       select port from wotlkrealmd.realmlist;
+------+
| port |
+------+
| 8086 |
| 8087 |
+------+
2 rows in set (0.00 sec)
```

**Comment by evil-at-wow** [comment]
You should only have the ports for realmd in your WoW config files. So the tests with ports 8086 and 8087 above are expected not to work properly. The WoW client _always_ connects to realmd first to authenticate ("log in"). If that succeeds, realmd sends your WoW client a list of realms it knows about. This list of realms contains IP addresses (I don't remember by heart if you can use hostnames) and ports for the world server associated with those realms (mangosd in your case).

So it's not just the port that is important in those realmlist DB tables, but also the IP addresses! These should always be your *public* IP address, because the client needs to be able to connect to those. Be careful though, you can't assume you can always connect to your public IP from a machine on your own LAN (while people outside of your LAN typically can).

Also, it's probably useful to verify in the realmd logs (or on the realmd console if you have that) that you can successfully log in, so you know that at least you get passed that stage.

**Comment by dvdvideo1234** [comment]
Gotta test tomorrow. Thanks.

**Comment by dvdvideo1234** [comment]
@evil-at-wow 

Hello, as expected reverting TBC and wotlk world server ports to 8085 results in

```sql
mangos>terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
./config.sh: line 79: 11245 Aborted                 (core dumped) $scriptpath/$drtitle/run/bin/mangosd -c $scriptpath/$drtitle/run/mangosd.conf -a $scriptpath/$drtitle/run/ahbot.conf
[CMaNGOS TBC World server v0.18] id(1) port(8085)
```

**Comment by evil-at-wow** [comment]
That is expected indeed. But note I didn't suggest to revert the world server ports; I just pointed out that connecting your client to the world server ports won't work.

But let's take this step by step. For now, let's focus on getting a TBC and WoTLK server up with a separate realmd for each world server (this is not strictly necessary, because a single realmd can be set up to provide a realm for TBC and a realm for WoTLK, but let's keep things simple for now).

So practically speaking, this means starting with the following settings:
* TBC realmd.conf uses ```RealmServerPort = 3724```.
* WoW 2.4.3 (8606) client's realmlist.wtf can use the default port, so ```set realmlist <your public IP>```.
* TBC mangosd.conf uses ```WorldServerPort = 8085``` and ```RealmID = 1```.
* TBC MySQL realmd.realmlist uses ```id = 1, address = <your public IP>, port = 8085```.

Now start the TBC realmd and mangosd (just those), and verify that you can log in and see a character screen. If that doesn't work, something's wrong and you should get that fixed first! If you run the client on a PC on your LAN, it's possible you can't connect to your public IP from a machine on your LAN (that's not unusual). In that case, and assuming you still want people from outside of your LAN to play on your server as well, you'll need to use a hostname for your public IP (if you don't have one registered, you can use a free service such as [Duck DNS](http://duckdns.org)). If you have a hostname, make these changes and try again:
* WoW 2.4.3 (8606) client's realmlist.wtf uses the hostname that resolves to your public IP, so ```set realmlist <your hostname>```.
* TBC MySQL realmd.realmlist uses ```id = 1, address = <your hostname>, port = 8085```.
* Machines on your LAN need to resolve that hostname to an IP address on the LAN (the IP of the machine running mangosd)! If you don't have your own DNS, just add an entry to your machine's ```/etc/hosts``` file that maps the hostname to the private IP of the machine running mangosd (127.0.0.1 if it's the same machine).

Assuming your TBC server now works correctly, continue with a similar setup for the WoTLK server:
* WoTLK realmd.conf uses ```RealmServerPort = 3725```.
* WoTLK 3.3.5 (12340) client's realmlist.wtf has to specify both host and port, so ```set realmlist <your public IP>:3725``` (or replace the public IP with a hostname).
* WoTLK mangosd.conf uses ```WorldServerPort = 8086``` and ```RealmID = 2``` (you can use 1 as ID here as well, but by using a different ID compared to the TBC ID we're already preparing to have the different realms served by a single realmd).
* WoTLK MySQL realmd.realmlist uses ```id = 2, address = <your public IP>, port = 8086``` (or replace the public IP with a hostname).

This should also work now, even while your  TBC server is running.

If you're going to use hostnames, the important point is that resolving a hostname should always result in an IP address that allows you to connect to the server running mangosd. For machines outside of your LAN, that is always your public IP. For machines on your own LAN, that could be your public IP, depending on your network setup, but it usually needs to be a private IP.

**Comment by dvdvideo1234** [comment]
@evil-at-wow 

Hello,

I opened all ports as you said and set unique ID for every realm in a dedicated port. I started CLASSIC and TBC. The CLASSIC server has all its default settings, TBC are changed 2/3735/8086. 
The CLASSIC server accepts client connections just fine (realmlist cannot be changed), but the TBC one fails though it accepts when I give it a port. [Config.txt](https://github.com/cmangos/issues/files/4474441/Config.txt)

See below:
```sql
Opened ports:

Router:
3724-3726	ALL	Enabled	Modify Delete
8085-8087	ALL	Enabled	Modify Delete

NAT:
3724-3726	ALL	Enabled	Modify Delete
8085-8087	ALL	Enabled	Modify Delete

CLASSIC
./classic/run/mangosd.conf:72:WorldServerPort       = 8085
./classic/run/mangosd.conf:65:LoginDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;classicrealmd"
./classic/run/realmd.conf:115:LoginDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;classicrealmd"
./classic/run/mangosd.conf:66:WorldDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;classicmangos"
./classic/run/mangosd.conf:67:CharacterDatabaseInfo = "127.0.0.1;3306;mangos;mangos;classiccharacters"
./classic/run/realmd.conf:118:RealmServerPort       = 3724
./classic/run/mangosd.conf:62:RealmID               = 1

TBC:
./tbc/run/mangosd.conf:72:WorldServerPort           = 8086
./tbc/run/mangosd.conf:65:LoginDatabaseInfo         = "127.0.0.1;3306;mangos;mangos;tbcrealmd"
./tbc/run/realmd.conf:115:LoginDatabaseInfo         = "127.0.0.1;3306;mangos;mangos;tbcrealmd"
./tbc/run/mangosd.conf:66:WorldDatabaseInfo         = "127.0.0.1;3306;mangos;mangos;tbcmangos"
./tbc/run/mangosd.conf:67:CharacterDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;tbccharacters"
./tbc/run/realmd.conf:118:RealmServerPort           = 3725
./tbc/run/mangosd.conf:62:RealmID                   = 2

WOTLK:
./wotlk/run/mangosd.conf:72:WorldServerPort         = 8087
./wotlk/run/mangosd.conf:65:LoginDatabaseInfo       = "127.0.0.1;3306;mangos;mangos;wotlkrealmd"
./wotlk/run/realmd.conf:115:LoginDatabaseInfo       = "127.0.0.1;3306;mangos;mangos;wotlkrealmd"
./wotlk/run/mangosd.conf:66:WorldDatabaseInfo       = "127.0.0.1;3306;mangos;mangos;wotlkmangos"
./wotlk/run/mangosd.conf:67:CharacterDatabaseInfo   = "127.0.0.1;3306;mangos;mangos;wotlkcharacters"
./wotlk/run/realmd.conf:118:RealmServerPort         = 3726
./wotlk/run/mangosd.conf:62:RealmID                 = 3


select id, address, name, port, realmbuilds from classicrealmd.realmlist union all
select id, address, name, port, realmbuilds from tbcrealmd.realmlist     union all
select id, address, name, port, realmbuilds from wotlkrealmd.realmlist;
+----+-------------+----------------+------+-----------------+
| id | address     | name           | port | realmbuilds     |
+----+-------------+----------------+------+-----------------+
|  1 | <PUBLIC_IP> | Yoda's CLASSIC | 8085 | 5875 6005 6141  | --> No options for ralmlist.wtf
|  2 | <PUBLIC_IP> | Yoda's TBC     | 8086 | 8606            | --> set realmlist <PUBLIC_IP>:3725
|  3 | <PUBLIC_IP> | Yoda's WOTLK   | 8087 | 12340           | --> set realmlist <PUBLIC_IP>:3726
+----+-------------+----------------+------+-----------------+
```

**Comment by dvdvideo1234** [comment]
@evil-at-wow  P.S. I make a DNS `yodawow-bg.duckdns.org`  to point to my <PUBLIC_IP> and update the CLASSIC client to `set realmlist yodawow-bg.duckdns.org:3724` as expected it does not work. I change the CLASSIC client to `set realmlist <PUBLIC_IP>:3724` Now works. The problem is not my network. Maybe it's this DNS.

**Comment by evil-at-wow** [comment]
The settings you posted earlier seem fine, assuming machines on your LAN can access your public IP (typically called 'NAT reflection').

> the CLASSIC client/mangos(sql) to set realmlist yodawow-bg.duckdns.org:3724 as expected it does not work.

I agree that's kind of expected with a standard DNS lookup. What it suggests is that _on the machine that runs the clients_, yodawow-bg.duckdns.org does not resolve to an IP you can connect to (so not to a private IP on your LAN).

You could (temporarily) try to fix this DNS resolve for clients by using your hostname again (in both the clients config and in the databases) and then adding a line to your /etc/hosts on the machine that runs the clients:
 ```<IP of your WoW server on the LAN> yodawow-bg.duckdns.org```

> I change the CLASSIC client/mangos(sql) to set realmlist <PUBLIC_IP>:3724 Now works.

This is a bit unexpected for me, because I would expect this to be the same as the case above (so not working). It seems to suggest that yodawow-bg.duckdns.org resolves to a different IP than your public IP, which is good from inside the LAN, but apparently not to the same IP that you typed in this case. Strange.

I'm also unsure why the Classic client works with the set realmlist <PUBLIC_IP>:3724 and the TBC/WoTLK client do not... did you by any chance do port forwarding only for the Classic ports on the router to the server machine on the LAN (and not for the TBC/WoTLK ports)?

Here on my machine, yodawow-bg.duckdns.org resolves to an IP address in the public range ("a machine on the internet"), so that looks good for people outside of your LAN. Now if you run ```dig yodawow-bg.duckdns.org``` on the machine running the clients (or just a ping if you don't have dig), what IP does it mention? Does it also say 85.187.x.x? Or something in the private range like 10.x.x.x or 192.168.x.x or whatever private range your LAN uses? If it's the 85.187.x.x address and it's not working, that means you don't have working NAT reflection, so you should probably make changes to make sure it resolves to an IP on the LAN for machines on the LAN (via /etc/hosts or an entry in your internal DNS if you have one, etc). This is what's typically called 'split DNS' (meaning a given hostname resolves to a different IP depending on whether you resolve it inside or outside your LAN).

**Comment by dvdvideo1234** [comment]
@evil-at-wow 

Hello, I finally had time to work on the WoW servers again and here is what I have found:

The ports opened in the router:
![image](https://user-images.githubusercontent.com/9112662/80302965-eb9d3400-87b5-11ea-92de-559eb444b8da.png)

In the NAT i have:
![image](https://user-images.githubusercontent.com/9112662/80303061-931a6680-87b6-11ea-9557-2c1c06084b4f.png)

But in the Ubuntu firewall i have inserted automatically the default ports for WoW
```
1119 (v6)                  ALLOW       Anywhere (v6)
1120 (v6)                  ALLOW       Anywhere (v6)
3724 (v6)                  ALLOW       Anywhere (v6)
4000 (v6)                  ALLOW       Anywhere (v6)
6112 (v6)                  ALLOW       Anywhere (v6)
6113 (v6)                  ALLOW       Anywhere (v6)
6114 (v6)                  ALLOW       Anywhere (v6)
8085 (v6)                  ALLOW       Anywhere (v6)
```

**Comment by dvdvideo1234** [comment]
The port settings were missing as port range in UFW
```
3724:3726/tcp              ALLOW       Anywhere
3724:3726/udp              ALLOW       Anywhere
8085:8087/tcp              ALLOW       Anywhere
8085:8087/udp              ALLOW       Anywhere
3724:3726/tcp (v6)         ALLOW       Anywhere (v6)
3724:3726/udp (v6)         ALLOW       Anywhere (v6)
8085:8087/tcp (v6)         ALLOW       Anywhere (v6)
8085:8087/udp (v6)         ALLOW       Anywhere (v6)
```

**Comment by evil-at-wow** [comment]
Good to hear the mystery has been solved!
