### ISSUE TITLE
🐛 [Bug Report] Core crashes on start with segfault

### ISSUE THREAD

**Issue by ykslol** [cmangos/issues#2177]
## 🐛 Bugreport

Server crashes with segfault while loading.
DBC extracted from normal, not custom, EN client

While debug we truncated in tbc_db  all creature_ai_* tables, and mangosd started properly.
We also have full coredump file.
server folders structure:
```
root@ha-world_cc29ba1d:/opt/mangos# ls
Cameras  bin  dbc  etc  logs  maps  mmaps  vmaps
```
DataDir = ".."

### Expected behavior
Server should starts properly_)

### Version & Environment
Client Version:  "2.4.3" (TBC)
CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/031b4e7c)
Database Repo & Commit Hash:  [TBC](https://github.com/cmangos/tbc-db/tree/73590c8b)
```
Boost: 1.62.0
OpenSSL: 1.1.0l
gcc (GCC) 7.3.0
mysql Ver 15.1 Distrib 10.1.44-MariaDB, using readline 5.2
build line:
- /usr/local/cmake/bin/cmake ../
        -DCMAKE_INSTALL_PREFIX=world/
        -DBUILD_GAME_SERVER=1
        -DBUILD_LOGIN_SERVER=0
        -DBUILD_EXTRACTORS=0
        -DPCH=0
        -DBUILD_PLAYERBOT=0
        -DDEBUG=1

runing under docker image ubuntu:18.04 - kernel 4.4.0-174-generic
In discord decided, that it is not docker issue.
```
-->
Operating System: Linux Flavor

### Steps to reproduce
1. Build mangosd from commit above
2. Install tbc-db via Installer from commit above
3. Start mangosd
4. Get crash in ~10 second while mangosd starting

### Crashlog
https://gist.github.com/ykslol/71428b8d00f2718037e11f5f94c0dc8d

**Comment by evil-at-wow** [comment]
The problem seems to be a non-existing spell.

```(gdb) bt
#0  0x0000000000e0fc73 in SpellEntry::HasAttribute (this=0x0, attribute=SPELL_ATTR_EX_CANT_TARGET_SELF)
    at core/src/game/Server/DBCStructure.h:956
#1  0x000000000124474c in CreatureEventAIMgr::LoadCreatureEventAI_Scripts (this=0x6e2b8e0)
    at core/src/game/AI/EventAI/CreatureEventAIMgr.cpp:1099
```
Note the "this=0x0" in frame 0 here (so a nullptr). The calling code in CreatureEventAIMgr is doing this (lines 1098/1099):
```
SpellEntry const* spellInfo = sSpellTemplate.LookupEntry<SpellEntry>(temp.action[j].cast.spellId);
if (spellInfo->HasAttribute(SPELL_ATTR_EX_CANT_TARGET_SELF))
    data.friendlyHp.targetSelf = false;
```
It's clear that if that spellId in the database action leads to a spell that isn't found, LookupEntry will return a nullptr and the next call will be dereferending the nullptr and crash the application.

Any chance that you can tell us the problematic spellId? If you reproduce the crash again, go to the frame with CreatureEventAIMgr::LoadCreatureEventAI_Scripts in your debugger (frame 1 in your crash log), and print ```temp.action[j].cast```. So next to ```bt```, also do ```f 1``` (1 or whatever number has CreatureEventAIMgr::LoadCreatureEventAI_Scripts) and ```p temp.action[j].cast```. Especially spellId is of interest of course.

**Comment by ykslol** [comment]
im so sorry about this wrong issue. My mistake. I did not properly initialized on new stage db DBC data. So thi is the reason why there was no spell. Thank u for investigation. I will be more careful in the future
