### ISSUE TITLE
🐛 [Bug Report] Creatures summoned >30 yards from target will automatically exit combat

### ISSUE THREAD

**Issue by Valkirie** [cmangos/issues#2184]
## 🐛 Bugreport
Creatures summoned further than 30.0f yards away from combat target will exit combat once they reach target due to distance with spawn point.

### Expected behavior
Summoned creatures with forced AI()->AttackStart(target) should not leave exit combat once they reach target.

### Version & Environment
Client Version: "2.4.3" (TBC)
CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/master

### Steps to reproduce
1. Go discuss with "Apprentice Mirveda" (entry: 15402)
2. Start quest "Unexpected Results" (entry: 8488)
3. Let summoned creatures reach Mirveda.
4. See them running back to spawn point.

**Comment by cyberium** [comment]
Fixed

**Comment by al3xc1985** [comment]
where?

**Comment by AnonXS** [comment]
Can we please start linking commits again, this is not exactly good form.

**Comment by cyberium** [comment]
When step to reproduce are correctly put like here its easy to try to reproduce and its what i did and i can confirm that its not reproducible anymore. The code since this issue changed a lot especially around the place where this is handled.
Just try it and unconfirm me if iam wrong but you have to know that i have tested it before i closed it ;)
I even had to level up until level8 because .q add 8488 did nothing for me :/. Look like there is a prerequisite.

**Comment by Valkirie** [comment]
I think that was a leash issue here.

**Comment by al3xc1985** [comment]
ty guys
