### ISSUE TITLE
Can't activate gm on in one circumstance

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2201]
If you type .GM ON you will see a message that you need to use value on or off... the gm on state can't be activated if you use upper case GM ON or GM OFF ..

**Comment by Warlockbugs** [comment]
Any chat command that accepts "on" or "off" literal args is now case-insensitive since:
https://github.com/cmangos/mangos-classic/commit/581b4da5fa40e669439e456d3fd64dd5dbbd52b1
https://github.com/cmangos/mangos-tbc/commit/d40d13302b3e1df8a3a93931e4db141e423a03d2
https://github.com/cmangos/mangos-wotlk/commit/afdd9168f8b15c12330556793aa8c226968b9e1d
