### ISSUE TITLE
🐛 [Bug Report] NPCs bugging indoors

### ISSUE THREAD

**Issue by craftorix** [cmangos/issues#2252]
## 🐛 Bugreport

NPCs are bugging through the door ceiling indoors. This especially likes to happen at the end of a door.

![WoWScrnShot_091320_001114](https://user-images.githubusercontent.com/70746948/93005946-d0f60c80-f556-11ea-8bc3-2c63633d8a9e.jpg)
![WoWScrnShot_091320_001109](https://user-images.githubusercontent.com/70746948/93005947-d18ea300-f556-11ea-9350-4955ce3accc8.jpg)
![WoWScrnShot_091320_001113](https://user-images.githubusercontent.com/70746948/93005948-d18ea300-f556-11ea-86df-0a5e4ea281d8.jpg)
### Expected behavior

They shouldnt glitch through the ceiling and get hyperactive 

### Version & Environment

Client Version: 

3.3.5a

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-wotlk/commit/95925d05964e5413cd74a0942515e3c27e5b4f0d

Database Repo & Commit Hash: 

https://github.com/cmangos/wotlk-db/commit/0ff9f2b76b21446f0b477621433da7ee8f8c20f5

Operating System: 
Windows 10
### Steps to reproduce
1. At best create a dwarf
2. Go to Anvilmar
3. Watch the patrolling Anvilmar Mountaineer gltiching through the ceiling
4. ...
5. Profit
6. Thinking about the cause of this issue
7. Trying to fix the issue

### Crashlog

- None

**Comment by AnonXS** [comment]
This was/is actually a global issue revolving around movegens/mmaps, not due to faulty db movement data, so if this stuff still happens at other locations like 

Object GUID is: Creature (Entry: 2346 Guid: 16164) DBGuid: 16164
Object GUID is: Creature (Entry: 2345 Guid: 16127) DBGuid: 16127

when they move through below the iron door, then some core commit is still missing, if not all good.

**Comment by Grz3s** [comment]
easy fix is to add 1 extra wp point .. exact under that door frame... and problem is gone
but yes it may req. more precise mmaps
