### ISSUE TITLE
🐛 [Bug Report] I cannot respawn bosses in naxx for raid practice.

### ISSUE THREAD

**Issue by moufpiece** [cmangos/issues#2293]
.respawn does not work, help

**Comment by MantisLord** [comment]
Unfortunately, I believe this is by design. When you kill a boss, you get saved to the raid instance. The core won't let you ".respawn" a boss/encounter which has already been completed in a raid.
You have a few options to get around this... you can zone out and use a command like ".instance unbind all" to reset your character's lockouts.
If you absolutely don't want to reset the raid, you could use ".npc add [id]" to spawn a second copy of the the boss you want to fight again. Keep in mind you might get some unexpected behavior if you go this route though. Some bosses aren't designed to have a second copy spawned on the fly like that and mechanics might not work the same way. So the best way is just to reset the instance/raid lockout.
