### ISSUE TITLE
🐛 [Bug Report] Compilation Error: ‘std::function’ has not been declared

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#2304]
## 🐛 Bugreport
Can't compile cmangos tbc server

### Expected behavior
Compile without errors

### Version & Environment
  Client Version:
  - "2.4.3" (TBC)

  Commit Hash:
  - [TBC](https://github.com/cmangos/mangos-tbc/tree/6d3fdf9752a8e59d177e91dbde42ddff8eefc93e)
 
 Database Version:
  - [TBC](https://github.com/cmangos/tbc-db/tree/e1d76aa76b235eea9665779bd0f3ca442632e93b)

Operating System: 
Linux Debian10 with MariaDB

### Steps to reproduce
1. git clone mangos-tbc and tbc-db
2. mkdir build cd build
3. cmake .. -DCMAKE_INSTALL_PREFIX=\../run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=1 -DBUILD-PLAYERBOT=OFF -DBUILD-AHBOT=OFF
4. make

### Crashlog
root@toriel:/home/splocinski/wow/mangos-tbc/build# make
[  1%] Built target detour
[  3%] Built target recast
[  3%] Built target gsoap
[  4%] Built target mpqlib
[ 11%] Built target g3dlite
[ 11%] Built target framework
[ 15%] Built target shared
[ 15%] Building CXX object src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o
In file included from /home/splocinski/wow/mangos-tbc/src/game/AI/BaseAI/CreatureAI.h:22,
                 from /home/splocinski/wow/mangos-tbc/src/game/AI/BaseAI/CreatureAI.cpp:19:
/home/splocinski/wow/mangos-tbc/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/splocinski/wow/mangos-tbc/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:63: src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:628: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by evil-at-wow** [comment]
Confirmed. I was about to ask for some details of your system, because I'm not seeing this issue on my own system, and we're also not seeing this issue on our TravisCI jobs, but I had a look at the code anyway to see where &lt;functional&gt; (the header needed for std::function) should be coming from, and it's indeed missing. :astonished: 

So of course I was wondering why the core builds on my system (and on the CI), and it turns out it's actually working for us because of what I'd call a side effect. This is the #include stack on my system from CreatureAI.cpp to &lt;functional&gt; where each header listed is included by the one below:

```
#include <functional>
#include <thread>
#include "Threading.h" (src/shared/Threading.h)
#include "Common.h" (src/shared/Common.h)
#include "ObjectRegistry.h" (src/framework/Dynamic/ObjectRegistry.h)
#include "Dynamic/FactoryHolder.h" (src/framework/Dynamic/FactoryHolder.h)
#include "AI/BaseAI/UnitAI.h" (src/game/AI/BaseAI/UnitAI.h)
#include "AI/BaseAI/CreatureAI.h" (src/game/AI/BaseAI/CreatureAI.h)
```

So it basically turns out we get the &lt;functional&gt; include "by accident" by including &lt;thread&gt;! A quick experiment on [Compiler Explorer](https://godbolt.org/) shows this is indeed working with GCC versions prior to GCC 7, so the GCC team has likely changed their thread header in later versions and it no longer includes &lt;functional&gt;.
I'm not entirely sure why the Travis CI builds worked out OK, as they are using GCC 7.5, but I'm guessing that could be because of patches by the Ubuntu team or something. 

Either way, it doesn't matter much, because the root of the problem is something we're doing wrong. Fix incoming!
