### ISSUE TITLE
🐛 [Bug Report] add dbc locale 8 support

### ISSUE THREAD

**Issue by shikulja** [cmangos/issues#2311]
## 🐛 Bugreport
Even if parameter DBC.Locale = 8 is used in mangosd.conf, and loc8 is present in the database.

![Снимок экрана 2020-11-10 143137](https://user-images.githubusercontent.com/3386359/98668905-9dbad880-2361-11eb-9373-7eb358e09da1.png)

All the same, the server does not detect, and sets loc0

![Снимок экрана 2020-11-10 143226](https://user-images.githubusercontent.com/3386359/98668916-a0b5c900-2361-11eb-8662-1721dd5864c0.png)

### Expected behavior
https://github.com/WoWruRU/classicdb_ruRU/blob/master/cmangos_ruRU_support.patch

### Version & Environment
:
  - i see only on "1.12.1" (CLASSIC), but most likely necessary for the rest
officially, support for the Russian language appeared only in tbc 2.4.3, perhaps the reason is this.

Server.log
2020-11-10 14:13:19 ERROR:Incorrect DBC.Locale! Must be >= 0 and < 8 (set to 0)
2020-11-10 14:13:19 Using enUS DBC Locale as default. All available DBC locales: enUS

**Comment by killerwife** [comment]
@Warlockbugs this is your territory.

**Comment by shikulja** [comment]
There was no support in mangos back in 2011, it has been 10 years, but it has not appeared.
This imposes many restrictions, with manual compilation of new assemblies each time, instead of using the ready-made one.

**Comment by Warlockbugs** [comment]
There is no official ruRU localization for any version below 2.4.0. Adding an unsupported locale into the game requires patching the game executable or the memory during runtime, because all possible locale paths are hardcoded into the client and all related DBC and interface files are digitally signed. This puts it into custom content territory, and a custom client requires a custom server, so not supporting it within the scope of CMaNGOS is fair.

A non-destructive way to have a custom locale would be using UI string manipulation addon like RuWoW, which translates only the interface during runtime, leaving original files be. However, someone in the russian vanilla community (i suspect ex-Valkyrie players) thought it was an outdated concept and started promoting what is essentially a hacked client. 

We can revisit this topic if we eventually move to supporting modern 1.13.x clients, which do have much more locales out of the box than 1.12.x.

**Comment by shikulja** [comment]
@Warlockbugs 
Yes ru the client was made by the fan community, to support the language that was added only later, just like cmangos was created in the interests of preserving content that Blizzard stopped supporting, in the interests of promoting new add-ons.
since the current server-side code already knows how to use all the official localizations, you just need to open the possibility of using loc8 at the discretion of those who need it, and will not have any impact on others.
elysium has nothing to do with the cmangos command, I think so, but it's a great example that anything is possible
...
Best regards to the team.

**Comment by Warlockbugs** [comment]
There are 8 locale fields in 1.12.x and 16 locale fields in 2.4.3 and 3.3.5a. While some of them are unused, unfortunately, every possible locale has to be hardcoded with an id and matching string to work at every stage: resource extraction, database loading, DBC loading, client auth, etc.
This is where we hit the problem of custom content: we have to know in advance in the code which string matches an id and vice versa. There is no perceived solution to reduce amount of work required to use custom locales with CMaNGOS, so if someone wishes to use a custom client, the best bet is still maintaining own fork of codebase with custom locale hardcoded in.

**Comment by shikulja** [comment]
The continuity of identifiers in wow (vanilla-tbc-lk-etc) of items of spells and other things was normal, quite logical.
If used the other way around, it would be perfectly fine.
