### ISSUE TITLE
🚀 [Feature Request] Scourge Invasion 1.11

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#2313]
Scripting of event https://wow.gamepedia.com/Scourge_Invasion

Implement attacks throughout azeroth in 6 zones over the old continent.

Revise loot lists and add vendors which sell event specific items.

Capital city invasions for Stormwind and Undercity.

Event specific bosses in several instances like Scarlet monastery and more.

Utilize Game Event system akin to War Effort for spawns. (thread safety is important)

Optional: Implement it in a way thats extensible for mango-wotlk with the second invasion.

**Comment by killerwife** [comment]
Placed a $60 USB bounty on this issue as per me and my team. https://www.bountysource.com/issues/94257116-feature-request-scourge-invasion-1-11

**Comment by killerwife** [comment]
Clarification on closing this issue, two people need to approve this after review. Both core and DB component.

**Comment by cala** [comment]
Though I would love to see this in-game event completed as much as everyone here do, I'm uneasy with the bounty.

I've only worked on scientific patents IP, not the artistic content IP used in video games so I'm not adamant on this, but I believe that giving money (or asking for money) in exchange of work that includes copyrighted material not owned the involved parties (or licenced to them), is beyond the legal line in most countries.

One would argue that the amount of money and copyrighted material is small - and I agree with that - but if one day the copyright owner decides to run a DMCA offensive similar to the one RIAA and YouTube are currently running on open source and free projects like [youtube-dl and its forks](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md), this bounty would be like a Christmas gift for their lawyers as we won't be able to protect ourselves by claiming CMaNGOS is a educational project, because someone is making profit from it.

CMaNGOS was already taken down once on GitHub by a DMCA request and we know that the copyright owner already closed at least another project in the past, so we can't pretend the risk is low or does not exist.

So, I'd very much like to know our two project admins' opinion on the matter: @xfurry and @cyberium.
