### ISSUE TITLE
🐛 [Bug Report] TBC Client crash

### ISSUE THREAD

**Issue by qutinglong** [cmangos/issues#2325]
## 🐛 Bugreport
Six players logged in from different IPS, joined the team, the players scattered to different maps, and some of the players'clients crashed or were kicked out. The more you log in, the more you crash, and the whole team gets kicked out!
But..
Six players in the same zone won't crash or kick out！
The same Ip login will not crash or kick out!

I'm sorry! My English is terrible

### Expected behavior
The client should not crash

### Version & Environment
TBC 2.4.3
Client Version: 
8606

CMaNGOS Repo & Commit Hash: 14a9fb4a34566b566e6c57eb5781a65d0afaf436

Database Repo & Commit Hash: 

Operating System: 

### Steps to reproduce
1. Six or more different I.P. players logged in
2.Join the team
3.Spread out on different maps

**Comment by canidae** [comment]
I'm experiencing the same issue (classic core) and I've noticed more people comment about similar troubles in Discord.
In our case players gets desynced or client crash if we're four people in the same party from two different public IPs (some NAT going on), but only when the players are in different zones.
I've attempted to recreate the issue locally, but it simply won't happen when all the clients come from the same IP.

As for work-around, we've found that forming the party/raid when everyone is in the same zone prevents the players from being desynced or kicked out of the game.

**Comment by qutinglong** [comment]
That's true

CMaNGOS Hash:0684836ec6726c94000b2d811d27c94bb0a2b818

This problem already exists, perhaps even earlier. Unfortunately, there is no test environment to narrow down the scope since when

**Comment by canidae** [comment]
See also: https://github.com/cmangos/issues/issues/2213

**Comment by killerwife** [comment]
I can perhaps help with diagnosing this. It would help a lot if for example on friday you would swing by the discord and let me connect to the server, and I would attempt to crash my own client.

I can use debugging software to find out why its crashing and we can kick off from there.

**Comment by canidae** [comment]
Managed to trigger the desync again (after about 30 minutes of being in a party of 4 players), but I don't know how to reliably reproduce it.
Unfortunately there doesn't seem to be anything interesting in the logs, this is the only notable entry:
`2020-11-25 20:45:25 ERROR:SESSION: received unexpected opcode MSG_MOVE_WORLDPORT_ACK (0x00DC) the player is still in world`

However, I'm not sure if it's related, due to these events before and after error:
`2020-11-25 20:44:10 Account: 6 (IP: 192.168.0.1) Logout Character:[Aïra] (guid: 1)` <-- Player went AFK, upon returning player was desynced and couldn't interact with world or log out/exit.
`2020-11-25 20:46:48 Account: 5 (IP: 192.168.0.1) Logout Character:[San] (guid: 2)` <-- Player was not AFK, wrote a message to party chat (which arrived) and was immediately desynced afterwards.
Neither of these logouts were done voluntarily.
There may also have been a third desync from a remote player (the two above were on the same network as seen by IP), but the player gave a somewhat vague explanation of "game crashed" and "couldn't log out" which sounded like a desync. Player immediately killed client so I couldn't verify if it actually was a desync.

None of the clients crashed, they were only desynced.
As mentioned earlier, this only happens when the players are in different zones. I've not seen it happen when players are in the same area. Even entering an instance at roughly the same time has so far not caused anyone to become desynced.

I'm not sure how easily this can be debugged (as opposed to a proper application crash), but you're welcome to join our server, @killerwife (I'll send you details on Discord).

**Comment by canidae** [comment]
I managed to capture data transmitted between client & server during a desync.
There were some few things I learned:
* Data sent from the desynced client (e.g. chat messages) *are* received by the server, other players could see the messages, but not the player sending them.
* Wireshark revealed that data is still sent from the server to the desynced client. Messages sent by other players were sent to the desynced client, but not displayed by the client.

This time the client actually crashed, but not immediately after the desync. Error message is probably worthless, but in any case:
![desync_crash](https://user-images.githubusercontent.com/33864/100516494-a3e3ee00-3184-11eb-9e27-9f8d1039ade3.png)

Further it seems like clients gets desynced in a "round robin" fashion. First one client desynced, relogged and joined the party. Then the second client desynced, relogged and joined. Then the third, etc. Only seen it happen in party with 4 or 5 players (raid not tested) when the players are in different zones. Not seen it happen in party of 2 or 3 players.

**Comment by killerwife** [comment]
When you are not in a party, all works k?

**Comment by qutinglong** [comment]
@killerwife MapUpdate.Threads = 0    Everything's fine！

**Comment by canidae** [comment]
I've not had a single desync when not in a party.
I will try MapUpdate.Threads=0 as well. Believe I already tested this once and still got desync issues, but it's worth a new try.

**Comment by killerwife** [comment]
I think I have the reason why its happening. Will push fix to tbc soon.

**Comment by qutinglong** [comment]
![QQ图片20201128221149](https://user-images.githubusercontent.com/3989074/100517645-107fdc80-31c7-11eb-897c-c9516c955334.png)
@canidae   
I just changed it here, in the 10 player test, constantly changing the map, there is no crash or kick again

**Comment by canidae** [comment]
Thanks, but isn't that essentially the same as just setting the config MapUpdate.Threads to 0?

**Comment by killerwife** [comment]
it is

**Comment by qutinglong** [comment]
MapUpdate.Threads  I didn't change it

**Comment by qutinglong** [comment]
@killerwife I'm sorry. I thought Mapupdate.com. Threads = 0 is the same as stripping in code

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/9aaa6dd278eb9b9b21cabcf9d503457013a8f71e

Try again.

**Comment by canidae** [comment]
With the latest changes from @killerwife I've not been able to reproduce this issue (in classic core, but same issue applies for TBC), I believe this issue can be closed.
