### ISSUE TITLE
🐛 [Bug Report] Paladins cannot refresh buff after learning Improved Blessing of Might

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2365]
## 🐛 Bugreport
After learning the Improved Blessing of Might talent, The Blessing of Might buff time is not over. If you release the Blessing of Might again, you will receive an error message: There is already a powerful spell at work.

### Expected behavior
There is no error prompt and buffs can be refreshed.

### Version & Environment
Client Version: 
2.4.3 

CMaNGOS Repo & Commit Hash: 
4585ce7281e65aa47ea0d74ee2df001804f45abb

Database Repo & Commit Hash: 
1d8526ff3139aefb4f12ae3fc9b5420bb7c1e361

Operating System: 
CentOS 7

### Steps to reproduce
1. Creating Paladin characters
2. .character level 70
3. learn Improved Blessing of Might talent
4. learn spell Blessing of Might 
5. cast Blessing of Might
6. cast Blessing of Might again

**Comment by john-redd** [comment]
Also experiencing this bug.

**Current Behavior**:
After learning the "Improved Blessing of Might" talent, attempting to recast "Blessing of Might" on a target that already has this buff results in the "There is already a powerful spell at work" error to be thrown. 

If the target dispells the buff by right clicking on it, "Blessing of Might" can successfully be cast on the target

**Expected behavior**
No error is thrown and "Blessing of Might" can be refreshed without the target first having to dispell the buff.

**Steps to reproduce**:
1. Put 1 (or 2) points in "Improved Blessing of Might" talent.
2. Cast "Blessing of Might" spell on self
3. Attempt recast of "Blessing of Might" spell on self.
4. "There is already a powerful spell at work" error is thrown.

Version & Environment
**Client version**:
3.3.5a

**Commit hash**:

**Database version**:
wotlkmangos.db_version.version = WoTLKDB v1.4+ 'WrathGate' for CMaNGOS-WOTLK 14029

**Operating system**:
Server: Ubuntu 20.04
Client: Windows 10

**Operating System**:
Client: Windows 10
Server: Ubuntu 20.04

**Additional Notes**:
There seems to be a mismatch on the client between the number shown on the target's "Blessing of Might" buff icon in the upper right hand corner, and what is shown on the tooltip in the bottom right hand corner when hovering over the spell on the Paladin's spell bar. Not sure if that is somehow related.
![Screenshot (10)](https://user-images.githubusercontent.com/54959255/119739507-95c70f80-be3f-11eb-9db9-b6747da7fa4b.png)

![Screenshot (9)](https://user-images.githubusercontent.com/54959255/119739498-91025b80-be3f-11eb-96b8-7a8230fe61aa.png)

![Screenshot (7)](https://user-images.githubusercontent.com/54959255/119739473-85af3000-be3f-11eb-89b2-dbc0b67fe8e9.png)
![Screenshot (8)](https://user-images.githubusercontent.com/54959255/119739488-8cd63e00-be3f-11eb-9ddb-6a6b90c18ab7.png)

**Comment by killerwife** [comment]
Retested, works as intended now.
