### ISSUE TITLE
[Classic/TBC] Spell hit/resist/reflect must be rolled when hit

### ISSUE THREAD

**Issue by Rockette** [cmangos/issues#237]
Actually, the roll for hit/resist/reflect is done when the spell cast end, it must be rolled when the spell hit the target.

This can be seen at http://www.youtube.com/watch?v=dxC31GliYRc

**Comment by Phatcat** [comment]
@mityada - tagging you since you just worked on reflect, and I would like to get this closed if possible.

You probably the one most on top of that part of the code currently. Is this true? I am not sure what I'm looking at in that video at all. I very well know it doesn't show a spell mid air getting reflected, it's the instant fire blast spell that is reflected.

**Comment by mityada** [comment]
@Phatcat, I see the same. Pyroblast is not reflected and damages the player, but then some instant spell is. Futhermore, the player takes damage before reflect is activated, so that video can't tell us anything about mid-air reflect.

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/1015
