### ISSUE TITLE
🚀 [Feature Request] MS visual studio versions

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#2417]
## 🚀 Feature
Hello!
Today mangos supported last version of MS visual studio and previous one.

I would like to discuss with you concept about using two versions: last one and lets say 2015 (for legacy case)
Windows versions and visual studios changes way to fast, but there are (i hope)  a lot of people with older (unsupported) OSes and a MS vs.

### Benefits & Purpose
As a POV of quest-tester: Setup vs 2015 and forget about reinstalling it.
last time i compiled server, VS 2015 has only issues with Map extractor, so (i assume) there are not that much features that never vs provided that older doesnot have.

**Comment by insunaa** [comment]
If I remember this correctly, VS2015 isn't supported because CMaNGOS uses C++14 features and CMaNGOS aims to be modern. Intentionally using outdated language features and libraries so that 5-10 year old compilers work, doesn't seem very practical to me.

Even if much of the core code of CMaNGOS stays the same, there will be library dependencies, such as a minimum of Boost 1.65.0, which might no longer work with older compilers. In addition to that: CMaNGOS is an educational project, not a commercial project that has to cater to a wide customer base.

I'm not a dev here tho, so maybe my thoughts on this are invalid. Regardless I still don't think you can expect much. Creating LTS versions of software is expensive and hard work.

**Comment by killerwife** [comment]
We try to have some backwards compatibility but we also aim to have c++17 features once they are actually needed. This is so that we can alleviate dependency on other libraries and in some cases make the code more simple and simple to use. We will definitely not be supporting VS 2015 again however. As such, closing this issue.
