### ISSUE TITLE
🐛 [Bug Report]Nefarian phase 2 bug

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2474]
## 🐛 Bugreport         

When the nefarian invokes phase 2, he cannot reach the ground. Sometimes it does land, but I don't know why.

 ![image](https://user-images.githubusercontent.com/71378304/122646256-837a8180-d11e-11eb-97c7-b18f8468888d.png)
          
### Expected behavior                      

it must land on the ground every time   
![image](https://user-images.githubusercontent.com/71378304/122647698-d0158b00-d125-11eb-90ef-31e7e60ea7c8.png)

     

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:89357fd36b174808e7ca372a13939802b91647e5                      

### Steps to reproduce                           

1. create hero level 60             
2. teleport to blackwin lair   
3. go to .go creature 85785
4. start event
5. kill all creature summon 
6. see        

### Crashlog       

- None

**Comment by insunaa** [comment]
the problem seems to be here:
![image](https://user-images.githubusercontent.com/3718129/123552064-bbb03e80-d774-11eb-807d-aa2bedecb868.png)

it's relying on a generated path for Nefarian to land, but the "landing sequence" only starts when Nefarian reaches Waypoint 8, which might not exist or might be somewhere in the air.
