### ISSUE TITLE
🐛 [Bug Report]High Priest Thekal bug no tiger form

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2477]
## 🐛 Bugreport         

when thekal dies, he does not change into his tiger form.
![image](https://user-images.githubusercontent.com/71378304/123132429-079a7500-d44f-11eb-9a00-1e29c9c45a2a.png)

          
### Expected behavior                      

When thekal dies, it must be resurrected as a tiger form, at this point he says "Shirvallah, fill me with your RAGE!".  during this phase, he can push back with Force Punch and throughout the fight, Thekal can summon two tigers.

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:89357fd36b174808e7ca372a13939802b91647e5                      

### Steps to reproduce                           

1. create hero level 60             
2. teleport to zul'gurub
3. go to .go creature 49310
4. start boss
5. see          
 
### Crashlog       

- None

**Comment by insunaa** [comment]
did you kill him with `.die` or an extreme amount of damage? Thekal is not supposed to actually die before he's resurrected, instead he'll be in a fake dead, untargetable state. Unfortunately the death prevention does not prevent `.die` or excessive amounts of damage (for some reason)

**Comment by ClassicW** [comment]
no, of course, when i test a boss, i inflict small amount of damage very quickly to simulate a raid. i don't use .die of course  
 
![image](https://user-images.githubusercontent.com/71378304/123147641-944d2f00-d45f-11eb-9efe-fba62c6ea728.png)

Also, the 2 mob next to the boss that should resurrect each other every 15 seconds, which forces the raid to kill them at the same time, doesn't work    

![image](https://user-images.githubusercontent.com/71378304/123147573-7da6d800-d45f-11eb-8804-adbb10b35363.png)

**Comment by insunaa** [comment]
I'll look into it

**Comment by insunaa** [comment]
Alright... Did some testing... Still can't quite figure out what's going wrong. The death prevention isn't working correctly. Not sure what exactly is going wrong there, but instead of the mobs going into a fake death, they go into a fake death and then immediately into real death, even tho they still have health left.
Because they transition into real death immediately, UpdateAI() is no longer called, which means any of the resurrection functionality doesn't work. I've tried to recode this to use the new SetDeathPrevention(true); paradigm, but that had no effect either. Something is making these NPCs die for real when they should only fake-die and I don't know what.

**Comment by insunaa** [comment]
Alright, that fixes it, PR is opened. Should still be re-written in CombatAI, but I really don't wanna right now

**Comment by cala** [comment]
PR merged. Thank you.
