### ISSUE TITLE
🐛 [Bug Report]heigan bug ocasionnally

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2481]
## 🐛 Bugreport         
  
heigan bugs strangely 1 out of 2 times, it does not close the door to prevent players from coming back when dead during the fight and it doesn't do the green spell that moves around the room.

![image](https://user-images.githubusercontent.com/71378304/123322561-bebcec00-d534-11eb-82c0-f43bbffbabb6.png)
![image](https://user-images.githubusercontent.com/71378304/123327994-51f92000-d53b-11eb-9d26-b6bec5149451.png)

          
### Expected behavior                       

occasionally it works properly, 
![image](https://user-images.githubusercontent.com/71378304/123324328-f9278880-d536-11eb-9416-694ced013e87.png)

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:89357fd36b174808e7ca372a13939802b91647e5                       

### Steps to reproduce                           

1. create hero level 60             
2. teleport to naxxramas
3. go to .go creature 88205
4. start boss
5. see          
 
### Crashlog       

- None

**Comment by insunaa** [comment]
Does the bug occur when pulling the boss for the first time? Or after resetting it once (by dying or using `.gm on`). Or is there no pattern you could discern when this bug occurs?

**Comment by insunaa** [comment]
OK, I found a *potential* issue, but that should only occur extremely rarely...
![image](https://user-images.githubusercontent.com/3718129/123559074-29229600-d79a-11eb-9cc9-2c7354ba252d.png)
![image](https://user-images.githubusercontent.com/3718129/123559082-30e23a80-d79a-11eb-8ae5-a1d721271514.png)
If for some reason at some point `diff` is equal to the corresponding `timer` variable, the variable would then at the end of the if statement be set to 0, because `timer-=diff` is an equation that can just coincidentally be 0.

That should only happen *very* rarely, because diffs are usually not in very regular intervals, so they can vary a lot between different `Update` calls.
