### ISSUE TITLE
🐛 [Bug Report] Battlegear of Eternal Justice not triggering with other Judgements than JOR

### ISSUE THREAD

**Issue by fatalieror** [cmangos/issues#2500]
## 🐛 Bugreport
Paladin Set Bonus 506
Spell = 26135
The Set Bonus from Battlegear of Eternal Justice is not triggering with the Judgement of the following Seals:
Seal of Command, 
Seal of Wisdom, 
Seal of Light, 
Seal of Justice

Seal of Righteousness is working. I Tried to fix it by copying the SpellFamilyMask and other flags from SOR or Judgement of Rightousness, but that didnt help.

### Expected behavior
20% chance to regain 100 mana when you cast **a Judgement.**

### Version & Environment

  - "1.12.1" (CLASSIC)

  - Win 10

### Steps to reproduce
1. Cast Seal of Command
2. Cast Judgement
-> No effect

Seal of Righteousness any Rank + Judgement = works

**Comment by ClassicW** [comment]
I confirm

**Comment by killerwife** [comment]
I will take a look soon™.

**Comment by killerwife** [comment]
Solved the issue, will export next week. Three issues. First, main judgement has newly discovered "suppress caster procs" and "suppress target procs" which make the main judgement spell not able to proc anything. Next, the set bonus was tied to this main spell and needs its spell_proc_event mask changed to correspond to all the actual judgement spells. Lastly, the actual judgement spells were TRIGGERED_OLD_TRIGGERED which suppresses procs by default. In sniff this can be seen as wrong, when a spell sends SMSG_SPELL_START, which actually means it can proc things normally, this is the case for the spellscript triggered actual judgements, like judgement of light. So I had to change it so that judgements are this special kind of scripted so that they proc things. Tested, worked, hopefully I dont forget to make that new spell_proc_event correct mask.
