### ISSUE TITLE
🐛 [Bug Report] Anticheat/Playerbots crash

### ISSUE THREAD

**Issue by wtfcolt** [cmangos/issues#2534]
## 🐛 Bugreport
When using any revisions with anticheat, summoning a bot will cause a segfault/crash.

### Expected behavior
Playerbot should be summoned.

### Version & Environment

Client Version:   - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/231421b73b6f949c5e2d7b17a85794ebe4775eb6

Database Repo & Commit Hash:  https://github.com/cmangos/tbc-db/tree/90424c0d68493d858895c9ad7a9a4ce92b076996

Operating System:  Win 10 

### Steps to reproduce
1. Compile server with playerbots
2. run server
3. use either the npc dialog or .bot command to summon a bot
4. Segfault
5. Profit

### Crashlog

- None
![image](https://user-images.githubusercontent.com/1743424/131259624-8b045bb9-b78d-49d8-9d17-b1db48d7472b.png)
![image](https://user-images.githubusercontent.com/1743424/131259630-035675ab-d231-494e-84e4-9597908110b0.png)

Side note: I tried disabling anticheat during tests with no change.

**Comment by kelbren** [comment]
Can confirm, compiled under Ubuntu,  server crashes as soon as you add a playerbot.
I also disabled anitcheat with no change.

**Comment by insunaa** [comment]
The problem isn't that anticheat is enabled, it's that a playerbot instance doesn't fully instanciate every value that would be required for the anticheat system to work. I'd guess the anticheat system is built in a way where character sessions are always looped through the anticheat library, if anticheat is disabled, it'll just wave everything through, but if anticheat is enabled it'll tack on the anticheat measures.

There's probably some object in the playerbot system that hasn't been considered for the anticheat system when it was developed, because the cmangos fork the anticheat was originally developed for does not include playerbots at all (afaik). So interactions between playerbots and the anticheat system are things that need to be looked at again, and until then playerbots will probably remain broken.

**Comment by killerwife** [comment]
I linked a commit, try it.

**Comment by wtfcolt** [comment]
Still crashing unfortunately
2021-08-29 16:11:13 Using commit hash(d32df64ee48e983b18f8299dafcdf820832732c4) committed on 2021-08-29T21:48:37+02:00

![image](https://user-images.githubusercontent.com/1743424/131264133-f4495f99-f238-40f4-96f4-298c5d64c4b2.png)

**Comment by kelbren** [comment]
confirmed crash, however,
however I changed the order of these 2 lines from:
 botSession->HandlePlayerLogin(lqh); // will delete lqh
 botSession->SetNoAnticheat()
to:: 
 botSession->SetNoAnticheat();
 botSession->HandlePlayerLogin(lqh); // will delete lqh

and bot now logs in successfully.

**Comment by wtfcolt** [comment]
@kelbren 's fix seems to work for me as well

**Comment by insunaa** [comment]
Can be closed methinks.
