### ISSUE TITLE
🐛 [Bug Report] New characters are "naked" on creation

### ISSUE THREAD

**Issue by korhaldragonir** [cmangos/issues#2561]
## 🐛 Bugreport
When creating a new character on a new account which does not have access to all Expansions (addon = 2 on wotlk). The characters starts off "naked", meaning all items are located in the backpack instead of equipped.

### Expected behavior
Expected behavior would be that the items are equipped to the character on creation as is the case for accounts with addon level 2.

### Version & Environment

Client Version: "3.3.5a (WOTLK)"

CMaNGOS Repo & Commit Hash: dfd0f9336588b3d9e9eda28abe2eddd35bae954b

Database Repo & Commit Hash: 9d25aa4eaedc78132f0bc4ec86b5de7664c6b1e2

Operating System: Linux (Ubuntu 20.04)

### Steps to reproduce
1. Created a new account with addon 0
2. Create a char (usually the first will then immediately start without items equipped)
3. Delete char
4. Set addon 2
5. Create char (all items are equipped)
6. Delete char
7. Set addon 0
8. Create char (again items are unequipped)

In some cases try 2 or 3 times. Before the bug occurs, but so far it nearly always occur on a new account created as addon = 0.

### Crashlog

- None

### Other Logs
Both logs were generated by mangosd when LogLevel = 3.

When the issue occurs - [mangos_log_issue.txt](https://github.com/cmangos/issues/files/7218311/mangos_log_issue.txt)
When the issue does NOT occur - [mangos_log_noissue.txt](https://github.com/cmangos/issues/files/7218312/mangos_log_noissue.txt)

**Comment by Nytanath** [comment]
I believe I have found a way to reproduce this somewhat reliably in WotLK:

- Create a new character.
- .go creature id 6220054
- The client will crash. This is a different bug that already has an open issue about it; we don't care about that right now.
- Without restarting the server, re-open the client and log into the same account.
- DO NOT LOG IN WITH THE SAME CHARACTER. Create a new one instead.
- The new character will probably be naked; when you try to log into it, the client will say "a character with that name already exists". The server will say "HandlePlayerLoginOpcode> Player X try to login a second char"
- Continue creating new characters. Eventually you'll get one that you can log in with. Will be naked and have the equip items in inventory. My client crashed soon after, though.

Now, I know this exploits an existing bug in WotLK, but I have seen the "new character has no equip" bug in Classic too. Maybe the root cause is the same.
