### ISSUE TITLE
🐛 [Bug Report] Invalid sending money by mail

### ISSUE THREAD

**Issue by aveolona** [cmangos/issues#2569]
## 🐛 Bugreport
Any attempt to send money through the mailbox can become a gold farm. The money attached to the letter does not diminish in the bag. For example: if you have 100 gold coins and you send someone the same 100 coins, the recipient will receive them, but they will remain in your bag too.

### Version & Environment
**Client Version:** 1.12.1 (CLASSIC) 5875 (enGB)

**CMaNGOS Repo & Commit Hash:** https://github.com/cmangos/mangos-classic & 153d18d
_Compiled today, a few minutes ago._

**Database Repo & Commit Hash:** https://github.com/cmangos/classic-db & fcd7f4c
_Loaded today, a few minutes ago._

**Operating System:** Debian 9.13 (stretch)

**Comment by insunaa** [comment]
https://github.com/cmangos/mangos-tbc/commit/d154093bdee70a919670005f87e9322e564a118a this commit is missing.

If you want to fix it in your own instance in the meantime add this in line 219 of src/game/Mails/MailHandler.cpp (you can add spaces around this line too so that it's not squished in between)
```cpp
    pl->ModifyMoney(-int32(reqmoney));
```

**Comment by aveolona** [comment]
It's works. Thanks!

**Comment by aveolona** [comment]
> UPDATE `creature` SET `DeathState` = 0 WHERE `id` IN (6177,6172);

This is it?
