### ISSUE TITLE
🐛 [Bug Report] account create

### ISSUE THREAD

**Issue by jilinge2** [cmangos/issues#2585]
### Bug Details

When I create an account，I get a message
```
mangos>account create 123 111
Table `command` have unexpected subcommand 'getvalue' in command 'debug getvalue', skip.
Table `command` have unexpected subcommand 'setvalue' in command 'debug setvalue', skip.
Account created: 123
```
Then I proceed to the second step，I get a message
```
mangos>account set addon 123 0
Account not exist:
```
I created it again, but got a message that the account exists
```
mangos>account create 123 111
Account with this name already exist!

```
Try to use other strings such as zhang as the account  `account create zhang 111`  , the creation is successful, no problem.
I can also log in to the game with account 123 and password 111, but I cannot use this account to execute `account set addon 123 0` and `account set gmlevel 123 2`

### Steps to Reproduce

1.  account create 123 111
2.  account set addon 123 0
3.  account create 123 111
4.  account create zhang 111

### Core SHA1 Commit Hash

c97f3cd322f7b63694759b9f5385420edc42dad5

### Database SHA1 Commit Hash

3db4bd042646b9521248e1e7a7d3b376b57dbf2e

### Operating System

Debian10.09

### Client Version(s)

- [X] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
I believe is somerhing wrong with using only numbers on acciunt name

**Comment by insunaa** [comment]
The issue here is that the `account set gmlevel` command allows you to specify accounts both by ID (in the database) and by account name. It first checks if you're using a number and if it is it tries to retrieve an account with that ID, in this case there is no account with ID 123, so the set gmlevel command fails.

I doubt there will be core changes regarding this issue. To avoid it simply use characters in your accountname at any point and not just a number.

**Comment by jilinge2** [comment]
Alright, thank you very much！！！
