### ISSUE TITLE
🐛 [Bug Report] Vampiric embrace

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2612]
### Bug Details

Mana gain through dmg is shown only in chat and not in combat text also

### Steps to Reproduce

1.cast
2.
3.
4.

### Expected behavior

After activatiing combat text from interface should see the mana gain from dmg on casting vampiric embrace

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Do you have any evidence for this behaviour? I'm not saying that this isn't correct, only that I know in the reference client several sources of mana-gain don't show up in the floating combat text (such as the mana you gain from Judgement of Wisdom for example) and I'm not sure if this could not be one of those

**Comment by al3xc1985** [comment]
Well as far as I saw a lot of priest mana battery videos on youtube. Classic tbc ones.

**Comment by killerwife** [comment]
Classic cannot be a source for this. I have direct proof that we are doing it correctly from 2.4.2 patch.

We send CAST_FLAG_HIDDEN_COMBATLOG - castflag 1

ServerToClient: SMSG_SPELL_START (0x0131) Length: 25 ConnectionIndex: 0 Time: 06/04/2008 13:02:52.000 Number: 13447
Caster  Unit/Player/Item  GUID: Full: 
Caster Unit/Player GUID: Full: 
Spell ID: 15290
Cast Count: 0
Cast Flags: PendingCast, HasTrajectory, Unknown3 (11)
Time: 0
Target Flags: Self (0)
unk byte 0 : 0
unk byte 1 : 0
unk byte 2 : 0

ServerToClient: SMSG_SPELL_GO (0x0132) Length: 43 ConnectionIndex: 0 Time: 06/04/2008 13:02:52.000 Number: 13448
Caster  Unit/Player/Item  GUID: Full: 
Caster Unit/Player GUID: Full: 
Spell ID: 15290
Cast Flags: PendingCast, Unknown3, Unknown7 (265)
Time: 1403800884
Hit Count: 2
[0] Hit GUID: Full: 
[1] Hit GUID: Full:
Miss Count: 0
Target Flags: Unit (2)
Target Guid: 0x0
unk byte 0 : 0
unk byte 1 : 0
unk byte 2 : 0

and we correctly send SMSG_SPELLHEALLOG which you can check with either packetlog or .debug opcodeinchistory 

ServerToClient: SMSG_SPELLHEALLOG (0x0150) Length: 20 ConnectionIndex: 0 Time: 06/04/2008 13:02:52.000 Number: 13446
Target GUID: Full: 
Caster GUID: Full: 
Spell ID: 15290
Damage: 15
Critical: False
Debug output: False

I just removed guids so I dont expose someone suddenly. If the sniffs you check with packetlog are in any way different from this, let me know. TBC has a bit of a buggy combat log because it was reworked in 2.4 and many things were fixed in 3.0.2

**Comment by al3xc1985** [comment]
U are right @killerwife .. I am closing this,,,ty for clarifying
