### ISSUE TITLE
🐛 [WOTLK] Shadowmeld Special case ~Racial~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2686]
### Bug Details

place down a snake trap, and u can stay near it, or go funther... the enemy will activate it..snake will go out...
Activate shadowmeld...in this case u are not out of combat...the enemy will attack u even thou u are invis

Case 2:

Cast Wyvern sting,,,put it to sleep...and use shadowmeld.... u will get out of combat, BUt when sleep end...he comes to attack u and put you in combat
### Steps to Reproduce

1.
2.
3.
4.
hunter

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
These are pvp cases and those works differently. Need a wotlk video to somewhat confirm what you are saying.

**Comment by al3xc1985** [comment]
very hard to find...but I should try...

**Comment by Nytanath** [comment]
> Cast Wyvern sting,,,put it to sleep...and use shadowmeld.... u will get out of combat, BUt when sleep end...he comes to attack u and put you in combat

I can reproduce a different but similar issue with Wyvern Sting:

- Aggro a mob, get it away from the spawnpoint.
- Damage it but not enough to kill it. Cast Wyvern Sting, then Shadowmeld.
Expected behavior is that the mob would lose Wyvern Sting and evade: we are out of combat and there are no other targets nearby.
Instead, the mob stays where it is, without even recovering health. Player is out of combat.
If you're still in Shadowmeld by the time Wyvern Sting expires, the mob evades. If you cancelled Shadowmeld, the mob will aggro you.
I don't recall ever seeing this kind of behavior with anything during my time on WotLK retail. Generally creatures evade when there's no target, and they lose all player-cast debuffs (tested by getting myself killed in Terokkar as a Druid, Moonfire and Faerie Fire faded on my death).

**Comment by killerwife** [comment]
Well this is indeed problematic however this would also do a similar thing on Feign Death and Freezing trap. Does it also break if you successfully exit combat with it or does the duration continue? Currently during any sort of CC all AI functions with threat list are paused. One thing I am probably clear about however, if you exit combat this way, the aura for shadowmeld should be removed from the target even if its in wyvern sting stun. I am just not so sure about wyvern sting ending :)

**Comment by Nytanath** [comment]
I'm not sure if this is what you asked, but I tested using Wyvern Sting and exiting combat with the .combat stop command - you exit combat, but re-enter it as soon as Wyvern Sting ends (this is because Wyvern Sting applies a damage over time after it ends, so it counts as re-aggroing the creature I guess).

I think creatures on CC should still evade if they have no target. I'll try on retail to Kidney Shot a mob and Vanish right after.

**Comment by Nytanath** [comment]
Behavior from Classic TBC: creatures lose CC and evade when they don't have a valid target anymore:

https://user-images.githubusercontent.com/99603810/154316355-568dba5f-a3b2-4728-ad5f-e57bb2dd3ea2.mp4

So
> Currently during any sort of CC all AI functions with threat list are paused

this doesn't seem totally correct, at the very least they should still process target validation.

**Comment by killerwife** [comment]
I have asked and if you FD during a freezing trap, freezing trap stays its duration.

**Comment by Nytanath** [comment]
> if you FD during a freezing trap, freezing trap stays its duration

That's not the case. Tested on TBC:

https://user-images.githubusercontent.com/99603810/154572161-4bc4096a-2dc6-4f2d-972c-b76a6b8403ae.mp4

**Comment by killerwife** [comment]
Ok, apparently its different on retail. Shadowmeld, FD and Mage Invis seem to all trigger evade if it was the last guy on the list even during CC. I will check out where I should adjust it later this weekend.

**Comment by Nytanath** [comment]
Yeah if a creature is in combat and loses all targets it should evade regardless of any debuffs, that's how I always understood it :P

**Comment by killerwife** [comment]
Hmmmmm.

![image](https://user-images.githubusercontent.com/7995382/154656578-9655a096-08ec-494b-b9db-47f5a30cbb68.png)

**Comment by Tobschinski** [comment]
hmmmmm

**Comment by Nytanath** [comment]
Sorry but I don't think this should be only for stuns? Disorient effects like Blind and fear/roam effects like Polymorph also let the creature evade if threat list is empty.

**Comment by Nytanath** [comment]
Polymorph:

https://user-images.githubusercontent.com/99603810/154685980-59f3d710-209c-4552-8b83-6c3302722e02.mp4

Tested on CMaNGOS WotLK, NPC does not lose Polymorph in same situation.
