### ISSUE TITLE
🐛【TBC.Server Crashed shuting down】 [Newest Bug Report] 

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [cmangos/issues#3021]
### Bug Details

Use 2022/06/19 newest core and tbc-db updated . 
Run cmangos server,  shows last alarm :   【GameEvent 1 "Midsummer Fire Festival" started.】
Server stopped .

### Steps to Reproduce

1.Git fetch and pull neweste core update ;
2.Git fetch and pull neweste tbc-db update ;
3.Cmake again, generated .
4.Commintted finish ,shows : no commit error.

### Expected behavior

should no this kind of error.

### Suggested Workaround

Game event date seems correct of this Hoilday Event . And no EAI alarms .

### Crash Log

[Crashes.zip](https://github.com/cmangos/issues/files/8934852/Crashes.zip)

### Core SHA1 Commit Hash

commit c63efea159b6d6178ba451c80952bd48ae4a9f8a

### Database SHA1 Commit Hash

e1acc3f5b83b1e92afa7829b950f161b9d36366d

### Operating System

WIN10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by jalbertcory** [comment]
I am having the same issue on my Wotlk server, however my TBC server is working fine.  The TBC server isn't trying to load the Midsummer event yet for some reason.

I was able to work around it by turning the Midsummer event off, so it's definitely the root cause.  I went into the `game_event_time` table and updated the start_time and end_time of the event (ID 1) to unix epoc.

**Comment by yuyu-lovegelin111333** [comment]
> 

I totally deleted this game event 1 . 🤓smile

**Comment by killerwife** [comment]
Use RelWithDebugInfo and run that, the crash dump sadly doesnt have any symbols loaded and I dont know what caused it. Is there any way to always reproduce it? going to a specific location, etc

**Comment by jialiang-bai** [comment]
> 

Tried this as well but it didn't work, since deletion of event 1 will also break mangos launching, events must start from entry=1 and be with a step of 1

I got a workaround, modify the start_time of event 1 in table game_event_time to a later time,  "2007-07-20 21:00:00" for instance.

Hope it'll also work on your side

**Comment by killerwife** [comment]
Events do not need to be with a step of 1 or start at 1 :) And also I cannot help with this crash until someone supplies me with a crash with debug symbols installed.

**Comment by AnonXS** [comment]
not enough info.
