### ISSUE TITLE
Hunter Talent: Improved Mend Pet

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#306]
Talent does not work; no cure is ever applied.

**Comment by HanFox** [comment]
I'd like to confirm that the spell/talent does not seem to work.

**Current behavior**: Improved Mend Pet (Rank 1 and 2) does not cure ailments. Also if pet has an ailment, but is at full health when Improved Mend Pet is cast an message will appear stating "Nothing to dispel".

**Expected behavior**: That once in a while after spamming Improved Mend Pet that a disease, curse, magic or poison effect may be removed.

**Steps to reproduce**:

1. Learn Improved Mend Pet.
2. Get your pet diseased or similar.
3. Cast Improved Mend Pet.

**Client version**: 1.21.1 (5875)

**Commit hash**: https://github.com/cmangos/mangos-classic/commit/f9abcf3304e16a74348f82a09f734f05e01e2c0d

**Database version**: https://github.com/cmangos/classic-db/commit/ff98f2a40e64939e0e3020cf8bc5a966ce477e92 (with https://github.com/cmangos/classic-db/commit/b1bd5d345bd267e7ceadb4bbf2a767bc03bed886 manually applied)

**Operating system**: Client and Server are both on Arch Linux (Client is emulated via Wine).

**Comment by al3xc1985** [comment]
@killerwife this can be closed ... working as intended
