### ISSUE TITLE
🐛 [Bug Report] Power-Checking / Recovery / Regeneration mismatched

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#3084]
### Bug Details

When trying to use Runes that are off cooldown as a DK, particularly Death Runes, you will be told that you can't use that because the runes aren't ready (even tho they are).
Similar thing happens with Rogues and Energy: The ability Sinister Strike costs 45 Energy to use, 40 with skills in the talent. Yet a rogue cannot use Sinister strike if it doesn't have at least 60 Energy (tho when it's used at 60, only 45/40 are subtracted as should be)

### Steps to Reproduce

1. Create a Rogue
2. Go to a Training Dummy
3. Cast Sinister Strike repeatedly while keeping an eye on your energy bar

### Expected behavior

Rogues should be able to use abilities that cost 45 energy as soon as they have 45 energy, Death Knights should be able to use Death Runes, as soon as they become available.

### Core SHA1 Commit Hash

95c98331406a6718f6b96fb4c78a4ffa4c86c958

### Database SHA1 Commit Hash

249dc1c18bf33ec082b524b9fb1dc4294ea699dd

### Operating System

Arch Linux

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Patrick-Barry** [comment]
I have noticed that druids are also having the same energy issue. When I run the debugger and set a break point in Spell::CheckPower it does show that the ability is failing because of not enough energy, but on the client it shows that I have enough. It seems that the client gets out of sync with how much energy the character actually has on the server. 

In my own testing I was using the druids claw ability. It was glyphed to use 35 energy. When I was at 43 energy I tried using it and got an out of energy response. I had a break point set in the debugger for when this happened and the server showed I actually only had 33 energy at the time while only needing 35 energy to activate.

Is it possible that either the client or server was set to the wrong energy regen rate? 

Wotlk commit: 0cca97a2cbad9b6f6939ee597abb231858720030
Wotlk DB commit: ba914a3ef503c4edc4ca1eb63bbafcf4d31cb6c3

**Comment by insunaa** [comment]
Not the wrong regen rate, but maybe the wrong regen tick. There is in general a pretty large latency that's not really transparent (you can see this easily if you log in with 2 accounts on the same computer, there'll be a ~1 second delay between actions you trigger (like walking, jumping, casting) becoming visible on the other client

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/commit/511170671966834235eb84224442d86ed639376a
