### ISSUE TITLE
🐛 [Bug Report] Priest and Warlock ‘s Charm，creature under controller can cast spell unlimited without GCD

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3130]
### Bug Details

Priest ‘s Mind Control  and Warlock's Enslave Demon，the mob under controll can cast mob's skill without any GCD and mana cost limit, can make a very huge dps to kill anything by himself.

### Steps to Reproduce

1.create a priest or warlock
2.mind control a creature with skill ,example in raid Serpentshrine Cavern , and mind control Coilfang Priestess(21220)
3.use the creature's skill Holy Smite attack enemy
4.watch spell icon, no GCD, No mana cost, cast unlimit

### Expected behavior

mob's effect by Charm,should cast spell with GCD

### Core SHA1 Commit Hash

3f3a2c04b47ff38a3ef615b77d3d64e715f9adca

### Database SHA1 Commit Hash

bc36ec312ce95327a981a174ed25411a1b872f85

### Operating System

unbuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Szymplo** [comment]
Hey, This is a big problem. In Mana Tombs it's possible to kill Pandemonius and Tavarok by Mind-Controlling  Ethereal Thrash within seconds. Spawning their AOE deals tons of damage and it gives players open way to exploit spirit shards and so on. Same thing with Slave Pens Sirens. It makes gameplay very unfair and makes really fast to get from lvl 62-68 by simply controlling creatures and killing everything within seconds.

Please fix it because it's "Major Bug"

Even disabling all controlled monsters abilities will be better than this.

**Comment by AnonXS** [comment]
whats the npc names so we can take priority on this matter. acid_tbc file has all the npcs that are part of this issue.

- [ ] Ethereal Theurgist 18315 ?
- [ ] Ethereal Priest 18317 ?
- [ ] Arcane Fiend 18429 ?

**Comment by Szymplo** [comment]
No Cooldown problem examples:

Mana Tombs:
Ethereal Spellbinder 18312,20260 - Summon Ethereal Wraith - U can summon army of them within seconds and that army can do Enormous damage
Ethereal Priest 18317,20257 - Holy Nova - AOE - Tons of damage 
Arcane Fiend 18429,20252 - didn't check as we didnt have Warlock in group.

Slave Pens:
Coilfang Enchantress 17961,19887 (Storms with ligthning) - Lots of AOE Storms in few seconds
Coilfang Scale-Healer 21126,21842 - Holy Nova - AOE - Tons of Damage

**Comment by Nightingale9002** [comment]
Coilfang Priestess(21220) is still a bug   spell 38582 and 38585,  it need fix too
