### ISSUE TITLE
🐛 [Bug Report] TBC Arena Season not save

### ISSUE THREAD

**Issue by ReyDonovan** [cmangos/issues#3137]
### Bug Details

no saving the event of the arena season 1, 2, 3 end etc

### Steps to Reproduce

1. .start event 53
2. .server restart 5
3. the npc that is associated with this event disappears
4.

### Expected behavior

when launching the arena seasons, we see the installed npc registrar and vendors

### Core SHA1 Commit Hash

400fd79820d0f46ff7061a3be8a5c46abc526820

### Database SHA1 Commit Hash

b47c5b3237efdf246a3efd68bc0642378babe301

### Operating System

debian 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
On a production server, this is handled via game_event and game_event_time tables.

But for 2.4.3 cmangos we should maybe think about autoactivating S4 instead of S1.

S1 by default is only active for 20 weeks, starting from the 2015-12-31 03:00:00, so its over, we should think about changing these values to 525600 default.

**Comment by AnonXS** [comment]
cmangos tbc should be perm 2.4.3, hence S4

Infos on how to adjust this in the commit below.

https://github.com/cmangos/tbc-db/commit/a6e826914b19f3ce6be920444f765406ca23abe7
