### ISSUE TITLE
🐛 [Bug Report] Some problems of Karazan

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3264]
### Bug Details

1. As long as you attack a monster, all the monsters will attack you.

![bug4](https://user-images.githubusercontent.com/3367999/208640772-4c90c939-f6ec-4516-9c98-226666f472f9.gif)

The classic version will not have this problem.
https://youtu.be/XAIrLaTOob4?t=274

2. Phantom Guardsman will not return to the right place.
![bug3](https://user-images.githubusercontent.com/3367999/208640887-f8364ad0-e4b2-4a75-a7d8-bf7b44fb14a8.gif)

3. Phantom Guest's buff has problem.
![bug2](https://user-images.githubusercontent.com/3367999/208640964-77240048-f16d-4874-8dc2-e80b32a51da7.gif)

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

7d38c3e8a91feeb97d2ec9e3ad110d5d7c911337

### Database SHA1 Commit Hash

153612cab10c07fda019d59269d1831fd83fa113

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
The phantom guardians are accurate. They're spawned within the collider of the lion statue, so on CMaNGOS the pathfinding puts them in the best reachable approximation. On the reference these phantom guards can't even be pulled, they'll stay in their position and eventually evade

The issue with the ball room is a common issue we have, which is chain-pulling due to our incomplete "call for help" implementation. call for help should only occur once on pull and only for the creature with the initial aggro, all other helping creatures should not call for help again (and should also be able to attack alone despite being in a spawn group)

The dance buff stacking is also caused by our current buff stacking issue.

**Comment by AnonXS** [comment]
1. resolved
2. linked to your high resolution maps/mangosconfig with strict z checks
3. documented in open pullrequest.
