### ISSUE TITLE
🐛 [Bug Report] 198/supplies-to-private-thorsen

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3280]
### Bug Details

You have to deliver some suppliies to 738/private-thorsen in rebell camp in north of stranglethorn vale.

But thorsen have no ? mark to finish the quest.

### Steps to Reproduce

1. start quest in Booty Bay
2. fly to rebell camp
3. go to private thorsen
4. ...

### Core SHA1 Commit Hash

3133079de45d2dc4b5a17f24dd74ea8f763c0656

### Database SHA1 Commit Hash

2023/01/17

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/issues/3222

**Comment by Ischtaratu** [comment]
ok, i see ... my fault ..

/closed

**Comment by AnonXS** [comment]
https://www.youtube.com/watch?v=-kunIaMwelY - queryed the npc default location at the fire, he always has npcflags|3 there so quest should be turnable, maybe the other quest needs condition for being taken instead?

currently only can be turned in here.

![grafik](https://user-images.githubusercontent.com/19734826/219797481-ef77dbea-6977-4a3b-a3f8-997dcb9a824c.png)

![grafik](https://user-images.githubusercontent.com/19734826/219797540-66a7b259-941e-4f91-b0e5-cb8ab969d9b8.png)

so we have to do it other way and restrict picking up 

![grafik](https://user-images.githubusercontent.com/19734826/219797781-a4da2024-6c77-43f8-ad79-9a84ca61eae8.png)

instead of hard changing his npcflags befor escort. (e.g make him only offer this quest on waypoint or xyz or idk.)

Zone: 33 (Stranglethorn Vale) Area: 33 (Stranglethorn Vale) - CONDITION_AREAID - quest offered
Zone: 33 (Stranglethorn Vale) Area: 99 (Rebel Camp) - not offered.
