### ISSUE TITLE
🐛 [Bug Report] After Akama dies, he will be reborn in place and he will not be able to talk

### ISSUE THREAD

**Issue by zhwblm** [cmangos/issues#3328]
### Bug Details

After Akama dies, he will be reborn in place and he will not be able to talk

### Steps to Reproduce

1.After Akama dies, he will be reborn in place and he will not be able to talk
2.
3.
4.

### Core SHA1 Commit Hash

c66c9c063c50da779724962285b15aae2d4053bd

### Database SHA1 Commit Hash

2b79a8e3e0c5e8039f72279442cac4898f2de12c

### Operating System

win10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
This sounds similar to what i saw when testing https://github.com/cmangos/issues/issues/3219#issuecomment-1325283418
![grafik](https://user-images.githubusercontent.com/19734826/230735952-57ff90ac-4fb3-440f-9f3b-f022dada993f.png)

```
Player selected: Creature (Entry: 23089 Counter: 5640798) DBGuid: 5640798.
npcFlags: 1.
UnitFlags: 4096 | DynamicFlags: 0 | ExtraFlags: 0
```

After Illidan kills akama, the player(s), goes into evade, he respawns in wired spot where he died.
![grafik](https://user-images.githubusercontent.com/19734826/230736066-5ace9b5c-2029-416e-a45b-471c203af143.png)
```
Player selected: Creature (Entry: 23089 Counter: 5640798) DBGuid: 5640798.
npcFlags: 1.
UnitFlags: 4096 | DynamicFlags: 0 | ExtraFlags: 0
```
should be interactable but isnt, because he is bugged out of existance and should not even respawn at that location, he has interactable mouseoverlay and npcflags but is not interactable.

Conclusion: same issue as with the other issue posted above. - (Council doors are bugged, illidan doors are bugged, illidan seems to ignore akama's dmg pretty much will go after player even when already damaged by akama alot.)

If you manually respawn him he will still respawn at this bugged position and not be interactable even if npcflags are seemingly correct.

**Comment by AnonXS** [comment]
Doors are fixed with - https://github.com/cmangos/mangos-tbc/commit/5d415652f0737e1b75c19e8eb2072f71ef201656

Akama Issue needs some more research.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/f166283450b52d715dac932813300f556cad5c97
