### ISSUE TITLE
🐛 [Bug Report] Check existing of map file './maps/5301243.map': not exist!

### ISSUE THREAD

**Issue by zjyzju** [cmangos/issues#3394]
### Bug Details

install mangos-tbc with tbc-db, and Extract file from World-of-Warcraft-2.4.3.8606-enGB Client.

But when starting mangosd, following error reported(./mangosd -c ../etc/mangosd.conf -p ../etc/playerbot.conf -a ../etc/ahbot.conf):

MySQL client library: 8.0.32
MySQL server ver: 8.0.32-0ubuntu4

Realm running as realm ID 1

Using World DB: TBC-DB 1.8.0 'Vengeance Strikes Back' for CMaNGOS-TBC
Using creature EventAI: ACID 2.4.3 (The Burning Crusades) for CMaNGOS-TBC (2.4.3 Client)

Using DataDir ./
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1
WORLD: VMap data directory is: ./vmaps
WORLD: MMap pathfinding enabled

Check existing of map file './maps/5301243.map': not exist!
Correct *.map files not found in path './maps' or *.vmtree/*.vmtile files in './vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.

### Steps to Reproduce

1. follow the instruction of install document
2.
3.
4.

### Crash Log

MySQL client library: 8.0.32
MySQL server ver: 8.0.32-0ubuntu4

Realm running as realm ID 1

Using World DB: TBC-DB 1.8.0 'Vengeance Strikes Back' for CMaNGOS-TBC
Using creature EventAI: ACID 2.4.3 (The Burning Crusades) for CMaNGOS-TBC (2.4.3 Client)

Using DataDir ./
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1
WORLD: VMap data directory is: ./vmaps
WORLD: MMap pathfinding enabled

Check existing of map file './maps/5301243.map': not exist!
Correct *.map files not found in path './maps' or *.vmtree/*.vmtile files in './vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.

### Core SHA1 Commit Hash

download on May  1 19:10

### Database SHA1 Commit Hash

download on May  1 19:10

### Operating System

ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Make sure you use the correct version of the extractors. Also check if the server has read permissions in the directory you place your map files in, check if the directory you place the files in is the correct directory that's referenced and make sure to only start mangosd / realmd from the directory that they're in, because they'll use the working directory you start them from

**Comment by AnonXS** [comment]
I get the same error sometimes for various maps, i've not been able to identify any issues related to it though.

**Comment by zjyzju** [comment]
The extractors is compiled by following command:
cmake ../mangos -DCMAKE_INSTALL_PREFIX=/opt/wow/cmangos/run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=0 -DBUILD_PLAYERBOT=ON -DBUILD_AHBOT=ON
make -j4 
make install

and I have checked the directory maps, the file is not exist:
-rw-r--r-- 1 root root 174736 May  4 12:14 5293030.map
-rw-r--r-- 1 root root 135836 May  4 12:14 5293031.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5293128.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5293129.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5293130.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5293131.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5314626.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5314627.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5314628.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5314629.map
-rw-r--r-- 1 root root 132676 May  4 12:14 5314630.map

I have tried with World-of-Warcraft-2.4.3.8606-enGB and World-of-Warcraft-2.4.3.8606-enUS, same error happened.

**Comment by insunaa** [comment]
check if all the mpq files in your wow client have the `.mpq` extension as uppercase (`.MPQ`)
The extractors may miss MPQ files with lowercase `.mpq`

The `Data` directory must also start with an uppercase `D`, not sure if the locales directory needs to be in the correct case as well, for example `enGB`, but doesn't hurt at least

**Comment by evil-at-wow** [comment]
> -rw-r--r-- 1 root root 132676 May 4 12:14 5293130.map
-rw-r--r-- 1 root root 132676 May 4 12:14 5293131.map
-rw-r--r-- 1 root root 132676 May 4 12:14 5314626.map
-rw-r--r-- 1 root root 132676 May 4 12:14 5314627.map

The ones for map 529 and 531 match what I have, but you're simply missing the entire map 530 (Outland) it seems!

Although insunaa is of course correct that correct casing is important - file names are typically case sensitive on Linux - there's almost no way this is the result of case sensitivity in MPQ file extensions or Data directory. In that case you'd be missing a lot more maps I think...

So let's try to find out where things are going wrong for you. Given you have the same issue with the enGB and enUS clients, please use World-of-Warcraft-2.4.3.8606-enUS because that's also what I have (also on Linux) so that's easier to compare. The build command seems correct at first sight, so you should have a few binaries in /opt/wow/cmangos/run/tools, including one called 'ad', correct?

Start with running the extractor ('ad') manually. Create a new folder for its output, and in a shell run a command like this (replace the two paths with the actual paths on your system):
> /opt/wow/cmangos/run/tools -i /path/to/World\ of\ Warcraft -o /directory/you/created

This is the reference output from my system that you should get:

<details>
  <summary>Reference output from ad - click to open</summary>
===================

Detected locale: enUS
Opening /path/to/World of Warcraft/Data/enUS/locale-enUS.MPQ
Opening /path/to/World of Warcraft/Data/enUS/patch-enUS.MPQ
Opening /path/to/World of Warcraft/Data/enUS/patch-enUS-2.MPQ
Extracting dbc files...
Extracted 185 DBC files

Using locale: enUS
Opening /path/to/World of Warcraft/Data/enUS/locale-enUS.MPQ
Opening /path/to/World of Warcraft/Data/enUS/patch-enUS.MPQ
Opening /path/to/World of Warcraft/Data/enUS/patch-enUS-2.MPQ
Opening /path/to/World of Warcraft/Data/common.MPQ
Opening /path/to/World of Warcraft/Data/expansion.MPQ
Opening /path/to/World of Warcraft/Data/patch.MPQ
Opening /path/to/World of Warcraft/Data/patch-2.MPQ
Extracting camera files...
Extracted 13 camera files
Using locale: enUS
Opening /path/to/World of Warcraft/Data/enUS/locale-enUS.MPQ
Opening /path/to/orld of Warcraft/Data/enUS/patch-enUS.MPQ
Opening /path/to/World of Warcraft/Data/enUS/patch-enUS-2.MPQ
Opening /path/to/World of Warcraft/Data/common.MPQ
Opening /path/to/World of Warcraft/Data/expansion.MPQ
Opening /path/to/World of Warcraft/Data/patch.MPQ
Opening /path/to/World of Warcraft/Data/patch-2.MPQ
Extracting maps...
Read Map.dbc file... Done! (83 maps loaded)
Read AreaTable.dbc file...Done! (1643 areas loaded)
Read LiquidType.dbc file...Done! (7 LiqTypes loaded)
Convert map files
Extract Azeroth (1/83)                  
Extract Kalimdor (2/83)                  
Extract test (3/83)                  
Extract ScottTest (4/83)                  
Extract Test (5/83)                  
Extract PVPZone01 (6/83)                  
Extract Shadowfang (7/83)                  
Extract StormwindJail (8/83)                  
Extract StormwindPrison (9/83)                  
Extract DeadminesInstance (10/83)                  
Extract PVPZone02 (11/83)                  
Extract Collin (12/83)                  
Extract WailingCaverns (13/83)                  
Extract Monastery (14/83)                  
Extract RazorfenKraulInstance (15/83)                  
Extract Blackfathom (16/83)                  
Extract Uldaman (17/83)                  
Extract GnomeragonInstance (18/83)                  
Extract SunkenTemple (19/83)                  
Extract RazorfenDowns (20/83)                  
Extract EmeraldDream (21/83)                  
Extract MonasteryInstances (22/83)                  
Extract TanarisInstance (23/83)                  
Extract BlackRockSpire (24/83)                  
Extract BlackrockDepths (25/83)                  
Extract OnyxiaLairInstance (26/83)                  
Extract CavernsOfTime (27/83)                  
Extract SchoolofNecromancy (28/83)                  
Extract Zul'gurub (29/83)                  
Extract Stratholme (30/83)                  
Extract Mauradon (31/83)                  
Extract DeeprunTram (32/83)                  
Extract OrgrimmarInstance (33/83)                  
Extract MoltenCore (34/83)                  
Extract DireMaul (35/83)                  
Extract AlliancePVPBarracks (36/83)                  
Extract HordePVPBarracks (37/83)                  
Extract development (38/83)                  
Extract BlackwingLair (39/83)                  
Extract PVPZone03 (40/83)                  
Extract AhnQiraj (41/83)                  
Extract PVPZone04 (42/83)                  
Extract Expansion01 (43/83)                  
Extract AhnQirajTemple (44/83)                  
Extract Karazahn (45/83)                  
Extract Stratholme Raid (46/83)                  
Extract HyjalPast (47/83)                  
Extract HellfireMilitary (48/83)                  
Extract HellfireDemon (49/83)                  
Extract HellfireRampart (50/83)                  
Extract HellfireRaid (51/83)                  
Extract CoilfangPumping (52/83)                  
Extract CoilfangMarsh (53/83)                  
Extract CoilfangDraenei (54/83)                  
Extract CoilfangRaid (55/83)                  
Extract TempestKeepRaid (56/83)                  
Extract TempestKeepArcane (57/83)                  
Extract TempestKeepAtrium (58/83)                  
Extract TempestKeepFactory (59/83)                  
Extract AuchindounShadow (60/83)                  
Extract AuchindounDemon (61/83)                  
Extract AuchindounEthereal (62/83)                  
Extract AuchindounDraenei (63/83)                  
Extract PVPZone05 (64/83)                  
Extract HillsbradPast (65/83)                  
Extract bladesedgearena (66/83)                  
Extract BlackTemple (67/83)                  
Extract GruulsLair (68/83)                  
Extract NetherstormBG (69/83)                  
Extract ZulAman (70/83)                  
Extract PVPLordaeron (71/83)                  
Extract SunwellPlateau (72/83)                  
Extract Transport176244 (73/83)                  
Extract Transport176231 (74/83)                  
Extract Sunwell5ManFix (75/83)                  
Extract Transport181645 (76/83)                  
Extract Transport177233 (77/83)                  
Extract Transport176310 (78/83)                  
Extract Transport175080 (79/83)                  
Extract Transport176495 (80/83)                  
Extract Transport164871 (81/83)                  
Extract Transport20808 (82/83)                  
Extract Sunwell5Man (83/83)                  
</details>

This is also give you all the map files in the directory you created (in a subdirectory maps). On my system, I get 3586 map files, including the ones for map 530.

**Comment by insunaa** [comment]
Check the .mpq extensions anyway, evil-at-wow has a good approach, but doesn't hurt to do the quick and dirty check first. You're of course correct that if all .mpq files were misnamed then all maps would be missing, but I've seen it before that people have mixed-case mpq files, I don't know why but I'm guessing it could be due to modifying the MPQ, that the tool overrides the file in lowercase for example, or that an expansion patch was added from a lower-case client, or maybe that it's an old original client which had been upgraded through the patch tool, which may or may not use lowercase, dunno...

**Comment by AnonXS** [comment]
I have 3586 map files, 2797 mmap files and still get these errors from time to time for no reason.

**Comment by evil-at-wow** [comment]
I understand you get the errors from time to time AnonXS - which is still a problem I would say - but the file listing provided by zjyzju earlier suggests they're not even on disk in their case (while your count suggests you at least have them on disk). So I just wanted to try to solve that mystery first :smile:

**Comment by zjyzju** [comment]
all mph file is MPQ

root@ost:/opt/wow/wow2.4.3/Data# ll
total 4792684
drwxr-xr-x 1 root root         68 Jan  5 18:07 ./
drwxr-xr-x 1 root root        666 May  5 13:14 ../
-rw-r--r-- 1 root root 3817027714 Jan  5 15:58 common.MPQ
drwxr-xr-x 1 root root        416 Jan  5 18:08 enGB/
-rw-r--r-- 1 root root   50569223 Jan  5 18:00 patch-2.MPQ
-rw-r--r-- 1 root root 1040104387 Jan  5 17:43 patch.MPQ
root@ost:/opt/wow/wow2.4.3/Data# ll enGB/
total 589584
drwxr-xr-x 1 root root       416 Jan  5 18:08 ./
drwxr-xr-x 1 root root        68 Jan  5 18:07 ../
-rw-r--r-- 1 root root       142 Jan  5 15:56 AccountBilling.url
-rw-r--r-- 1 root root     27939 Jan  5 17:55 Credits.html
drwxr-xr-x 1 root root       122 Jan  5 18:08 Documentation/
drwxr-xr-x 1 root root        20 Jan  5 18:08 Interface/
-rw-r--r-- 1 root root       142 Jan  5 15:56 TechSupport.url
-rw-r--r-- 1 root root  19096816 Jan  5 18:00 backup-enGB.MPQ
-rw-r--r-- 1 root root  19651468 Jan  5 15:56 base-enGB.MPQ
-rw-r--r-- 1 root root      8813 Jan  5 15:56 connection-help.html
-rw-r--r-- 1 root root     20283 Jan  5 17:55 eula.html
-rw-r--r-- 1 root root 120420297 Jan  5 15:58 locale-enGB.MPQ
-rw-r--r-- 1 root root  12319131 Jan  5 18:00 patch-enGB-2.MPQ
-rw-r--r-- 1 root root  66086049 Jan  5 17:44 patch-enGB.MPQ
-rw-r--r-- 1 root root 366017976 Jan  5 15:59 speech-enGB.MPQ
-rw-r--r-- 1 root root      2670 Jan  5 17:33 termination.html
-rw-r--r-- 1 root root     53754 Jan  5 17:55 tos.html

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/236585352-3b5bab0b-5856-48ed-be86-20d468f9f165.png)

![grafik](https://user-images.githubusercontent.com/19734826/236585469-a4e76287-d714-4270-80bc-a1aa5c6dd4e4.png)

expansion.MPQ? though clients may differ, dont mind patch-3.MPQ

**Comment by evil-at-wow** [comment]
That missing expansion.MPQ explains why you're missing the main expansion map. And I just remember something that may explain it: back in the days you had the WoW installer and then with the TBC expansion there was a WoW-BurningCrusade installer. But if I'm not mistaken, you could install "WoW 2.0" (being the original game but at a later version) and patch it all the way to 2.4.3... but not have (and thus not able to play) the TBCexpansion!
So make sure you're using a TBC installer and have that patched to 2.4.3!

**Comment by celguar** [comment]
Using tbc installer is not a remedy, I have an installer and it installs 2.4.3 without expansion.mpq
Same goes for w o w d l  website, they have a 2.4.3 with no expansion.mpq.
So need to get a proper client (no links here, just google it)

**Comment by evil-at-wow** [comment]
If it's not installing expansion.mpq, then you don't have a TBC (as in 'Burning Crusade') installer. Using a 2.x installer or 2.x patch is _not_ sufficient, you really need a Burning Crusade installer (and then patch that to 2.4.3 if needed). Unfortunately there are probably many files tagged as 'tbc' or 'burning crusade' on the internet while the files are merely 2.x versions, but not necessarily include the expansion. That's not making things easier of course...

**Comment by celguar** [comment]
Yes it doesn't make it easier, as all those installers say it's tbc installer, it says burning crusade ,has tbc music and logo
 Easier just to download ready client

**Comment by zjyzju** [comment]
after change to a new client , it is ok now. thanks all!

**Comment by insunaa** [comment]
Closing as completed.
