### ISSUE TITLE
🐛 [WOTLK] Emty window loot table

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3412]
### Bug Details

If a creature that u kill, does not have loot in it, it should not have the animation like when it has.
95% of the time this thing is working, but there is a slight 5% when u get that behaviour

Tested with updated core 19.05.2023

![image](https://github.com/cmangos/issues/assets/6240049/fe74c2a1-787f-493c-b28f-7f2ddb1f9c8c)

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
@evil-at-wow let me poke u in this one, cause u have a lot of patience to check this small stuff

**Comment by kelbren** [comment]
There is a server side config option to disable this behavior in mangosd.conf
Corpse.EmptyLootShow 
If target can have loot (or can be skining after loot) but no loot generated still show loot window
Default: 1 (show)
0 (not show)

Change it to 0 from 1 and see if that works.

**Comment by AnonXS** [comment]
wth this makes no sense to me, why it even exists. Potential Fix: <https://github.com/cmangos/mangos-tbc/commit/ca8c6c30d62cc1039af657c6f6147d016e254873>

/tested and it seems to do the trick. Still has to be discussed if this is maybe a blizzlike oversight / video proof etc, or we atleast reduce the chance for it to happen.

```

                // loot may be anyway empty (loot may be empty or contain items that no one have right to loot)
                bool isLootedForAll = IsLootedForAll();
                if (isLootedForAll)
                {
                    // show sometimes an empty window
                    if (sWorld.getConfig(CONFIG_BOOL_CORPSE_EMPTY_LOOT_SHOW) && urand(0, 2) == 1)
                    {
                        m_isFakeLoot = true;
                        isLootedForAll = false;
                    }
                }

```

to bypass alot of discussion we can start by flipping default value to 0, as it is clearly not default behavior, maybe for some debugging cases it is good to still have this option, but then maybe with 100%?

But yea then again, maybe it this could happen in original classic/tbc/wotlk so need some more feedback.

**Comment by al3xc1985** [comment]
I don't have 2 much experience on official server, I played till 80 like when first wotlk released, but I don't remember this to happend than. I am not saying it 100% cause it's long time since than.

Tested with Corpse.EmptyLootShow and it does the trick

**Comment by insunaa** [comment]
I can confirm that both of these behaviours could be observed on official servers at different times. I don't know when they switched it, but I'm absolutely sure that very early in WoW enemies that had no loot drop wouldn't sparkle and wouldn't be lootable, but at some later time, I don't remember when exactly, it became possible to loot empty corpses, and get an empty loot window as a result.

Mobs that don't have a loot table never get a loot window, but all mobs that do have a loot table can have an empty window. I can only speculate as to the reason and I'd guess it's to accommodate for random quest item drops for quests the character isn't on, so basically the mob drops a quest item, but the player isn't on that quest, so the player doesn't see the item in the loot window => it's empty

**Comment by evil-at-wow** [comment]
We've had discussions in the past about this, although I can't quickly find any back. That's likely why the config option exists: so people can turn it off if it annoys them, even though it has been seen on the reference servers as insunaa mentions.
I'm very positive there were cases where I have gotten empty loot windows on the reference (and perhaps there is even some evidence burried deep in my capture archives). But it's hard to find solid evidence of what the reference has changed and when exactly. The possible quest item theory is a good one though, because as far as I know quest item drop are always in the loot but not shown if you're not eligible for them (one way this was visible at one point in time is for quests that require n items dropping from mobs; if you were still missing one to complete the quest, you could kill multiple mobs until you see a quest item in the loot of multiple mobs, then once you picked up one quest item the ones in the other loot you know also had one disappeared when you checked again).

**Comment by al3xc1985** [comment]
U got emty loot window because u killed more mobs than u needed for quests? for example u need 8 crystal from mob X and u killed 9 or 10... in that case u might receive that effect.. is this the case u describe? @evil-at-wow

**Comment by insunaa** [comment]
No, the theory is that loot tables/loot rules don't check if a player is on a quest before deciding to drop a quest item, they just drop them according to their dropchance regardless. Only players who aren't on that quest won't see these quest items. For most mobs you won't notice that, because they'll have some gray loot or money so the loot window isn't empty even if a quest item dropped for a quest that you aren't on, but if the mob has no other loot for you except for the quest item which is invisible to you,  because you're not on the quest, you get an empty loot window

The scenario that evil-at-wow described was a scenario which you can use to partially test this hypothesis: You need 8 crystals and you kill 10 mobs, all of which have dropped the crystal, but you never picked up the loot from them (no auto-loot) so when you go through the 10 mobs you killed and loot them one by one, having previously confirmed that all of them have dropped these crystals, you'll notice that once you've looted 8 crystals that the 2 remaining mobs, which previously still had crystals, no longer have crystals and instead just show an empty loot window

**Comment by AnonXS** [comment]
But in classic, the items turned red in the loot window, but were still visible to you after you looted the needed amount of items. (atleast that was my observation with this, not sure how quest items that drop in stacks handle this)

I mean part of this to happen so often is that the default quest drop chance is 80%, so alot have to yet be reduced to lower amounts. (starting zones come to mind where the chance will stay so high)

Other then that the simple 33% will be visible might be a tad too high, which results in player frustration when farming these mobs.

**Comment by insunaa** [comment]
@AnonXS I believe that was only when grouped up with other party members still on the quest, not sure tho

**Comment by AnonXS** [comment]
Ah okay, anyways, i stand by the point that reducing it to 1/5 will reduce the likelyhood of it happening by alot as it's already an unusual edge-case to begin with.

**Comment by al3xc1985** [comment]
I believe that so too @AnonXS

**Comment by evil-at-wow** [comment]
I honestly don't remember what patch the behavior I described was seen...

AnonXS is correct that in Classic items turned red in the loot window once you got enough of them already. That was also the case when you were questing alone and not just when you were in a group as insunaa writes (I found footage of solo play in the first days of Classic and that happening). 

For what it's worth, I also found footage from the first days of Classic where "Ice Claw Bear" were killed, their body blinking suggesting there's loot, and then getting an empty loot window. Same thing for "Snow Leopard". Humanoids typically dropped some coins. I don't know if these can drop quest items. Another pure guess is this may also be related to skinnable mobs? Kind of lure the player into looting, so another player can later skin (you can't skin mobs that aren't looted already, but you can skin afterwards, even if tagged by someone else)? 

Interestingly enough, once the player has skinning as a profession,I also found two kills of "Elder Black Bear" later with different behavior: once giving the empty loot window, but once giving a loot icon after the kill but not bringing up an empty window upon looting, but the cursor changing into the skinning one. And a killed "Forest Lurker" also suggested loot, but didn't bring up an empty loot window either when looting (and didn't change icon because they are not skinnable). So yeah it's a mystery but empty loot windows certainly happened quite often in Classic it seems... not sure if that has ever changed (and if so, when).

**Comment by miraco** [comment]
I just got an empty loot windows on wotlk classic. So this seems to be indeed an correct behavior.
Sadly didnt make a screenshot before, but i got it a 2nd time now.

![WowClassicT_eGtdoOkSH7](https://github.com/cmangos/issues/assets/6261245/9a899535-1156-4288-beec-92bcae1700e9)

**Comment by al3xc1985** [comment]
Tnan we need to reduce this behaviour as anonxs pointed

**Comment by al3xc1985** [comment]
it's ok, and normal. Tested on offi
