### ISSUE TITLE
🐛 [Bug Report] Lots of mobs in tirisfal Glades have the wrong abilities

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3413]
### Bug Details

In Tirisfal Glades:

1. Scarlet Warriors have both Nimble Reflexes and Moss Hide, but are only supposed to have Nimble Reflexes.
2. Greater Duskbats cast Sonic Burst but are supposed to cast Ravage instead.
3. Vampiric Duskbats cast Ravage but are supposed to cast Screech instead.
4. Scarlet Friars cast Power Word: Fortitude, but are supposed to cast Lesser Heal instead.
5. Captain Vachon casts the wrong level of Shield Bash.
6. Darkhounds are supposed to be able to Daze players, but I haven't seen them use this ability.
7. Additionally, most of these mobs are being given these abilities from two different parts of the database (creature_ai_scripts and creature_template_spells)

### Steps to Reproduce

N/A

### Expected behavior

See bug details

### Suggested Workaround

I've corrected most of these values myself.

### Crash Log

N/A

### Core SHA1 Commit Hash

c3702e1a

### Database SHA1 Commit Hash

Dunno, not in the filename

### Operating System

Win7

### Client Version

9.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
Can you do ".npc info" to give us a list of npcs to look into, because i could not find any scarlet warriors (entry=1535) that have moss hide.

7. Ah i see what you checked, https://github.com/cmangos/issues/wiki/creature_template_spells does not influence ai its spells these npcs have when they are MCed, but infact you're right they were wrongly assigned somehow.

1. corrected some wrong mc spell in creature_template_spells.

e.g. 2. the bats might still have this wrong sonic boom spell in creature_template_spells, but it is not used ingame.

![grafik](https://github.com/cmangos/issues/assets/19734826/8c76c5d3-c039-47bb-9156-57c88b011b6d)

3. you're wrong, maybe mislead by using wowhead as source.

![grafik](https://github.com/cmangos/issues/assets/19734826/20804c54-e9db-4acd-9677-b5665beba6c2)

4. should not cast the fortitute spell which does nothing for them, their heal had long cd due to eai being not good with healing spells anymore.

5. no correct spellid, but too often.

6. daze is a spell that is cast on you depending on your SKILL_DEFENSE (95) level compared to the enemies level.

---

If you find more open a new issue, best is do it by zone or something as to not do too much at once.
