### ISSUE TITLE
The database IS installed properly. It's your duskbat data that's wrong.

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3420]
Yes I have. Maybe install the database properly before complaining. Thank you and have a nice day.

_Originally posted by @insunaa in https://github.com/cmangos/issues/issues/3419#issuecomment-1556259860_

**Comment by AnonXS** [comment]
Can someone confirm this issue happening on master-mangos-tbc?

```
.go c id 1553 - https://www.wowhead.com/wotlk/npc=1553/greater-duskbat
.go c id 1554 - https://www.wowhead.com/wotlk/npc=1554/vampiric-duskbat
```

**Comment by kelbren** [comment]
I don't have TBC setup, but In Wotlk they only cast Ravage very frequently

After reading the comments on wowhead, it seems this behavior is correct.  Demoralizing screech is active only if it is a hunter pet.

**Comment by insunaa** [comment]
> ```
>           Yes I have. Maybe install the database properly before complaining. Thank you and have a nice day.
> ```
> 
> _Originally posted by @insunaa in [#3419 (comment)](https://github.com/cmangos/issues/issues/3419#issuecomment-1556259860)_

Post the output of
```sql
select * from creature_ai_scripts where creature_id=1554;
select * from creature_template where entry=1554;
```

**Comment by wdstudios2** [comment]
> I don't have TBC setup, but In Wotlk they only cast Ravage very frequently
> 
> After reading the comments on wowhead, it seems this behavior is correct. Demoralizing screech is active only if it is a hunter pet.

Screech was changed to Demoralizing Screech in Wrath. I don't know if there was an AI change. The duskbats' abilities kept changing in every expansion. What matters is that the Vampiric Duskbats are NOT supposed to have Ravage in ANY expansion, and they certainly shouldn't be able to kill players by casting it every 2 seconds.

**Comment by wdstudios2** [comment]
> Post the output of
> 
> ```sql
> select * from creature_ai_scripts where creature_id=1554;
> select * from creature_template where entry=1554;
> ```

What output? Am I supposed to type those somewhere?

**Comment by miraco** [comment]
https://puu.sh/JHqZK/cd1ac6cb38.png

https://puu.sh/JHr0k/9dc1e1e659.png

I can confirm that both npc use ravage only on cmangos-tbc. (from creature_ai Vampiric Duskbat - Cast Ravage) but i dont know what they should originaly do on retail cause no one profed anything other.

I dont know whats the issue in here because it doesnt point any bug from opener.

So please do a proper issue, or write me at discord so i can open the starting issue. 

But please stop opening such bullshit issue threads.

**Comment by wdstudios2** [comment]
>  i dont know what they should originaly do on retail cause no one profed anything other.

I've said several times before that they're supposed to cast Screech (spell=24423). https://www.wowhead.com/tbc/npc=1554/vampiric-duskbat#abilities;mode:normal

> But please stop opening such bullshit issue threads.

There aren't bullshit issues. I've never used a core or database that was more than 3 days old, and with the exception of the dead Draenei crash survivors, I've always provided the correct core and DB commit hashes on which these bugs appear.

**Comment by miraco** [comment]
> > i dont know what they should originaly do on retail cause no one profed anything other.
> 
> I've said several times before that they're supposed to cast Screech (spell=24423). https://www.wowhead.com/tbc/npc=1554/vampiric-duskbat#abilities;mode:normal
> 
> > But please stop opening such bullshit issue threads.
> 
> There aren't bullshit issues. I've never used a core or database that was more than 3 days old, and with the exception of the dead Draenei crash survivors, I've always provided the correct core and DB commit hashes on which these bugs appear.

So first:
You said it in other issue threads, not in this one.  You just acted like a child and opened 2 new issues without any context.
So me, for example, only readed this one here and i didnt know what your actualy issue is, because your title just said database is installed and your bug details just say yes i have.
How should **_I_** know whats your issue without searching the other issue threads you opened before?
Thats why i called it bullshit issue, and i will for now on just start closing this kind of posts.

For future, if someone closes your issue, but you believe that this is still not working correctly, try to contact anyone of the team and tell them to reopen it. Or just create a new Issue with correct title, bug report and so on. 
There is a reason we have a template for this. 

2nd: 3days old Core/Database can have a great impact. Just look how much commits went into core/db repo in the last days. And every commit could already have fixed one of your issues. So yes isunaa was right, your initial issue was already fixed on our site, you just didnt updated your db/core.

Anyway for your issue with Screech on Vamipiric Duskbat:
wowhead **is not** a good source for some things. I fighted this mob on retail wotlk server, and there they only use Ravage on me.
![WowClassicT_65Qb6FM2Dd](https://github.com/cmangos/issues/assets/6261245/58209098-06c2-4c45-972a-b063512b0da4)

If you still think they should only use Screech instead of Ravage, show me a video from retail tbc, or a patchnote that this npc got changed from tbc to wotlk. 
But for now we will let it like it is.

**Comment by wdstudios2** [comment]
>  You just acted like a child and opened 2 new issues without any context.

It's not "acting like a child" dumbass. It was LITERALLY THE ONLY THING I COULD DO.

> How should I know whats your issue without searching the other issue threads you opened before?

I provided a link to the previous discussion.

> For future, if someone closes your issue, but you believe that this is still not working correctly, try to contact anyone of the team and tell them to reopen it.

I would have loved and preferred to do that. Unfortunately, your Discord moderators have a bad habit of banning anyone who proves them wrong or disagrees with them about anything. That problem was ignored too.

> I fighted this mob on retail wotlk server, and there they only use Ravage on me. If you still think they should only use Screech instead of Ravage, show me a video from retail tbc, or a patchnote that this npc got changed from tbc to wotlk. But for now we will let it like it is.

Well... THAT is interesting. What could cause such a discrepancy?

**Comment by insunaa** [comment]
The discord has literally 9 banned accounts, 8 are cryptoscammers and the ninth is you. Reconsider your behaviour towards people, maybe then you'll be taken seriously

**Comment by wdstudios2** [comment]
There was nothing wrong with MY behavior. I was attacked and I defended myself.
------- Original Message -------

**Comment by killerwife** [comment]
You two take it off github. I will procceed to delete the messages that are irrelevant and will continue to do so if the discussion devolves again on another thread.

**Comment by al3xc1985** [comment]
Screech is a spell that hunter pets use.
