### ISSUE TITLE
🚀 [Feature Request] 

### ISSUE THREAD

**Issue by 111High111** [cmangos/issues#3422]
![~BY84QOVAWS`E8VR19_VTM0](https://github.com/cmangos/issues/assets/133279370/6a5647d8-7543-4cf7-b75a-118efac918e2)
### Feature Details

Can we translate the database into Chinese

### Benefits and Purpose

Can we translate the database into Chinese

### Core Versions

- [X] 1.1.12 (Classic)
- [x] 2.4.3 (The Burning Crusade)
![~BY84QOVAWS`E8VR19_VTM0](https://github.com/cmangos/issues/assets/133279370/f470dcbe-f4fe-4fd5-b858-72c964c5cf0c)

- [x] 3.3.5a (Wrath of the Lich King)

**Comment by wdstudios2** [comment]
China is home to hundreds of languages. You might as well ask for the database to be translated into "African" or "Middle Eastern" :) https://en.wikipedia.org/wiki/Languages_of_China

**Comment by celguar** [comment]
@wdstudios2 
Language requested is stated in first message

**Comment by 111High111** [comment]
I just want to translate it into Chinese. In the game, the names and dialog boxes of the strange task NPCs are in English. I just want to convert them into Chinese, but the database file for changing the Chinese language is actually empty




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmangos/issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 凌晨5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmangos/issues] 🚀 [Feature Request]  (Issue #3422)





 
China is home to hundreds of languages. You might as well ask for the database to be translated into "African" or "Middle Eastern" :) https://en.wikipedia.org/wiki/Languages_of_China

**Comment by fangshun2004** [comment]
I use cmangos-tbc. Most of the tasks in it Chinese Simplified have data. Chinese Traditional is missing a part. However, it is easy to convert Chinese Simplified into Chinese Traditional populate the database. Although there are some differences between the two traditional in Blizzard servers. But for now, it's better than nothing

**Comment by fangshun2004** [comment]
I use cmangos-tbc. Most of the tasks in it Chinese Simplified have data. Chinese Traditional is missing a part. However, it is easy to convert Chinese Simplified into Chinese Traditional populate the database. Although there are some differences between the two traditional in Blizzard servers. But for now, it's better than nothing

**Comment by fangshun2004** [comment]
I use cmangos-tbc. Most of the tasks in it Chinese Simplified have data. Chinese Traditional is missing a part. However, it is easy to convert Chinese Simplified into Chinese Traditional populate the database. Although there are some differences between the two traditional in Blizzard servers. But for now, it's better than nothing

**Comment by 111High111** [comment]
So how can I turn them into Chinese




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmangos/issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmangos/issues] 🚀 [Feature Request]  (Issue #3422)





 
I use cmangos-tbc. Most of the tasks in it Chinese Simplified have data. Chinese Traditional is missing a part. However, it is easy to convert Chinese Simplified into Chinese Traditional populate the database. Although there are some differences between the two traditional in Blizzard servers. But for now, it's better than nothing

**Comment by insunaa** [comment]
https://github.com/MangosExtras/MangosZero_Localised
https://github.com/MangosExtras/MangosOne_Localised
https://github.com/MangosExtras/MangosTwo_Localised

These are translation projects for the relevant game versions. I don't know how you'd integrate these translations into CMaNGOS, but I've heard of people doing it, you could try asking in the offtopic channel in our discord server.

**Comment by fangshun2004** [comment]
Export data in an existing data table where local5 is blank and local4 is not empty. Export as update.  Then conversion with transcoding software/web pages is also possible. Convert text from simplified to traditional. Replace local4 with local5, and import the database again after the replacement is complete so that it works fine. However, there are some slight differences between the text translation and the translation of Blizzard's Chinese Traditional. But the main meaning is the sam

**Comment by Nightingale9002** [comment]
网上有一些数据库汉化，但是不全，包括那个db.nfu的数据，而且还有很多比如珠宝是错的。各种插件跟数据库也对不上。主要是版本太多了。

**Comment by MantisLord** [comment]
> https://github.com/MangosExtras/MangosZero_Localised
https://github.com/MangosExtras/MangosOne_Localised
https://github.com/MangosExtras/MangosTwo_Localised
> 
> These are translation projects for the relevant game versions. I don't know how you'd integrate these translations into CMaNGOS, but I've heard of people doing it, you could try asking in the offtopic channel in our discord server.

I know this is an old issue, but just wanted to clarify a couple things.

The MangosExtras repos you linked do contain some relevant data, but some is also obsolete/deprecated in favor of official sources (that which is covered by our broadcast texts already). In the case of TBC-DB, we should already have imported the relevant data from the MangosOne_Localised repo.
I'll try to explain in a bit more detail for those who care...

All localization texts can be split into two categories:

**1. Broadcast texts**
Includes all texts used by creatures & gameobjects for gossip menus/menu options and yells/says/emotes during scripts both in and outside of combat.
Our current broadcast text data should be from an official source and mostly complete for all languages.
There may be some cases where we still need to set the appropriate broadcast text Id for each English text. For example, any creature which still uses `npc_text` instead of `npc_text_broadcast_text` is a case where we already have the proper translation data available in the DB - it's simply not yet assigned.
Here's how to show/search the Chinese data we have for broadcast texts: 
`select * from broadcast_text_locale where Locale = 'zhCN';` 

**2. All other texts**
Broadcast texts do not cover things like quests, names of items, creatures, and gameobjects.
For these we still use the corresponding locales_* tables. This is where our data is definitely lacking/incomplete.
In TBC-DB, we have some data in each of these tables for Simplified/Traditional Chinese (loc4/5):
```
locales_creature
locales_gameobject
locales_item
locales_page_text
locales_points_of_interest
locales_quest
locales_questgiver_greeting
locales_trainer_greeting
```
I can't attest to the source of any of the data in these locales tables I listed, other than it was copied straight from the MangosOne_Localised repo. If anyone has an official Blizzard data scrape for all of this type of text, please share so we can improve on what we already have in TBC-DB.

As a result of the addition of broadcast texts, the following locales tables are now obsolete. We should not continue to maintain the data in any of these tables - they'll eventually be dropped as broadcast texts now serve as the official source:
```
locales_gossip_menu_option
locales_npc_text
```

Any remaining localized text strings (system messages, login screens, settings menus & buttons) should be handled by using a game client matching the language you want to play in.

**Comment by celguar** [comment]
I recommend using vmangos locales for 1.12. MangosZero locales often have Cataclysm+ locales for quests, at least I noticed it in Russian and French
