### ISSUE TITLE
🐛 [WOTLK] Shadowmourne - Visual Bug

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3533]
### Bug Details

https://www.wowhead.com/wotlk/item=49623/shadowmourne

The visual that proc on this weapon never dissapear even if the buff expires

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by virusav** [comment]
Core SHA: 411996adfc54a4efe68308141c2de4c5108032ae.
Wotlk-db SHA: a2c943579278a8a2a4354a48269725145e7f6ccc.
![WoWScrnShot_082523_124325](https://github.com/cmangos/issues/assets/323130/06cf74c2-cd24-4322-ac62-1bcf7efdd284)
![WoWScrnShot_082523_125441](https://github.com/cmangos/issues/assets/323130/4c63fffa-d065-41a2-bc5a-736b4295f164)


The effect disappears.
The problem is that the timer under the buff icon sometimes shows the time incorrectly.
If you hover over the buff, the tooltip will show the correct time.
With each new fragment, the time is aligned with the buff and in the tooltip.

**Comment by al3xc1985** [comment]
retested again with fresh, and works.. thx
