### ISSUE TITLE
🐛 [TBC] [Bug Report] Katrana Prestor doesn't turn into Onyxia - The Great Masquerade

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3539]
### Bug Details

During the Onyxia attunement, one quest has the player characters following Marshal Windsor to the Keep to confront Katrana Prestor. Windsor uses these two tablets to cast a spell on Katrana Prestor that, normally, forces her into Onyxia form.

At present, Windsor casts the tablets on Prestor, but she never turns into her dragon form. A bit of a letdown.

### Steps to Reproduce

1. .quest add 6402
2. .go creature 79862
3. Chat with Squire Rowe, who will summon Reginald
4. Turn in quest at Reginald and pick up The Great Masquerade
5. Carry on with the RP and follow Reginald (this quest takes, like, 10 minutes; if there is a faster way of getting through it, do that)
6. Once you give Reginald consent to enter the Keep... 
7. Profit.

### Expected behavior

Onyxia should turn into her dragon form once Reginald completes his cast. 

https://www.youtube.com/watch?v=WFDA5zakwcc&ab_channel=Wrecking
9:42 timestamp

### Core SHA1 Commit Hash

4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9

### Database SHA1 Commit Hash

29d56229d67cefbbf835f52cd3a0072746520952

### Operating System

Windows 11 Home - 64-bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by evil-at-wow** [comment]
Confirmed. The issue here seems to be an unknown spell:
> CastSpell: unknown spell id [20409](https://www.wowhead.com/classic/spell=20409/lady-prestor-transforms-dnd) by caster: Creature (Entry: 1749 Counter: 10497) DBGuid: 10497

I'm sure this worked a few years ago, so I wondered what relevant parts have changed. A closer look suggests this is the commit that broke it for at least TBC (and likely WoTLK as well if it was ported): https://github.com/cmangos/mangos-tbc@2648c7dfbaca617ea907ffe3f5abbe94b70a902b.

In particular, note how the transformation to Onyxia was done with an ```UpdateEntry``` call before the commit, and with a spell after. The line introducing the spell gives a very good hint of why it was done differently before:
> -// SPELL_ONYXIA_TRANSFORM = 20409, // removed from DBC
  +SPELL_ONYXIA_TRANSFORM      = 20409,

It looks like this spell is indeed not in TBC's DBC, but that wasn't noticed when this was ported to TBC. But we can fix this by taking the missing spell from Classic's DBC.

**Comment by insunaa** [comment]
it worked ~3 months ago, so not sure why it's not working now.

**Comment by Grz3s** [comment]
`(...)and likely WoTLK as well if it was ported(...)`
Quest was removed in 3.x.x ...so TBC issue ONLY.

**Comment by cpevors** [comment]
A bit late to my own party, but I also recall it working a decent while ago. Haven't attempted this quest in probably 6+ months.

I sounds like an easy fix, but I'll admit I'm not savant at these things, so I'll leave the fix to more capable hands. I appreciate the collaboration and the help!
