### ISSUE TITLE
🐛 [Bug Report] Greater Silithid Flayers and Greater Anubisath Warbringers spawning in Gadgetzan and elsewhere

### ISSUE THREAD

**Issue by LEO33SoFo** [cmangos/issues#3624]
### Bug Details

[Greater Silithid Flayer](https://www.wowhead.com/tbc/npc=15756/greater-silithid-flayer)s and [Greater Anubisath Warbringer](https://www.wowhead.com/tbc/npc=15754/greater-anubisath-warbringer)s are spawned in Gadgetzan and Silithus, including several Qiraji elite mobs at the _Scarab Wall_, indicative of the 10-hour phase of the _Gates of Ahn'Qiraj_ event, where there should not be any, because in my solo server I didn't start the _War Effort_ event, and the gates are supposed to be closed by default, or open like in VMaNGOS.
Even after using the command `.worldstate wareffort phase 5`, the aforementioned mobs still spawn.

### Steps to Reproduce

1. `.tele Gadgetzan` or `.go object id 180717`.
2. Check for the aforementioned mobs.

### Core SHA1 Commit Hash

6c9da3dfa1fc72c84d3ab82d119e0990c48ed751

### Database SHA1 Commit Hash

dcf9967fe151a62623d78e961c006934b418998a

### Operating System

Windows 8.1 with Update 3 Professional 64bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by obi23lipnik** [comment]
can confirm this happens on the current tbc-core too; The Gadgetsan ones are super sketchy too, since they are lvl ~58 elites inside the safezone. 

The ones in Barrens pose a different problem, since they are easily farmable even at lvl 30, and the farm yields a sick ~50 gold per hour easy. 


A viable workaround is just deleting all of these mobs from the creature table and restarting the server.
