### ISSUE TITLE
🐛 [Bug Report] Windows Guide Needs a Refresh

### ISSUE THREAD

**Issue by DrKittens** [cmangos/issues#3627]
### Bug Details

One of the core wiki pages with instructions for installation that is referenced
https://github.com/cmangos/issues/wiki/Detailed-installation-guide-for-Microsoft-Windows

Uses a very old version of boost libraries at old MSVC versions that dont appear to work with the modern windows ecosystem (without toolset buildflags which arent covered) even though cmangos can build under more recent boost versions.

### Steps to Reproduce

1. Attempt compilation of cmangos with a more recent compiler eg Visual Studio 17 2022 installation using the suggested 14.1 / 14.2 1.69 boost binaries and observe a build failure due to linker issues.

### Expected behavior

The recommendations / explanation of boost libraries should be functional and not lead the user astray. Less specificity eg install the latest version for your MSVC compiler and a reference table with what msvc version aligns with what commonly used windows compiler / IDE **or** an explicit functional working example with a modern / available MSVC compiler or IDE.

### Suggested Workaround

Update the wiki article section here https://github.com/cmangos/issues/wiki/Detailed-installation-guide-for-Microsoft-Windows#boost to include a table of MSVC versions for the related compilers

eg 
12.0 for visual studio 2013
14.0 for visual studio 2015
14.1 for visual studio 2017
14.2 for visual studio 2019
14.3 for visual studio 2022

Additionally bump the example version of the boost library from 1.69 to 1.80 as if someone were search that example version they would not be able to find versions for 14.2 and 14.3 which are the versions they'd most likely require

### Core SHA1 Commit Hash

na

### Database SHA1 Commit Hash

na

### Operating System

Windows

### Client Version

1.12.1 (Classic)

**Comment by MantisLord** [comment]
The main cross-platform installation instructions already have a better explanation of which boost binaries to choose with less specificity here: https://github.com/cmangos/issues/wiki/Installation-Instructions#installing-and-configuring-boost-windows

Perhaps it's time for us to consider retiring this Windows specific page you've linked and add any missing details to the main install instructions page.

**Comment by Muehe** [comment]
@MantisLord I agree with retiring the page. Don't really have the desire to keep a separate Windows install of Cmangos around for maintaining it since I use mostly Linux these days, so unless somebody else wants to pick up maintenance we should remove it. It's not just the MSVC part that's outdated by now, other parts as well, like still talking about 32bit compilation, describing how the old DB install script worked instead of the new one, showing Win7 way of editing environment variables...

That said, if @DrKittens or anybody else wants to update it, I still see some worth in having the page for less technically inclined new users. And I *think* the wiki is editable by anyone with a GitHub account again. But it would be a fair amount of work with the state the page is in right now.

**Comment by Muehe** [comment]
Have removed the content of the guide and references to it in this commit: https://github.com/cmangos/issues/wiki/_compare/fa8ed70c57d04cd93cbadc46fd2031e196459b55

Left a stub in place in case anybody wants to pick it up.

**Comment by killerwife** [comment]
Isnt windows install basically, download mysql, right version of boost, visual studio, cmake, some right environment variables and done?
