### ISSUE TITLE
🐛 [Bug Report] Quest : "A Pawn on the Eternal Board"

### ISSUE THREAD

**Issue by Hectelion** [cmangos/issues#3637]
### Bug Details

after accepting the quest nothing happens

### Steps to Reproduce

1.Levelup to 60
2.get and complete the quest "What Tomorrow Brings"
3.get and complete the quest "Only One May Rise"
4.get and complete the quest "The Path of the Righteous"
5.get and complete the quest "Anachronos"
6.get and complete the quest "Long Forgotten Memories"
7.get the quest "A Pawn on the Eternal Board"

### Expected behavior

https://www.youtube.com/watch?v=V_wU8PhIIWU

### Core SHA1 Commit Hash

48c44d0fab262c18c66e624c556d944e81bf6f39

### Database SHA1 Commit Hash

364f84ad5e9f6bb986afa6cb39a5bb4902613118

### Operating System

windows 10

### Client Version

1.12.1 (Classic)

**Comment by Grz3s** [comment]
backport from WoTLKDB missing:
https://github.com/cmangos/wotlk-db/commit/37b1eb2059db88609183b157c062e036fa6694e4
effect:
https://www.youtube.com/watch?v=MrtZXvj3Zdg&list=PLQWa1A2Qh_1XH_dyeGPZE1D9hwPw801e1&index=109

Note:
wotlk has gate const. open (classic not) - script may need small update in final part. (remove opening gate in final moment)

**Comment by Hectelion** [comment]
Yes it worked for the quest 8519, seems something missing for the previews quest the 8305 that does not complete and need a gm command don't know why.
The thing you said about removing the openng gate in the final part I dont know how to do it

**Comment by Hectelion** [comment]
If I may add, in cmangos-classic the gate is open by default and at the end of the video the gate is open again as it was at the start, wanting to test with the gate closed, acting on the gameobject-addon table the video start with the gate already closed and the spells used to close it make little sense, in theory the gate should be open at the beginning of the video to close with their spells and return to the state it was in before the video, whatever it was, then it would be fantastic if the portal were opened with the activation of phase 4

**Comment by Grz3s** [comment]
both vids comming not from classic
- from 1st post - comes from wotlk as it was in 2010. 
- second link.. is effect of my work for wotlk 3.3.5 (wotlk)

Dont mix 2 diff things...
- The Gates of Ahn'Qiraj (aka opening of the Gates of Ahn'Qiraj or the War Effort) was a server-wide [world event](https://wowpedia.fandom.com/wiki/World_event) that heralded in the opening of the raid instances [Ruins of Ahn'Qiraj](https://wowpedia.fandom.com/wiki/Ruins_of_Ahn%27Qiraj) and [Temple of Ahn'Qiraj](https://wowpedia.fandom.com/wiki/Temple_of_Ahn%27Qiraj)
- quest: `A Pawn on the Eternal Board` - shows RP event that happened long before above one & explains why gate was closed in first place..  

As far i remember .. vanilla had it closed until AQ event started. (so shouldnt be open as default) .. it was done with wotlk (if im correct)
WoWWiki:
As of February 6, 2009 ([patch 3.0.8a](https://wowpedia.fandom.com/wiki/Patch_3.0.8a)), the Ahn'Qiraj gates will automatically be open on all new future realms.

Thats why ... at the end of my vid.. gate opens again... to match ver 3.x.x and in my opinion should stay closed in 1.x.x & 2.x.x
Once more im sugestin to backport wotlkDB script + sd2 path that is connected to it...  then remove final line from script:
```code
(15381,5,7,-7926.0156,1400.8499,57.67987,100,10,1538108);
and script: 1538108
```

This should be sone by CDB DEV ..

**Comment by Hectelion** [comment]
Thank you, your work was excellent and thanks also to your suggestion I solved it.
The quest A Pawn on the Eternal Board as far as I can tell can be done before or after the AQ opening event, so I added the opening of the gate to the start of the quest and at the end instead of removing the opening of the gate l conditioned to events 123 or 124 active in classic.

**Comment by evil-at-wow** [comment]
> The quest A Pawn on the Eternal Board as far as I can tell can be done before or after the AQ opening event

Correct. Naturally the quest can be done before the AQ opening event because it's part of the chain to open the AQ gates in the first place, but one could also do the entire chain after the gates were already open (just without getting the mount).

It also seems the gates remain in their realm state. When the gates are opened on a realm, the quest starts with the gates open. Then as part of the quest's scripts they are closed by Anachronos, at which point they are actually briefly closed for the entire realm it seems (some players on their way to the AQ raid couldn't, because of the closed gate). At the end of the quest they revert to the open state. See for example [the video here](https://www.youtube.com/watch?v=SIvFcv7k5wY). This I can confirm after having done it myself on _the reference_. When the gates are still closed on a realm, the quest seems to starts with the gates closed, yet Anachronos still closes them as part of the quest; see [this movie of someone going for Scarab Lord](https://youtu.be/6Ke2PSvOO5Y?t=150) and [another move of the same person showing this quest](https://youtu.be/3nrTm0t3RGo?t=830). Because I've never done the quest before the gates were opened on a realm, I can't confirm that myself, so hopefully that is indeed the real deal.
