### ISSUE TITLE
Dying with Last Stand on sets HP to 1

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#462]
If you die with Last Stand on, it sets your HP to 1 after you die.

Making your client stuck even though you are really dead.

https://github.com/cmangos/mangos-classic/blob/25432f1f378a2ebc03e56e38637ceab4303adafe/src/game/SpellAuras.cpp#L3441-L3460

This is more than likely across all cores as the code seems familiar across all cores.

Definitely bugged on Classic Core, though.

**Comment by cala** [comment]
A possible fix from getmangos (have not tested it neither looked if it is good):
https://github.com/mangoszero/server/commit/e4bbedc09fca5c9a4d956650e4c754c0bdf33a43

**Comment by vovk** [comment]
@cala this won't help.

**Comment by Appled** [comment]
https://github.com/cmangos/mangos-classic/blob/25432f1f378a2ebc03e56e38637ceab4303adafe/src/game/SpellAuras.cpp#L3454
Instead of else statement, shouldn't you check if the unit is alive before setting the health? Because when you die, the auras are removed after "the real death", so setting the health makes you stuck. You can reproduce this thing easily; logon on GM account, kill yourself (no matter how) and then /g .modify health 1
You'll get stuck. So checking if the unit is alive before setting the health should fix this.

**Comment by cyberium** [comment]
There is still something weird that can cause that on actual core.
I got it recently.
Char die, but core side health is set to none zero right after. Client side it result on moving corpse :/
