### ISSUE TITLE
Shadow word: pain

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#465]
If you cast shadow word: pain on a target and another player also casts his sw:p on the same target, your sw:p disappears. Seems like only one sw:p can exist on a single target.

These are all sw:p - classic:
http://db.vanillagaming.org/?spell=589
http://db.vanillagaming.org/?spell=594
http://db.vanillagaming.org/?spell=970
http://db.vanillagaming.org/?spell=992
http://db.vanillagaming.org/?spell=2767
http://db.vanillagaming.org/?spell=10892
http://db.vanillagaming.org/?spell=10893
http://db.vanillagaming.org/?spell=10894

Tested on Classic.

**Comment by Warlockbugs** [comment]
Multi-rank SW:P should be fixed in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
Currently there is no evidence pointing that DoT spells shouldn't stack in vanilla, however, as debuff slots are limited, they should be knocked off from target by more important auras via debuff priority system (thats why you rarely can see multiple dots if any in raids on videos), which is something we need to implement at a later point.
Closing this as initial issue is fixed.

**Comment by Phatcat** [comment]
http://wow.gamepedia.com/Disgusting_Oozeling#Notes

**Comment by Phatcat** [comment]
Either disgusting Oozling aura is prioritized very high (higher than raid debuffs?) or there's something more to it

**Comment by Warlockbugs** [comment]
The debuff limit at the time was 8 if i am not mistaken, later increased to 16, so, yes, it was possible. The Acid is a DoT and in the old priority system it had the lowest prio.
