### ISSUE TITLE
Vyletongue Corruption

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#470]
You have to use an item with a gameobject. Several Creatures spawn and you to have to kill them. Each creature counts for the quest. 

Bugs:
- You can always use the same gameobject to spawn the creatures
- Too many creatures spawn. It should be 1-3.
  It is interesting that the last source mentions an elite who should always spawn. I didn't find any other source who tells about that. 

Quest: http://www.wowhead.com/quest=7041 and http://www.wowhead.com/quest=7029
Item: http://www.wowhead.com/item=17696
Creatures: http://db.vanillagaming.org/?npc=13696
Gameobject: http://wowpedia.org/Vylestem_Vine   http://db.vanillagaming.org/?object=178905

Sources:
http://wowpedia.org/Quest:Vyletongue_Corruption
https://web.archive.org/web/20060314034804/http://wow.allakhazam.com/db/quest.html?wquest=7029

**Comment by cala** [comment]
Almost probably a DB issue. What happens: using the item casts a spell activating a trap GO, the player trigger the trap and the NPCs spawn.
The issue here seems to be that the trap GO does not despawn when hit by the spell or acts like it has several charges (DB says it should have only one).
Hence, the trap GO can be activated/triggered several times, resulting in many spawns and many quest credits.
