### ISSUE TITLE
[Classic] DireMaul not scripted.

### ISSUE THREAD

**Issue by raymerjacque** [cmangos/issues#553]
DireMaul needs some serious scripting. Some parts are done, but some are not. when you enter diremaul, to the left. that whole section where you do the pally mount quest, and where the big dog boss is is not scripted at all. the mobs just stand still. in the retail all those torrents with the tiny torrents around them move in groups, the whisps float around and the whole instance has patrols.

**Comment by Patman64** [comment]
[Closed for this reason.](https://github.com/cmangos/issues/issues/552#issuecomment-70025386)

I haven't opened a new ticket for this post because it seems like there's more than one issue. [Please open new issues here,](https://github.com/classicdb/database/issues/new) and **open one ticket per problem** (e.g. *"Sergeant Five-eyes doesn't patrol."*).

Please do not open a *"Half of Dire Maul is broken"* ticket because it will never be closed and we love closing tickets, it's like the best part of fixing stuff (it also helps us stay organized and stuff).
