### ISSUE TITLE
Crossfaction Bugs

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#596]
When you allow crossfaction on your server you still have some bugs.

When you're in a group (horde AND alliance):
- You can't inspect characters of the other faction
- You can't follow characters of the other faction
- When you activate nameplates of enemies you also see the nameplate of characters of the other faction
- When a character of the other faction uses a damage dealing totem which attacks you and you get into his group it still attacks you (didn't test other pets)

When you're in a raid (horde AND alliance) AND you are in different groups:
- You can't inspect characters of the other faction
- You can't follow characters of the other faction
- When you activate nameplates of enemies you also see the nameplate of characters of the other faction
- Mouseover on characters of the other faction shows a sword but attacking them gets cancelled and he can't get any damage
- When using Tab to switch targets characters of the other faction can become target
- Crazy: group 1 (A A A H H) and group 2 (H A). H from group 2 buffs and only the following players get the buff: A from group 2 and one H from group 1. All players are in range. Maybe has to do something with the invitation because we changed the groups at the beginning?

I know that crossfaction is NOT blizzlike but it is very important for little servers to make it possible for players to raid even if there's only a little number of characters.

**Comment by cyberium** [comment]
cross faction is partialy coded/supported i think this will be removed one day.

**Comment by evil-at-wow** [comment]
I'm pretty sure most of this works fine on my TBC server, and I know some more client limitations were introduced in 3.x, so this should probably be labeled with Version-WoTLK for future reference.

About removing this feature in the future: I understand it's a custom feature that's nowhere near top priority, so I understand we don't spend a lot of time to support it. But if you're going to remove the option to group and play cross faction, you will kill most, if not all, small family and friend servers. That would only leave the bigger servers, which are the public ones (let's be honest here, pretty much no one runs a friends and family server with 50+ accounts). And that would be very ironic, because our stance has always been that we don't support public servers...

**Comment by cyberium** [comment]
I think time will come when we'll have more serious discussion about this. My point is auction bot, crossfaction and probably a couple of other feature should be coded as fully optional. No interaction at all with clean code when not enabled in cmake. Iam not against more feature you saw it by the introduction of PlayerBot in core. But those feature should not slow main development (that is already slow enough)
Also my answer meant to be more clear. A feature is not so well supported because there is many other urgent things to fix in clean core. And finally where i understand the need of player bot to play solo or with friends/family, i don't understand much the need of both factions in same group. But that's MY point ofc and i am big enough to follow the majority opinion :)

**Comment by Warlockbugs** [comment]
The list of issues for crossfaction groups should be revisited as most of it was fixed with related patches above for all branches.
