### ISSUE TITLE
[TBC] Gossip Menu Bug When Trainer or Vendor Only Has 1 Option Available

### ISSUE THREAD

**Issue by stan84** [cmangos/issues#630]
Gossip_menu_option not showing, when trainer or vendor has only 1 gossip_menu_option avilable.
its not working like on this example:
lets vendor talk to players - greetings bla bla ...
Player chosing menu option " show me your stuff...babe (only one menuid avilale)
showing stufff... buying selling etc

creature #79771 is good example of that 

when creature has 2 or more option menu's it's working fine.

**Comment by Saben65** [comment]
This was a change blizzard did due to player feedback. I am not certain when exactly it took place, but I wanna say I first noticed it sometime after the release of TBC, before WotLK. It definitely wasn't there in Vanilla. The only real references I could find after 30 minutes of googling were addons created between 2012-2014 that describe it as a change blizzard made a while ago, and they never implemented a feature to disable it. 

Sometime during WotLK they implemented this function to revert it that could be run from the chat window. (Doesn't work on cmangos)

/run ForceGossip = function() return true end

**Comment by cyberium** [comment]
Not clear to me maybe TBC users/devs could confirm its still present?

**Comment by al3xc1985** [comment]
I don't think this is still valid @killerwife

**Comment by killerwife** [comment]
This is done automatically by client. This was verified by me running client in debug mode. Not a bug.
