### ISSUE TITLE
[Classic] Flasks

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#636]
Core 2644

You can stack all four flasks. That should not be possible.

**Comment by MarcoPolo87** [comment]
You can stack all four flasks in vanilla.  This was only done in hardcore PvP since it was pretty expensive back in those days.  The stacking of all four flasks was removed with the launch of The Burning Crusade.  You could also "chain chug" health and/or mana potions while in combat.  As soon as the cool down expired, you could drink it again.

With the release of The Burning Crusade, Alchemy was nerfed and "potion stacking" was no more.  This was due to PvP balancing.  in The burning Crusade Flasks and Elixirs were re-categorized as Battle and/or Guardian elixirs.  Some of the new Flasks produced a buff that counted as both a Battle and Guardian elixir.  I was an alchemist in vanilla on my warrior, and I loved stacking my flasks and elixirs.  =)    I was sad when that was taken away.   =(

Also, one of the The Burning Crusade patches, around the release of the Tier 6 Black Temple Raid, Blizzard locked Health and Mana potions to "one use" while in combat.   I used to chain chug health potions while Endurance Tanking the Fel Reaver at level 70 in Tier 5/6 Gear.  I wish I still had that video of me soloing him.  =(

I used to have two nice videos with both examples from Live but, as with most things, they were lost when my HDD died.

PS:  I searched youtube for an hour watching raid videos, but most videos did not even show the player using a flask or elixir.  I guess only the "Top Raiders" might have actually used the Flasks on a regular basis in Vanilla wow.  As I said, I remember them being really damn expensive.

**Comment by cala** [comment]
Unfortunately, you could not stack two flasks in Vanilla. Only one was active at a time, for 1 hour, persisting through death. The none-stacking rule was even written in the tool tip.
So @Kelzior is right on this, yet @MarcoPolo87 is right about other elixirs (basically, players could stack as many elixirs as they wanted in Vanilla).

**Comment by MarcoPolo87** [comment]
@cala Thanks for the clarification.  I was probably exploiting a Bug/Glitch with the flasks, as was commonly caused by game patches, back in those days.
