### ISSUE TITLE
[Classic] Caster line of sight bug

### ISSUE THREAD

**Issue by Etherstream** [cmangos/issues#656]
If you get out of line of sight of a caster mob, they'll stand there doing nothing before you get in line of sight with them again. Happens everywhere, instances and outdoor world.

**Comment by Patman64** [comment]
EventAI is not currently robust enough for good LoS handling. There's an event that fires when a the target is too far away, but no event that fires when the target leaves LoS.

**Comment by evil-at-wow** [comment]
I believe they actually run to you and thus move in LOS again when you enable mmaps. I'm not saying it's perfect then, but at least it makes a better experience.

**Comment by Etherstream** [comment]
I have mmaps enabled so that shouldn't be the issue.

**Comment by evil-at-wow** [comment]
All right, perhaps I was lucky to have a few cooperating casters then :smile:
Thanks for the info.

**Comment by Kelzior** [comment]
I would like to get fixed this asap. People can abuse the bosses easily.

**Comment by Kelzior** [comment]
Bump on this

**Comment by cala** [comment]
There is already a discussion open about this issue: https://github.com/cmangos/issues/issues/180 which is part of a bigger one about updating the NPC AI system (see also: https://github.com/cmangos/issues/issues/588 and http://cmangos.net/thread-6742-post-42494.html). I would not expect a fix soon on this.

In my experience, NPC casters losing Los follow their target if the target (usually a player) moves out of range. If target is still in range, casters remain stuck.

I'm closing the issue here, let's concentrate the discussion into one place.
