### ISSUE TITLE
[Classic] Sidequest availability

### ISSUE THREAD

**Issue by Muehe** [cmangos/issues#664]
*Might be an issue for other cores as well, but only tested on classic.*

There seems to be a problem when two quests share a negative ExclusiveGroup (so both must be finished before continuing) and they both have a child quest. The child quests will only become available when both parent quests are accepted, while they should become available as soon as their respective parent quest has been accepted.

For more info see https://github.com/classicdb/database/issues/761

**Comment by killerwife** [comment]
From what I understand, after parent quests are accepted, you should immediately gain access to child repeatable quests, but this should happen even if you accept only one (and get only one child quest respectively). After you complete both these quests (the non-repeatable ones), you should get a third quest. Gonna try to look at it.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/pull/37
Added one condition check for this issue. The code was checking whether the quest has its parents all active due to how exclusive group is handled. Added check so that a branch quest off only one of the exclusive group quests is shown (both in case of having a show when active and show when complete parent). 
Same fix needs to be applied to WOTLK and Classic and the issue closed. As I am currently struggling a bit with github and stuff, would really appreciate if someone could do it.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-wotlk/commit/7ee8d7e2d1962723e61d68688aa2b9abd270e1d6
https://github.com/cmangos/mangos-classic/commit/acef9e7b6cc373013736274186f290eaab8cfe6f
https://github.com/killerwife/mangos-tbc/commit/7025e072e6f2b25565718791d6040f49054bbe0e
Tested on TBC core, needs testing on vanilla/wotlk.

**Comment by Muehe** [comment]
Thank you both :+1: Will test "soon"™
