### ISSUE TITLE
Classic Crash Log 2!

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#701]
http://pastebin.com/1BjZkz3a

**Comment by Kelzior** [comment]
@xfurry

**Comment by evil-at-wow** [comment]
This is a real crash. And the only possible explanation I see, is that an item or object gets added to the list of world objects that needs to get an update at the client, but then gets deleted before we're actually sending the update to the client. I can't tell how that can happen yet.

Do you have any idea what instance caused the crash, and what was happening when you got the crash? For example interaction with a specific GO or something? I'm just asking, because it could help us reproduce this issue and debug it.

**Comment by Kelzior** [comment]
Probably aq20. You should check the General. When you start killing the adds of the 2nd boss. I couldnt reproduce it but some players did report this

**Comment by Kelzior** [comment]
Closing, opened a new clear one #703 #704 #705 #706
