### ISSUE TITLE
Classic Crash Log 3!

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#702]
http://pastebin.com/5x3VaFBU

**Comment by Kelzior** [comment]
@xfurry

**Comment by evil-at-wow** [comment]
That log is pretty messed up. It's like it's mixing multiple outputs, and sadly, we're even missing a part. The most interesting part of the stack trace no less, pointing to the code that actually crashed. Other than saying that it seems very similar to the one in #701 I can't do much with that log.

If this is actually what you saw in the console or the log file, rather than say a mistake while copy/pasting, then we have another problem in the core! Could you check the log file again please?

**Comment by Kelzior** [comment]
No the link of the log is complete but I got 2 logs from the same crash (same time) http://pastebin.com/iB2jnNBx

**Comment by Kelzior** [comment]
Closing, opened a new clear one #703 #704 #705 #706
