### ISSUE TITLE
[Classic] Creatures aren't moving (visually).

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#729]
Whenever your client is updated with creatures that should be on the move (random or waypoint) already, they won't move until the server sends the next SMSG_MONSTER_MOVE. If it does, the creature will start running to catch up. This looks nasty.

Is there something in SMSG_UPDATE_OBJECT?

This does not happen if the creature is freshly spawned.

**Comment by Neotmiren** [comment]
Not sure about your description, but if it is the same issue as

1) .t Ironforge, quickly click on some waypoint-moving NPC and they are not interactable because server coordinates differ from client ones.
2) .t Westfall and quickly check nearest Harvest Golem behaviour, try attack from range etc. Also wrong client coordinates.

then these bugs are already fixed in my version of CMangos-Classic. I changed code of
Object::BuildMovementUpdate() to something like in current MangosZero repository (did not use any specific commits, so cannot point them).

**Comment by Tobschinski** [comment]
Yep, that's it.

**Comment by cyberium** [comment]
Fixed https://github.com/cmangos/mangos-classic/commit/0d95ddc14ad688380bf28c9ffb219a099459e96b
