### ISSUE TITLE
Vanilla - Mage Combustion

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#730]
Step # 1.Talents to make spell: "Combustion"
Step # 2.Use the spell: "Combustion" and make possible many stacks on "Combustion"
Step # 3.Then reset the talents without learn "Combustion"
Step # 4.After the first steps have unlimited " Combustion " 
Step # 5.The magic disappeared only when the hero dies.

What I mean: someone makes this bug with 9 stacks "Combustion" and all the time has a 90% Fire spells Critical chance.

**Comment by Kudos5** [comment]
I guess this is because the spell Combustion(11129) triggers the spell Combustion(28682) and when 11129 is unlearned the auras from triggered spells are not removed. So you could add a check for 11129 in Player.cpp::removeSpell() and then remove the aura from 28682. Or something more general like 
```c++
// remove auras due to triggered spells
const uint32* triggeredSpells = sSpellStore.LookupEntry(spell_id)->EffectTriggerSpell;
for (uint32 i = 0; i < MAX_EFFECT_INDEX; ++i)
    RemoveAurasDueToSpell(triggeredSpells[i]);
```
also in removeSpell()

I don't know if this solution is good, but it seems to work. I never wrote anything for a project like this before, so I'd love to hear what you guys think.

And I suppose it's also a problem that the stacks of combustion are no longer being removed upon crits after 11129 has been unlearned.

**Comment by Kelzior** [comment]
Thanks I will test this tonight

**Comment by Neotmiren** [comment]
There is existing commit which fixes Combustion (applied it to my version of CMangos-Classic long ago):

https://bitbucket.org/mangoszero/server/commits/46f237a453cd6ae37fe313d51431c52a7060277f

More generic approach by @Kudos5 could be better, but only if there are no EffectTriggerSpell values shared by different spells. In fact shared values exist in spell.dbc, although they all might be related to different ranks of the same spell or to versions obsolete of spells...

**Comment by Kelzior** [comment]
Thanks alot!
