### ISSUE TITLE
Vanilla - Critical character glitch

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#735]
There is something that is moving the characters to other accounts. I am getting like 1-3 reports weekly from a server with around 50 online players. There are no custom edits, i am using the   current core of cmangos classic.  

What I know is that people are getting sometimes long "retrieving character list"  thing and probably it happens from there.

When a character glitch happens (to another account) the account ID from the characters db us getting changed from itself. 

Example

Account id = 5
It changes to a random number like 8

Then I change it back to 5 but it automaticlly changes to 8 after 10-15secs.

This will happen constantly till a server restart.

I also tried deleting the whole character from the db. But it comes back from itself.

Players are losing their bags when this starts.
Than they are getting DCs and when they relog, their character is gone.

This only happens to 1 character from their account.

This is a really critical bug and it needs to be fixed.

**Comment by Kelzior** [comment]
@xfurry
@cala

**Comment by Kelzior** [comment]
This happened already for around 10 different account/characters

**Comment by xfurry** [comment]
Sorry, I'm in holiday. :tropical_drink: No dev access until 5th September

**Comment by Schmoozerd** [comment]
sounds like memory corruption or a bad sql.

Maybe the UberInsert has a bug in classic?

**Comment by Kelzior** [comment]
Please someone look at this issue

**Comment by cala** [comment]
> sounds like memory corruption or a bad sql.
> Maybe the UberInsert has a bug in classic?

I agree that would look like this. 
However, it must depend on system configuration since I never had this once in years of using Classic cmangos (and zero before) though I very often restart the server or log in/log out for dev purposes. 
(still in holidays as for myself)

**Comment by evil-at-wow** [comment]
> Then I change it back to 5 but it automatically changes to 8 after 10-15secs.

> I also tried deleting the whole character from the db. But it comes back from itself.

That's probably because the server also keeps character data in memory and periodically saves this data to the DB. As a general rule: you can't just modify the character database while the server is running, and this is particularly true for characters that are logged in!

**Comment by Kelzior** [comment]
Will pay a nice amount to anyone that can fix this, contact me on skype; kelzo_    

This is a major for me.

**Comment by Kelzior** [comment]
100$ for the fixer

**Comment by Kelzior** [comment]
Will pay a nice amount to anyone that can fix this, contact me on skype; kelzo_

**Comment by evil-at-wow** [comment]
Assuming this is indeed a bug, the question is how we're ever going to debug what's happening. Because we can't fix bugs unless we discover what their root cause is...

Sadly, you seem to be about the only one that can reproduce this problem. So we can't exclude a hardware failure yet (I've seen bad memory modules twice where I work, and they sure caused some weird behavior). Now, I can imagine that you don't have a few spare machines to test with, but have you tried to run a [memtest](http://www.memtest86.com) on the machine that hosts your server (and database, if they should be hosted on different machines)? If not, could you do so? If anything, that could exclude a bad memory module as possible cause and narrow it down a bit.
