### ISSUE TITLE
classic : corpese

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#764]
summon creature corpse too much quickly remove the game(maybe 5s?)
so cant loot item...

**Comment by xfury** [comment]
maybe it is remove by db script.

**Comment by xfury** [comment]
player->SummonCreature(VISUAL_WAYPOINT, pointPath[i].x, pointPath[i].y, pointPath[i].z, 0, TEMPSUMMON_TIMED_DESPAWN, 9000);
like this.you can control it's despawn time.
and some summoncreature has other rules to despawn.

**Comment by ROKB** [comment]
@xfury  but all summon creature problem..

**Comment by devmaximus** [comment]
ROKB  i assume you are referring to the creature http://www.wowhead.com/npc=2773/orkalar who has respawn timer of 5 seconds and have multiple spawn locations. so if you kill him you have 5 seconds to  loot the target in-case the current spawn guid is going to be reused during the random re-spawn. 

take a look at creature table spawntimesecs, use the following query:

select c.guid, c.spawntimesecs, ct.`Name` from creature c
left join creature_template ct on ct.entry = c.id
where c.spawntimesecs <= 5
order by ct.entry 


this can only be resolved when cmangos implements dynamic guid for creature spawns where spawned creature will not require to reuse the same guid for current spawn when its in corpse state. for example corpse has its own timer for dispawn which may be longer then re-spawn (sometimes respawn is faster in official because of population farming various areas). to resolve this would require large amount of work to refactor in order to support this approach.

**Comment by Laizerox** [comment]
You could try this c9d3597016240dbe1d3c58642cd4d79e52a7a290

Will wait for feedback

**Comment by cyberium** [comment]
I think @devmaximus resumed the situation.
It seem that for some specific scripted creature they use default value wich are pretty fast.
So for those creature that have "realy" the need to be respawned fast there is no solution currently.
For other creature that uses default value they probably have to not use them and script/creature data have to care of that.

**Comment by ROKB** [comment]
@Laizerox work fine. thx
