### ISSUE TITLE
classic : every expendability item

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#773]
[img]http://i.imgur.com/1eaXVdQ.png[/img]

can use infinity item.

**Comment by ROKB** [comment]
회 사용가능 = can be use

**Comment by cyberium** [comment]
sorry i cannot understaind this could you please try to rephrase?

**Comment by ROKB** [comment]
@cyberium um... every expendability like potion and scroll can be use infinity..
clean mangos-classic core.

**Comment by evil-at-wow** [comment]
Based on the number in that screenshot and ROKB's second comment, I'm guessing the problem is that items with an effect that should last for a certain time are actually applied for 2,147,483,647 seconds (= 2^31 - 1). Which is like forever, practically speaking. So it looks like the core is using a -1 somewhere which gets translated into "the maximum value of a signed 32-bit integer" somewhere.

I'm just not sure if this issue is about the time the effect lasts (say a food buff) or a duration on the item itself. But that should be fairly straightforward to test if this is general problem.

**Comment by cyberium** [comment]
@ROKB thank for rephrasing :+1: 
@evil-at-wow thank for trying to explain ;)

I still not sure i get it.
So, some item have to disapear after certain time? Any concrete exemple that i can test and reproduce?

**Comment by ROKB** [comment]
@cyberium not disaprer.
make potion. and logout and login the same character.
check potion.

**Comment by cyberium** [comment]
Thank you very well for that last explanation @ROKB !!!

**Comment by ROKB** [comment]
@cyberium 
Don't mention it.:D
