### ISSUE TITLE
classic : creature corpse

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#774]
player kill the creature. creature condition is death(look) but still follow and attack player.
only can kill the area skill spell..

**Comment by ROKB** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="Z3vS959"><a href="//imgur.com/Z3vS959">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by killerwife** [comment]
the maximum HP is an addon, not serverside.

**Comment by ROKB** [comment]
@killerwife but clean db clean core.
still bug, so what's ur thinking?

**Comment by killerwife** [comment]
I would have to check the death issue, but the HP changing is an addon on the client, which is working as intended (im using the addon and that is its behaviour), cyberium is doing some backports for classic, just wait for that first.

**Comment by ROKB** [comment]
@killerwife  very well...
answer just waiting..
@cyberium

**Comment by cala** [comment]
> creature condition is death(look) but still follow and attack player.
only can kill the area skill spell..

@ROKB : Can you tell us how to reproduce that, please? I don't see anything wrong with dead creatures.

**Comment by cala** [comment]
After further checking. Poke @cyberium because the issue seems to come from: https://github.com/cmangos/mangos-classic/commit/4aacdaf942df9eeeee18d8e8a2c01588fc19cc6a
How to reproduce it:
- use a rogue
- attack a NPC and build combo points (max is best)
- when NPC is near death, use Kidney Shot to stun it
- kill it with attacks/skills while it is still stunned
- run away from the corpse => the corpse will follow you (not everytime, I did not find yet how to reproduce it 100% of the time)
- type `.gm on` then `.gm off` : the corpse moves to its spawn points and is instantly revived

I assume something prevent the NPC from having the correct status change alive->dying->dead.

**Comment by cyberium** [comment]
Thank you @cala i'll check that next week.

**Comment by al3xc1985** [comment]
I remember the same issue in wotlk maybe was fixed dunno, a yes it had that issue too

**Comment by cala** [comment]
More info make the debugging more easy:
- I'm still unable to reproduce it 100% of the time (more like 10% even when trying, so this is not a frequent issue…)
- The corpse is able to do damage to the player (like if the NPC is still alive), those are displayed by the client
- Player is unable to attack the corpse via client (cast spell or attack) but if player use GM command (`.damage` for example), it can be damaged/killed
- On evade (`.gm on`), the corpse moves/slides back to it spawn point. Sometimes, it switches back to alive when it reaches the spawnpoint, sometimes as soon as it evades, sometimes while moving back: no rule here

**Comment by ROKB** [comment]
cmangos/mangos-classic@7f69ae8
https://github.com/cmangos/mangos-classic/commit/285a800e9d443c4380b218a87a2df0e288542ce4

this is problem. i guess

**Comment by cala** [comment]
Nice, thank you. I was pretty sure the chase movement generator was at fault. A division error, that would explain why it was so hard to reproduce.
