### ISSUE TITLE
classic : ffa loot system little problem.

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#784]
the other system gold share 1/n but ffa not 1/n.
every gold 1 person.

**Comment by cyberium** [comment]
Not sure i understoood but the ffa loot seem work

**Comment by evil-at-wow** [comment]
What ROKB was trying to say is that there was a problem with FFA (free for all) loot when it comes to sharing the gold: instead of n players each getting a fraction 1/n of the gold, as normal, all gold goes to one player only.

This was logged shortly after your rework of the looting code was committed, so maybe there was a problem at that point. I remember several loot related fixes in the weeks and months after that, so I have no idea if it's still reproducible, but that's easy enough to verify.
