### ISSUE TITLE
Classic CharacterDatabase.AsyncPQuery Hang

### ISSUE THREAD

**Issue by Razoray** [cmangos/issues#884]
Hello I have a weird issue, from time to time the Char Async is hanging/blocking which is causing to major problems.

Im using win32 (32g ram 6core) + mysql db
Cmangos + classicdb.

This mostly happens when there are +100 online.

Adding players to friendslist/ignore takes ages and when you try to login it gets stuck at retrieving characters list for 5-30 mins.

Loading screen takes a long time aswell.

So basicly the async threads gets blocked by something..

After a restart, everything is back normal.

I changed from server and mysql some months ago but this happens.

Any ideas which can cause this issue?

**Comment by Razoray** [comment]
Noone?

**Comment by cyberium** [comment]
Well, some major change occured in network code, including database code. So there is no point to start trying fixing something related to it before those change are applied to classic.
Currently only WoTLK is merged, TBC and Classic update will occur soon.

You will have to update your core, confirm that it still occur, and try to find the best way to replicate it 100%. Because those kinds of problem are generaly hard to find for devs.

so for now the best is to close this issue, we will reopen it if required.
cheer
