### ISSUE TITLE
[CLASSIC] Hunter Issues with Concussive Shot

### ISSUE THREAD

**Issue by Draparn** [cmangos/issues#895]
**Current behavior**: 
A. Fleeing mobs unaffected by Concussive Shot.
B. Revive Pet revives at the location of death, not next to the Hunter.
C. Auto Shot keeps shooting when deselecting target and after target is dead unless you manually cancel "Auto Shot".

**Expected behavior**: 
A. Mobs should have reduced movement speed when dazed.
B. Pet should revive next to the Hunter.
C. Hunter should stop firing when there's no target.

**Steps to reproduce**:
A. Get a mob to flee and fire Concussive Shot.
B. Get pet killed and cast Revive Pet.
C. Start shooting a mob and then left click to deselect it.

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 

**Operating system**:

**Comment by Argonn** [comment]
Together with point B. It is also possible to outrun your pets corpse (making it despawn) and then use 'Call pet' to call it back with 1 hp (without having to revive it, and saving tons of mana)

**Comment by Phatcat** [comment]
https://www.youtube.com/watch?v=SwLjJH8LXfc&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n 2:23

**Comment by dagochen** [comment]
@Phatcat What is there at 2:23?

**Comment by Phatcat** [comment]
> Current behaviour:
(...) 
C. Auto Shot keeps shooting when deselecting target 

-

> Expected behaviour:
(...)
 C. Hunter should stop firing when there's no target.

what exactly is happening at 2:23?

**Comment by Phatcat** [comment]
So the only thing left in this issue is point A.
Point B was handled months ago point C is really a 2-part issue where the first part of it I'm denying with my comment there and the second part of it (not stopping auto shooting on dead target) has also been solved in the past couple of months. Point A may also have been solved as well, I'm gonna get around to testing that eventually.

**Comment by dagochen** [comment]
Nah...that is considered Lag/delay in your video. The animation is done, then target is lost...ofcourse shot goes out.

**Comment by Phatcat** [comment]
.... If that was just lag/delay, then the icon would not still have been highlighted in the bar.

If you want an example of client lagging behind server look at video 2 at 53:19 (she doesn't lose her target before she gains 'resting' status - that we know she ought to)

**Comment by Phatcat** [comment]
Not only that, she even fires the second shot AFTER having deselected the target, and she is about to fire a third shot before the target gets too close.

**Comment by dagochen** [comment]
Ask any hunter from classic he will deny that behaviour :/

**Comment by Phatcat** [comment]
Probably a reason most hunters used to go by the term huntard.

I really do not care what you or others 'think', prove it or give up on it. Did you even play back in vanilla?

**Comment by dagochen** [comment]
Yep...stopped my autoattack in PvP in cases of icetrap by deselecting...

**Comment by Phatcat** [comment]
Would you care to prove that? 
Because I can also remember pets going hostile when you abandoned them but without proof it's not gonna get implemented, or we may as well make any change that anyone thinks he can remember. That's not how we work.

Not only that, I have proof of the opposite. I myself never got my hunter past level 35, and I frankly don't recall this at all personally, and even if I did it would make zero to no difference. You can act as offended or as much in disbelief as you want, it serves you nothing. Spend the energy looking through patch notes and old pvp videos instead.

**Comment by adellaci** [comment]
I have to side with Phatcat on this one. I only played my Hunter in classic and I believe that was how it behaved, I also had the same behaviour with my Warlock using a wand with auto. Also believe that was a topic on conversation with Blizz devs too at the time. It caused problem during instances when we was suppose to pull back from attacking, I got chewed out a couple of times. I believed it got changed, but i can't remember when, because i just got in the habit of shutting auto off.

**Comment by BareRose** [comment]
I've done a brief test of point A and it seems like the slow is working correctly, would still be nice if someone else could confirm. If I'm right and @Phatcat is right about points B/C then this issue should be closed as it has been fully addressed.

**Comment by Phatcat** [comment]
All of the issues mentioned in this issue has been resolved.
