### ISSUE TITLE
SOAP ip binding fails.

### ISSUE THREAD

**Issue by Undergarun** [cmangos/issues#904]
**Current behavior**: SOAP bind to ip not working. Binds to all interfaces ignoring config value.

**Expected behavior**: SOAP listener should bind to ip indicated on config file.

**Steps to reproduce**:
1. Change soap bind ip to different ip than "0.0.0.0" (All ips on server)
2. 
3. 

**Client version**: Classic, TBC, WoTLK

**Commit hash**: Since  @6d178567724adbaed75a2d0d4ff902b630d4ff26

**Database version**: Not applies

**Operating system**: Linux.

@namreeb

**Comment by Undergarun** [comment]
news?

**Comment by Warlockbugs** [comment]
All known IP binding issues are fixed now.
This issue is fixed in:
https://github.com/cmangos/mangos-classic/commit/50992bc84b8e65c4e595f0791c1bcc2a1fee57ff
https://github.com/cmangos/mangos-tbc/commit/6302c8ad056f0e0e06201243a550e5691644aecb
https://github.com/cmangos/mangos-wotlk/commit/b79236f7576699f430dc4729095bae850e450664

**Comment by Undergarun** [comment]
Thank you so much!!!
