### ISSUE TITLE
[Classic] Caster NPCs are in auto-attack mode while casting

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#916]
**Current behavior**: 
Caster NPCs are in their "prepare attack" animation in melee range while casting spells instead of their casting animation, and they do a hit between two spell casts. Check the video:
http://webmshare.com/8G3Wg

**Expected behavior**: 
Caster NPCs should always use their casting animation while casting, and I believe they should not hit between two spell casts. I think the ones with offensive spells should only attack when they are out of mana.

**Steps to reproduce**:
1. Find an offensive caster mob (ex.: http://db.vanillagaming.org/?npc=1522 or http://db.vanillagaming.org/?npc=474)
2. Engage in combat with the caster and move to it's melee range.

**Client version**: 
1.12.1

**Commit hash**: 
6f501dedc751b6acc7a272823f4f70d2fec1b7c9

**Database version**: 
v1.6.5 'The Wailing Pet, The MidSummer Joy and all that sort of things'
Using most recent classicdb + scriptdev2 + acid to date.

**Operating system**: 
Debian

**Comment by killerwife** [comment]
@Phatcat

**Comment by Phatcat** [comment]
[In this video](https://www.youtube.com/watch?v=cb8L2CW2C-0)
At 1.30 - if the creature casters's target is outside of some range, (would personally guess the hunters no ranged zone), then it will start chugging spells, but if its target is in range (at 1.40) then it will go straight to melee, probably never doing their offensive spell unless it's instant. This is evident of the somehow relatively later video [here](https://www.youtube.com/watch?v=hKzAgtBy0qQ) , at 0:17 the furbolg to the left will start chain-cast, because its target is never within this 'range' when it does its check to see if it should melee. Yet at 0:30, the spellcaster to the left will never do his lightning bolt. not once in the entire fight. I strongly believe this is because its target is within range.

The reason I believe the zone is further than just melee range is because caster mobs were indeed kitable back in the day, but only very slowly. I remember that actually. You just had to do it in small steps at a time or they would go back to chugging spells at you.

What I would really have loved, is a video showcasting a spellcasting mob rooted JUST outside of melee range of its target to see if it would go to spellcasting or not? - it probably would and should.

**Comment by katz1** [comment]
@Phatcat 
I may be misunderstanding you, but are you implying that every caster creature started to attack in ~8 yards?

I don't believe that was the case in vanilla. In the videos you posted the caster creatures are clearly having melee capabilities as well, so they are something like hybrid casters (shamans in the case of furbolgs). But 'pure casters', the ones usually with low armor never started to melee in close range as far as I remember. Otherwise I wouldn't have used Kick so often with my rogue on them.

**Comment by Phatcat** [comment]
@katz1 :
[this guy](https://youtu.be/d85xDraICrs?t=6m14s) - this npc is a caster (he has a knife for melee..) he has lots of mana, and he is casting a spell. But notice what happens as soon as the player goes out of line of sight - the mob gets closer, and now he is much more interested in and busy knifing, rather than casting. All casters had melee capabilities, cause they were not defenseless when you silenced them. I did not play a rogue much, but it sounds like you did. Did you encounter any mob not going for melee when silenced?

If you are however right that some caster mobs would always prefer casting nomatter the distance to their target, then the mob [here](https://youtu.be/FmT3oyRUB_o?t=7m4s) clearly also shows that caster mobs _do_ melee in between casts, as he goes _straight_ for combat stance as soon as he is done casting.
We do however clearly see a caster run straight up next to his target and start casting, which confuses me, unless it was just due to bad pathfinding and the mob would have gone over to just melee, which his stance kind of indicates. Too bad we don't find out in that video.

Also, I farmed timbermaw in vanilla, to exalted - they were casters those ones, not hybrid fighters.

**Comment by Grz3s** [comment]
2 things with this and probably with most of casters:
1st:
Pls look how NEW Dynamic movement system works...

In this case...
```sql
('152201','1522','4','0','100','0','0','0','0','0','49','1','0','0','22','1','0','0','0','0','0','0','Darkeye Bonecaster - Enable Dynamic Movement and Set Phase 1 on Aggro'),
('152202','1522','9','5','100','1','0','40','3400','4800','11','13322','1','0','0','0','0','0','0','0','0','0','Darkeye Bonecaster - Cast Frostbolt (Phase 1)'),
('152203','1522','9','5','100','1','9','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Darkeye Bonecaster - Enable Dynamic Movement at 9-80 Yards (Phase 1)'),
('152204','1522','9','0','100','1','0','8','1000','1000','49','0','0','0','0','0','0','0','0','0','0','0','Darkeye Bonecaster - Disable Dynamic Movement at 0-8 Yards'),
```
Most intersted for us here is range between 0 - 8 yards... here .. he is able to do male. above it he will only cast spell - if mana is > needed to cast it)

2nd.
Look at spell itself:
ID - 13322 Frostbolt
```code
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 5) "Long Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 40, MaxRangeFriendly = 40
```
This info is official and canot be changed...
So for this creature: spell can be casted even if player is close as 1yard to him...

Because of that.. You will see situation (1-8y) where between casts he can do male also. Shouldnt he? (just checked on blizz - he casts spells and does the same...(maybe in more smoothly way - but hey... we are not blizz).
If this still anoying you... 

than you can change this:
```sql
('152202','1522','9','5','100','1','0','40','3400','4800','11','13322','1','0','0','0','0','0','0','0','0','0','Darkeye Bonecaster - Cast Frostbolt (Phase 1)'),
```
into this:
```sql
('152202','1522','9','5','100','1','5','40','3400','4800','11','13322','1','0','0','0','0','0','0','0','0','0','Darkeye Bonecaster - Cast Frostbolt (Phase 1)'),
```
Between 0-5y.. he will do only male
Regards

**Comment by katz1** [comment]
@Phatcat 
I admit I was wrong regarding the absence of attacking, and I think this is the clearest proof:
http://www.youtube.com/watch?v=jTSyexUNN9E&t=13m27s

But the main focus of this issue was meant to be **how** the casters attack currently, which is still wrong because they try to attack and cast at the same time. Please check this vid, it might be a bit better than the last one:
http://webmshare.com/jjLwW

**1.** The casters are using an attack animation during casting (while they clearly have a casting animation, unlike furbolgs).
**2.** The casters are not alternating between attack and cast modes, but they throw in an **instant** hit between two almost continuous spellcasts.

**Comment by Phatcat** [comment]
@katz1
You are right, these are different issues, and what you showcase is a bug, and should be fixed, I am in no way contesting that =) - the issue with the AI about which sort of engagement it should prefer under what circumstances was however at least half your issue report, and so I addressed that.

**Comment by Phatcat** [comment]
So what should happen is that non-controlled npcs should disengage auto-attacking right before casting, then reengage in auto-attacking straight after. This would remove the instant hits happening between spells as they'd have to wait for next weapon swing.

**Comment by katz1** [comment]
> the issue with the AI about which sort of engagement it should prefer under what circumstances was however at least half your issue report, and so I addressed that.
Sorry, for some reason I thought it was overlooked.

**Comment by Phatcat** [comment]
**https://github.com/cmangos/mangos-classic/pull/166/commits/a4a531ae40735e0736d89fa3a12458c67f564e0e**

**Comment by Phatcat** [comment]
https://github.com/cmangos/mangos-classic/commit/c05169266f7a57798c4e99ecd261bbd6c3ccd8f3
