### ISSUE TITLE
[CLASSIC] Ranged mobs don't follow on losing LOS

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#922]
**Current behavior**: 
Ranged mobs just stand and do nothing when out of LOS (Line of sight)

**Expected behavior**: 
Get in line of sight and fight!

**Steps to reproduce**:
Find ranged mob, pull it, run behind corner/tree/whatever

**Client version**: 
1.12.1

**Commit hash**: 
N/A

**Database version**: 
N/A

**Operating system**: 
Linux

**Comment by katz1** [comment]
@SatyPardus 
Could you specify where / with which mob did this happen?
Caster mobs have always chased me nicely.

**Comment by SatyPardus** [comment]
https://youtu.be/86t2rFwabT0 Here is the bug in video form :)

**Comment by Muehe** [comment]
I think following on LOS break works in EventAI's DYNAMIC_MOVEMENT but not in COMBAT_MOVEMENT and DB devs are in the process of switching out those movement types.

@Grz3s might know more.

You could try something like this to see if I guessed right:
```sql
-- Switch from ACTION_T_COMBAT_MOVEMENT to ACTION_T_DYNAMIC_MOVEMENT
UPDATE creature_ai_scripts SET action1_type = '49' WHERE action1_type = '21';
UPDATE creature_ai_scripts SET action2_type = '49' WHERE action2_type = '21';
UPDATE creature_ai_scripts SET action3_type = '49' WHERE action3_type = '21';
```

**Comment by killerwife** [comment]
I advise you to check out TBC ACID ^^

**Comment by cala** [comment]
@SatyPardus greetings and thank you for your report and interest in CMaNGOS. :smile: 

The issue you are reporting is related to the mobs AI and not to the core (server). The feature where casters follow their target if it moves out of LoS was introduced in the core a few months ago. It may need some improvements but is working pretty well in my opinion.
However, this feature has to be manually added in every mob's AI that requires it. This is the job of [ACID](https://github.com/ACID-Scripts/), one of the sub-projects of CMaNGOS. A good bunch of the AI are updated in the TBC branch. Many of them are already backported to the Classic branch by myself or to the WotLK branch by @Grz3s . More will come when we can spare the time.

Based on the above, I'm closing the issue here. Thank you.

**Comment by Phatcat** [comment]
@cala And this is why we have to rewrite the AI and base it on classes, because writing ai for every mob is.... thats... The AI needs an update.

**Comment by cala** [comment]
We discussed this and I fully agree. Question is: who has the time *and* knowledge to do this? Currently everyone's plate is already full. But being one of those who update the AIs, I agree indeed.
