### ISSUE TITLE
[CLASSIC] Rogue Setup

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#938]
Setup does not work at all. Should give combopoints when dodge / resist opponents attacks.

**Comment by dazidkk** [comment]
Bump Still an issue :-)

**Comment by jimmybrancaccio** [comment]
@ROKB or @dazidkk Can you confirm if this is still an issue on the latest builds?

**Comment by Phatcat** [comment]
Rogue setup is broken in a whole other way currently, instead of doing what it says so in the tooltip, 45% chance to add a combopoint every time the rogue dodges the attacker or resists their spell fully, what is currently happening though is that the rogue with about 90% chance will add a combopoint on the target if the attacker dodges or parries the rogue.

**Comment by jimmybrancaccio** [comment]
@Phatcat Do you know if this is still a problem?

**Comment by Phatcat** [comment]
It was when I tested it just a few months ago. If you are curious as to if it's been fixed since, why don't you go ahead and test that? has there been any known efforts on rogue combo point system? have you TRIED to replicate the issue yourself and failed?

I can't even be bothered actually testing it and reporting back again even though I did that for you the first time, because in a few months with no work on the issue you're just gonna ask again anyways, or maybe you'll just outright close the issue. And I frankly have better things to do than reaffirming the same issues over and over again.

**Comment by jimmybrancaccio** [comment]
I've asked you if it was a still a problem @Phatcat. No need to be snarky and rude (as you seem to always be).

I've left the Need Replication label on it so someone can replicate it. If you don't want to that fine. Just leave a simple comment stating that you don't have time or that you don't want no. Thanks.
