### ISSUE TITLE
[Classic] Crushing Blows

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#949]
Lower level mobs dealing Crushing Blows .
100% frequency until you start to get within the weapon skill - defence skill formula margin used by the core calculation.

I can see and understand the calculation used in the core (word for word from http://vanilla-wow.wikia.com/wiki/Crushing_blow. Which one came first ?), whether I am convinced is another matter, but what about some modifiers on top of this, where are they ?

I thought it was > player level +3 before crushing blows were possible at all.

I believe this is part of the nagging feeling in the back of my head since the huge amount of work I did yesterday (and then scrapped because I couldn't prove my point) on questioning the Mor'Ladim commit.

Create a character, .level 59, fight a lower level mob that meets the existing calculation (I used a 32/33ish because I was testing something in STV), see those crushing blows come it at 100% frequency.

**Comment by Phatcat** [comment]
Please don't use unreliable sources like vanilla wow wikia, use cached wowwiki or cached allakhazam sites.

http://wowwiki.wikia.com/wiki/Crushing_blow?oldid=349008

**Comment by Zooke** [comment]
My link to that site was to show that the core code (including comments) is a verbatim copy of what is written on that ste.

**Comment by Phatcat** [comment]
Well, both yes and no, actually =)

Nothing in my link states anything about the mob having to be above the players level. so either this issue report is incomplete or faulty. You still are short of providing the proof for what this issue is based upon.

> When the attacking mob has 15 or more points of weapon skill above the player's base defense there is a chance of being struck by a crushing blow. The chance is 2% per point of difference minus 15%

So a mob will need 65 more skill points for 100% crushing, (or 13 levels going by default values)

But yes, a 100% crushing is very much possible for a mob.

**Comment by Phatcat** [comment]
So in your example, the level 32/33 mob will actually be doing 100% crushing blows upon you untill your defense skill reaches roughly 100, by which his chance will slowly diminish the closer your defense skill gets to his weapon skill.

**Comment by Zooke** [comment]
I will try to find any evidence I can, this Ghostcrawler quote from July 2008 confirms the existence of the +3 mechanic, but as you will rightly point out, maybe it was introduced after 1.12

**Comment by Phatcat** [comment]
Also if this is targeted towards a specific era of woW please add it to the issue title as this issue hub is for vanilla, TBC and Wrath - I took a guess that this issue was refering to vanilla since you used a site called vanilla-wow

**Comment by Zooke** [comment]
I am indeed referring to vanilla, unfortunately so far this is the closest I can get.
But, also contained in that quote is this

> Crushing blows originally served a dual-purpose: they discouraged you from attacking mobs much higher level than you, and they made bosses more challenging.

This statement would (on the basis my raised issue) appear to be untrue.

**Comment by Phatcat** [comment]
@Zooke I don't think you are out of your depth here, I just think you may be going by the wrong sources. the reason these new 'vanilla' wiki and db sites are unreliable is because they are all made after Vanilla did not even exist anymore; so where they got their data is anybodies guess, and usually a lot of that data is from private servers, private servers we can never be sure have the correct info.

.... I know I don't come off as a very pleasant person, and I am sorry if I've caused you any pain or distress, but please know that you could never waste my time... that is not why I do this... so I won't be reviewing any of your commits or issues anymore, someone else can probably handle that with more care. Please don't feel discouraged from contributing to cMaNGOS in the future because of me.

**Comment by Zooke** [comment]
Thank you for your gracious reply,
Please do not in any way change because of my sensitivities (real-life has been testing today), the work being done on your pet pr is worthy of anyone's admiration.
This was just supposed to be something to distract from my normal gaming duties at http://zlogames.ru/index.php?/profile/30411-zooke/
No harm done and can't wait for the new pet stuff to be finished. Good Luck.

**Comment by Zooke** [comment]
If I cannot convince with a quote from https://en.wikipedia.org/wiki/Greg_Street then I do not believe any evidence will ever be enough.
I do not know who authored http://wowwiki.wikia.com/wiki/Crushing_blow?oldid=349008 but do they really have greater knowledge than the person "employed by Blizzard Entertainment as Lead Systems Designer on the award-winning MMORPG World of Warcraft"
However;
As a final (I promise) post-script to this, if I stand back and look at our conversation, I see that I have in fact created a 'white elephant'. By manufacturing a game situation that would have been virtually impossible to have happened on retail (having a high level character without a matching defence rating) we could argue 'til the cows come home' and never find any real evidence because on live, this never actually happened.
I therefore apologise unreservedly for dragging us both down this road.

**Comment by Phatcat** [comment]
Okay, I actually never stated that you were wrong on this, just that you needed to provide some proof. You did, because yes, we should rather trust the designer than the wiki, you are 100% right.

The thing is, this is not an issue you'd ever experience as a player, because it is practically impossible to find mobs lower level than you with a higher weapon skill than you have defense skill. Think about it. The reason you experience it, is because you instantly level up via commands, but players don't do that, players have to level by questing and grinding; NOT getting defense skill while leveling is practically impossible and you'd have to go to great lengths not to level up the skill. And since mobs need at least 15 more weapon skill than you have defense, hence it's de facto impossible to experience as a player.

I am however convinced you are right, and I think you should reopen this issue if you feel its worth doing something about in the core anyways.

**Comment by Phatcat** [comment]
@Zooke

https://github.com/Phatcat/mangos-classic/blob/73ac6cfc0ce6b891522e381c99911c199a89cf64/src/game/Unit.cpp#L2218

Looks like someone else was aware of this as well but never put in the actual check in our core (very strange).

Sorry.
