### ISSUE TITLE
[TBC] Quest: 10674 - Trapping the Light Fantastic

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#965]
**Current behavior**: 
Quest item summons an Imp to collect the orbs.

**Expected behavior**: 
In animate mechanical device should be summoned.

https://tbc.wowhead.com/quest=10674/trapping-the-light-fantastic

**Steps to reproduce**:
1. Find small light orbs in Razaan's Landing
2. Use Item

**Client version**: 
2.4.3

**Commit hash**: 

**Database version**: 
1.5

**Operating system**:

**Comment by Caladrea** [comment]
Looks like both the Alliance and Horde quest are using a creature instead of the correct item. 

Alli Quest 10674 is currently using creature entry 21926 instead of item entry 30852
Horde Quest 10859 is currently using creature entry 22333 instead of item entry 31668

`/* BLADE'S EDGE MOUNTAINS */
UPDATE creature_template SET ScriptName='npc_light_orb_collector' WHERE entry IN (21926,22333);`

I am new to mangos, so sorry for any incorrect wording. I have not been able to test if my findings are correct yet. Still trying to figure out where everything is, and what needs to be changed to implement changes properly.

**Comment by killerwife** [comment]
The script is for AI of mob, you cant script GO behaviour.

**Comment by AnonXS** [comment]
https://www.wowhead.com/quest=10674/trapping-the-light-fantastic

**Comment by killerwife** [comment]
Should be working fine now.
