### ISSUE TITLE
Classic latest verision ScriptNameAI Error Core Crash!

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#976]
**Current behavior**: 
ScriptName:boss_rajaxx
**Expected behavior**: 
[mangos.exe_[24-6_15-29-50].txt](https://github.com/cmangos/issues/files/331386/mangos.exe_.24-6_15-29-50.txt)

**Steps to reproduce**:
1. 
2. 
3. 

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**:

**Comment by shnibble** [comment]
Can you add some details as to what caused the crash (i.e. what was going on in game when the crash occurred)?

**Comment by Phatcat** [comment]
boss_rajaxx

It is a guy related to AQ I think, I'm not sure. I guess give yourself a ridiculous amount of health and go in and pick a fight with him and see if the core crashes after him attacking you for a few minutes; that was how i reproduced his other boss crash reports (the zg one)

**Comment by Phatcat** [comment]
Just went in and picked a fight with him and I don't think the issue is in his script as I didn't encounter any crashes, and I even let him have a go on me for a couple of minutes at different stages of health (I think the times I've fought him on retail vanilla can be counted on one hand... and I played a druid healer, so I was tugged away in the back usually..

**Comment by cyberium** [comment]
invalid issue
