### ISSUE TITLE
Ticket rework? Usefull?

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#984]
Would it be good when the ticket system is being reworked, to add some more information and fixes to it?
I expirimented a little bit with all of it and read online about it, started a little rework to add more functionality. Would something like this be worth to push to here?

And when yes, what are the rules for that? As the texts from the current ticket system are all in the database and fixed id's in the code, it's hard to push new ones into there. Hard coded only english texts are not welcome, right?

I also want to include the survey system and test a little bit more with it.

**Comment by Phatcat** [comment]
If you feel it's worth asking you must somewhat feel that it's worth pushing, and I'm gonna say go for it; you can never be sure it's going to get merged but surely it's worth the push if you believe it would improve upon something.

**Comment by Phatcat** [comment]
Abandoned?

**Comment by SatyPardus** [comment]
Working on it in free time^^ Just wanted to ask. Doesnt need to be in the issues :P

**Comment by Phatcat** [comment]
What with git and your e-mail, though?
 https://github.com/cmangos/mangos-classic/commit/acfa2a0cd438aff38268f5c8ddb7e2a909105143

**Comment by SatyPardus** [comment]
Huh?

**Comment by Phatcat** [comment]
Look at the author of that commit; you; 
but it doesn't know that you're associated with that e-mail (which is odd since I pulled your commit straight from your fork..)

**Comment by SatyPardus** [comment]
Weird :D I dont know anything about git stuff.

**Comment by evil-at-wow** [comment]
[offtopic]
His user isn't recognized by github in the commit in his repository either, so that's why it's not working with the commit you've linked, even though you've pulled that patch from his fork.

It means @SatyPardus is pushing commits to github with a different e-mail address than what's in his github profile, that's all. If you'd want to fix that, [the documentation](https://help.github.com/articles/setting-your-email-in-git/) explains how to check the current setting and how to change it. :smile:
