### ISSUE TITLE
Bug With Spellcasting in Gruul's Lair Script for High King Maulgar

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#985]
boss_kiggler_the_crazedAI

@VladimirMangos 

> Bug in unconditional use m_creature->getVictim() in
> if (DoCastSpellIfCan(m_creature->getVictim(), SPELL_LIGHTNING_BOLT) == CAST_OK)
> after early cast when boss target can lost.

**Comment by xfurry** [comment]
There is one point which I don't really understand about all these new crashes.

We had these scripts running for at least 5-6 years (2011 was the last time we changed anything there), and nobody complained about any crash on any reference to the ThreatManager, or m_creature->getVictim() or DoCastSpellIfCan().

Why did these things show up so now and why is this so suddenly a problem since it wasn't before?
I'm tempted to believe that it has to do with other recent core changes, most specifically in the spell or pet changes...

**Comment by killerwife** [comment]
@xfurry The JustRespawned patch by Cyberium broke a lot of SD2 shit, but I dont know if it influences this.

**Comment by Phatcat** [comment]
@xfurry Oh my god would you get off my back with my pet changes, how could they possibly have anything to do with this?

**Comment by killerwife** [comment]
Not all crashes are a result of recent changes. They are the result of renewed cmangos popularity.

**Comment by xfurry** [comment]
I'm not blaming anyone... I just raised that question. 
Not sure why some of you feel so stressed about this... 

If we need to revert the JustRespawned patch, then let's do it, and find a better way.

**Comment by cyberium** [comment]
Well we can revert it its easy enough and i will not feel hurted at all. However we will need to find an alternative. And in the best case a better alternative would be welcome.

Iam more thinking that is the result of some bad design in the code.
And finaly, i still have irl issues so i dont have enough time to investigate that more. But iam sure as soon as we can reproduce a crash we could find the real problem.

So,
1 - yes we are encountering some crash.
2 - yes we need to adress them asap.
3 - yes some of them are probably due to recent change.
4 - yes we will adress them one by one.
5 - yes we count on all of you to continue to open related issues or complete already opened.
6 - yes we are happy to see some movement here. More code added may involve more risk to get a crash but is it better to sleep and do nothing?
7 - feel free to revert any commit if you have a better alternative and if you understaind exactly what you are doing.
And finaly.
8 - Do all of that with a smile!

@killerwife what sd2 script it broke exactly? And if its the case its another design problem. Why JustRespawned was called automaticaly at each AIM_Initialize() for eventai and not for other AI?

**Comment by killerwife** [comment]
Well, just about 10+ of them :D (all escorts and more) Because in SD2 we differentiate between on AI init (in constructor) and on creature respawn. Only EAI is written so that JustRespawned occurs on start. I fixed it this way http://imgur.com/UkIQhSP not the most elegant solution, but the least intrusive.

**Comment by xfurry** [comment]
@killerwife give me a few examples of quests that broke.
I will investigate and fix this.

**Comment by killerwife** [comment]
City of Light (or any other escort)
Any quest that relies heavily on Reset(); function
Please dont fix it SD2 side in any way. It would mean much less control over scripts, and I do not want to be forced to make a "just respawned" overload everywhere. Look at the image I provided, and rather do something along the lines of that (something that enables more, rather than restricts more, since this is the whole point of SD2)

**Comment by xfurry** [comment]
First, let me investigate.
We will discuss the fix, before I push it.

**Comment by cyberium** [comment]
Well what i need is that JustRespawned and other like method are working exactly same way no matter the kind of AI.
Its not the case currently so i doubt we can fix that without changing some script.
@killerwife have some talent to find workaround but do we need this kind of code here?

**Comment by killerwife** [comment]
My argument to this is that many SD2 AIs are one shot scripts, i.e. they never "respawn" just "spawn". First of all, calling JustRespawned is super unintuitive, since IMO it should be called only after first death. Which means SD2 AI constructor takes care of that already, and having to script JustRespawned, instead of having it in constructor, is just fluff. Whereas in EAI it makes sense, because you can't script its constructor. 

My ability for creating workarounds is the result of stuff being broken on the main branch of development :D and running a server. (I couldve just reverted your AIM init change instead, but I didnt :P)

**Comment by xfurry** [comment]
> First, let me investigate.

Can you please give me some time here. I'm pretty sure we can fix this in an easy way. :wink: 
I'm busy right now, but I will try to look at this later today / tomorrow.

**Comment by killerwife** [comment]
@xfurry dont be intimidated by my response. Keep in mind I do not have any push rights :D I am only talking about it because I had to address it on vengeance ^^

**Comment by jimmybrancaccio** [comment]
Can anyone fill me in if this case and the issues described within are still problems?

**Comment by AnonXS** [comment]
I guess the above mentioned crashes related to

`ThreatManager`
`m_creature->getVictim()`
`DoCastSpellIfCan()`

are resolved again? @killerwife

**Comment by jimmybrancaccio** [comment]
@killerwife @AnonXS Any ideas on if the issue is resolved now, or does it still need some work?

**Comment by killerwife** [comment]
this should work properly nowadays.
