### ISSUE TITLE
[TBC] When Attacking Bosses mangosd Will Crash - CanReachWithMeleeAttack

### ISSUE THREAD

**Issue by wowx** [cmangos/issues#991]
**Current behavior**: 
Server crashes many times on CanReachWithMeleeAttack
**Expected behavior**: 
http://pastebin.com/hDL7zEDD
**Steps to reproduce**:
 Server crashes during fight with bosses The Lurker Below, Lady Vashj and many other.
**Client version**: 
TBC
**Commit hash**: 

**Database version**: 

**Operating system**: 
linux debian 8.2 64bit jessie

**Comment by Phatcat** [comment]
@xfurry @killerwife
Either a scripter is going to have to self assign himself and start looking at this with the scripts in question or I am going to make a generic failsafe in CanReachwithMeleeAttack. I am unwilling to stand by and continue to let us crash when I know we're perfectly capable of doing something about it.

**Comment by killerwife** [comment]
This is ehm. I know what the issue is but the problem is UpdateAI logic. This happened when player was killed/DCed/something after first GetVictim and before the call. To simply fix this we just need to enclose 
if (m_creature->CanReachWithMeleeAttack(m_creature->getVictim()))
with 
if(Unit* victim = m_creature->getVictim())
thats what vladimir hinted at last time and thats what should be done with it. Feel free to add the change @Phatcat, I know it will solve it.

**Comment by Phatcat** [comment]
no, no, no, no.

right now we have a system which allows for 'broken' scripts to crash our system.
It is too late; I am going to generically fix this in CanReachWithMeleeAttack. Because that is the core function. Which is crashing our system. Oh the calls will still be wrong in the scripts, but I am not going to fix that.

I am on the core team and the db team; I will soon have to do my own ACID work to make guardian pets and engineering work; now you're telling me to just do script work myself - You know the solution, you say you know it works; why are you telling me to do it and not do it yourself?

You wouldn't even basically touch up the PR with Laizer's commit that cala pushed to the core so now I'm going to have to bloat the repo with a commit clean that up; because I cannot leave bad codestyle without fixing it; but this is script work,

**Comment by killerwife** [comment]
Mainly because I am at work these days.

**Comment by Phatcat** [comment]
Best excuse ever. gonna have to give you a :+1: for that one.
Okay, I will look into the scripts then... but I still think it's a mistake leaving a our system open to crashing through CanReachWithMelee , faulty scripts or not.

**Comment by al3xc1985** [comment]
@killerwife i believw you fixed rhis

**Comment by killerwife** [comment]
Fixed yes.
